upgrades/run_docker_lib_demo.py, upgrades/setup.py, upgrades/tests/test_docker_framework_client.py, upgrades/upgrade_testing_framework/core/docker_framework_client.py
This change is to outline a bare-bones docker library to be used in this framework for starting and stopping a definable cluster. The `create_container` and `remove_container` have been fleshed out a little more to give a better picture of how these functions are planned to be expanded on. Also included is a sample script to run and demo these functions.
The goals of this PR are:
* To set direction early as to what would be helpful to have for this docker library (or maybe isn't necessary)
* What you would like to see added outside of the basic functions here
* Solicit critique for Python usage and best practices for a noob :smiley:
* https://github.com/opensearch-project/opensearch-migrations/issues/16
* Added unit tests for the code
* Added demo script for starting a cluster using this …
=> Add basic container create/remove for docker lib

.github/workflows/python-tests.yml
Signed-off-by: Tanner Lewis <lewijacn@amazon.com>
This change is to execute our python unit tests on opening of a PR and updates to a PR. It will also include code coverage to be added as a comment to the PR
Verified workflow is successful on personal fork
* https://github.com/lewijacn/opensearch-migrations/actions/runs/3641127326/jobs/6146687419
Two things I have noticed which are not blockers but may warrant minor additions in future
* Code coverage should be uploaded to the issue without token on codecov/codecov-action@v3 for public repos but this was not the case for my personal fork. This does not fail the Upload Coverage Report step as can be seen, but if this occurs for our migrations repo as well we may need a codecov repo upload token to work properly. I have seen other repos in …
=> Add python tests with coverage workflow

.flake8, .github/workflows/CI.yml
Signed-off-by: Omar Khasawneh <okhasawn@amazon.com>
This change applies linting on .py files, to preserve clean style of code.
Closes [#41]
=> Add linting (flake8) workflow to repo

.github/workflows/backport.yml, .github/workflows/delete_backport_branch.yml
Signed-off-by: Tanner Lewis <lewijacn@amazon.com>
This change is to setup the workflow structure for creating backport PRs when a backport label is applied to a PR that has been merged as well as a workflow to delete these backport branches once their respective backport PR is closed.
Only the default behavior has been added for now to set the structure, which is usually sufficient for most repos. However,  as the repo evolves we can adjust to meet our use case.
* https://github.com/opensearch-project/opensearch-migrations/issues/43
Tested in local fork of this repo by creating a sample Github app that is integrated into the repo (To generate APP_ID and APP_PRIVATE_KEY) and adding backport labels to a merged PR. Will try to document this process for others who may want to follow in …
=> Add default backport behavior

upgrades/setup.py, upgrades/unit_tests/clients/test_rest_client_base.py, upgrades/unit_tests/clients/test_rest_client_default.py, upgrades/unit_tests/clients/test_rest_ops.py, upgrades/unit_tests/cluster_management/test_node_configuration.py, upgrades/upgrade_testing_framework/clients/__init__.py, upgrades/upgrade_testing_framework/clients/rest_client_base.py, upgrades/upgrade_testing_framework/clients/rest_client_default.py, upgrades/upgrade_testing_framework/clients/rest_ops.py, upgrades/upgrade_testing_framework/cluster_management/cluster.py, upgrades/upgrade_testing_framework/cluster_management/cluster_objects.py, upgrades/upgrade_testing_framework/cluster_management/node.py, upgrades/upgrade_testing_framework/cluster_management/node_configuration.py, upgrades/upgrade_testing_framework/core/framework_runner.py, upgrades/upgrade_testing_framework/core/framework_state.py, upgrades/upgrade_testing_framework/steps/step_create_source_snapshot.py, upgrades/upgrade_testing_framework/steps/step_restore_source_snapshot.py, upgrades/upgrade_testing_framework/steps/step_test_source_cluster.py, upgrades/upgrade_testing_framework/steps/step_test_target_cluster.py
Signed-off-by: Chris Helma <chelma+github@amazon.com>
Adds a basic REST client library we can expand on to the UTF
* https://github.com/opensearch-project/opensearch-migrations/issues/50
Added Unit Tests:
```
(.venv) chelma@3c22fba4e266 upgrades % python -m pytest unit_tests/
========================================== test session starts ===========================================
platform darwin -- Python 3.10.6, pytest-7.2.0, pluggy-1.0.0
rootdir: /Users/chelma/workspace/Migration-Fork/opensearch-migrations/upgrades
collected 92 items                                                                                       
unit_tests/clients/test_rest_client_base.py .........                                              [  9%]
unit_tests/clients/test_rest_ops.py .... …
```
=> Updated UTF to use a REST Client instead of curl

cluster_migration_core/README.md, cluster_migration_core/cluster_migration_core/core/versions_engine.py, cluster_migration_core/cluster_migration_core/robot_actions/cluster_action_executor.py, cluster_migration_core/unit_tests/core/test_expectation.py, cluster_migration_core/unit_tests/core/test_versions_engine.py, cluster_migration_core/unit_tests/robot_actions/test_cluster_action_executor.py, upgrades/README.md, upgrades/upgrade_testing_framework/robot_lib/OpenSearchRESTActions.py, upgrades/upgrade_testing_framework/robot_test_defs/common_upgrade_test.robot, upgrades/upgrade_testing_framework/steps/step_perform_post_upgrade_test.py, upgrades/upgrade_testing_framework/steps/step_perform_pre_upgrade_test.py
Signed-off-by: Tanner Lewis <lewijacn@amazon.com>
Changes include
* Passing EngineVersion string to robot REST library to ensure proper REST client is used
* Minor fix to failing python test
* Robot tests additional documentation
* Minor fixes
None
UTF sample run 
```
(.venv) (09:25:13) local [/Volumes/workplace/opensearch/lewijacn-migrations/opensearch-migrations/upgrades] -> ./run_utf.py --test_config test_configs/snapshot_restore_es_7_10_2_to_os_1_3_6.json
[FrameworkRunner] ============ Running Step: LoadTestConfig ============
[LoadTestConfig] Loading test config file...
[LoadTestConfig] Loaded test config file successfully
[FrameworkRunner] Step Succeeded: LoadTestConfig
[FrameworkRunner] ============ Running Step: BootstrapDocker ============
[BootstrapDocker] Checking if Docker is …
```
=> Robot tests use EngineVersion for REST client and minor fixes

cluster_traffic_capture/docker_config_capture/Dockerfile
Signed-off-by: Chris Helma <chelma+github@amazon.com>
The mirroring SPOA suddenly stopped working, and switching from HAProxy 2.8 to 2.7 seemed to fix it.
Specifically, the HAProxy Primary w/ mirroring spun up fine and lived until you sent a request to it, at which point HAProxy dies with this message:
```
root@def18754cf21:/# haproxy -f /usr/local/etc/haproxy/haproxy.cfg
[NOTICE]   (125) : New program 'mirror' (127) forked
[NOTICE]   (125) : New worker (128) forked
[NOTICE]   (125) : Loading success.
[ALERT]    (128) : A bogus APPCTX [0x5651c586b880] is spinning at 4528372 calls per second and refuses to die, aborting now! Please report this error to developers [strm=0x5651c586b36
0,8 src=<SPOE> fe=mirror be=mirroragents dst=<SPOE> txn=(nil),0 txn.req=-,0 txn.rsp=-,0 rqf=80c020 rqa=0 …
```
=> MIGRATIONS-867 Switched to HAProxy 2.7

cluster_migration_core/cluster_migration_core/cluster_management/docker_command_gen.py, cluster_migration_core/cluster_migration_core/cluster_management/docker_framework_client.py, cluster_migration_core/unit_tests/cluster_management/test_docker_command_gen.py, cluster_migration_core/unit_tests/cluster_management/test_docker_framework_client.py, cluster_traffic_capture/cluster_traffic_capture/gen_haproxy_cfg.py, cluster_traffic_capture/demo_haproxy.py
Added a new log statement that generates an equivalent 'docker run' command to what the Docker Python SDK executes
N/A
Ran the HAProxy demo w/ debug logging to STDOUT.  We now have some idea of what actual command is executed when we tell the Docker SDK to run a container.
```
DEBUG:cluster_migration_core.cluster_management.docker_framework_client:Creating container primary-cluster-node-1...
DEBUG:cluster_migration_core.cluster_management.docker_framework_client:docker run --name primary-cluster-node-1 --network primary-cluster-network --publish 9200:9200 --volume primary-cluster-volume-1:/usr/share/elasticsearch/data:rw --ulimit memlock=-1:-1 --env cluster.name='primary-cluster' --env cluster.initial_master_nodes='primary-cluster-node-1,primary-cluster-node-2' --env …
```
=> Improved Docker "run" command logging

datastash/README.md, datastash/docker-compose.yml, datastash/index_template_base.json, datastash/logstash.conf
This change adds a `datastash` folder that houses the Logstash configuration (and Docker compose YAML). The purpose of "datastash" is to provide a Logstash container that users can easily customize to migrate all indices from a source cluster (Elasticsearch by default) to a target cluster (OpenSearch by default).
The folder also includes a `README.md` with instructions on how to use this tool to migrate data.
https://opensearch.atlassian.net/browse/MIGRATIONS-1005
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of- …
=> [Historical data migration] Added a "datastash" folder with Logstash configuration

TrafficCapture/captureKafkaOffloader/build.gradle, TrafficCapture/captureKafkaOffloader/src/main/java/org/opensearch/migrations/trafficcapture/kafkaoffloader/KafkaCaptureFactory.java, TrafficCapture/captureKafkaOffloader/src/test/java/org/opensearch/migrations/trafficcapture/kafkaoffloader/KafkaCaptureFactoryTest.java, TrafficCapture/captureOffloader/src/main/java/org/opensearch/migrations/trafficcapture/CodedOutputStreamSizeUtil.java, TrafficCapture/captureOffloader/src/main/java/org/opensearch/migrations/trafficcapture/FileConnectionCaptureFactory.java, TrafficCapture/captureOffloader/src/main/java/org/opensearch/migrations/trafficcapture/StreamChannelConnectionCaptureSerializer.java, TrafficCapture/captureOffloader/src/test/java/org/opensearch/migrations/trafficcapture/StreamChannelConnectionCaptureSerializerTest.java, TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/Main.java, TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/InMemoryConnectionCaptureFactory.java, TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/NettyScanningHttpProxyTest.java
Some incoming packets will be larger than what our offloading protocols (e.g. Kafka) can handle.  This change chops those messages into pieces (while retaining proper protobuf format) and sends them to the offloader. The offloader will provide the `CodedOutputStream` and thus can set the max desired size of the message which will be determined by the size of the `CodedOutputStream` ~~and can also provide the minimum chunk size which will limit the maximum number of data bytes that will be chunked~~. This functionality required minimal change for offloaders (Kafka, File, InMemory) and was mainly rooted in the Serializer.
https://opensearch.atlassian.net/browse/MIGRATIONS-1061
Manual testing with local kafka cluster and file directory and unit tests
By submitting this pull request, I …
=> [Traffic Capture] Add multipart support for offloading messages

TrafficCapture/dockerSolution/build.gradle, TrafficCapture/dockerSolution/src/main/docker/docker-compose.yml, TrafficCapture/dockerSolution/src/main/docker/elasticsearchWithSearchGuard/Dockerfile, TrafficCapture/dockerSolution/src/main/docker/elasticsearchWithSearchGuard/disableTlsConfig.sh, TrafficCapture/dockerSolution/src/main/docker/elasticsearchWithSearchGuard/enableTlsConfig.sh, TrafficCapture/dockerSolution/src/main/docker/elasticsearchWithSearchGuardDisabled/Dockerfile, TrafficCapture/settings.gradle, TrafficCapture/trafficCaptureProxyServer/kafka.properties, TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/Main.java, TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/NettyScanningHttpProxyTest.java
This change sets up an ES 7.10 image with search-guard so that a Capture Proxy image can be built upon that to use the TLS configs from the base image.  Additional command line arguments were used to be able to more easily manage starting the proxy in different contexts.
Search-Guard is installed (from a remote zip plugin) and is configured with the plugin's 'install_demo_configuration' script.
The elasticsearch.yml file is configured to support it coming up as a single node.
Additional changes are made to support our uses cases. Two simple scripts are added to the container to toggle TLS on/off via the configuration. TLS and HTTP auth are both disabled, as these are most useful for us at the moment.
Lastly, the image that is built from this docker file (which can also be done via gradle) …
=> Capture proxy container with tls and command line args

TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/CloseableTrafficStreamWrapper.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/HttpMessageAndTimestamp.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/ReplayEngine.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/RequestResponsePacketPair.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/SourceTargetCaptureTuple.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/NettyPacketToHttpHandler.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NettyDecodedHttpRequestHandler.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NettySendByteBufsToPacketHandlerHandler.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/RequestPipelineOrchestrator.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/netty/BacksideHttpWatcherHandler.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/transform/JoltJsonTransformBuilder.java, TrafficCapture/trafficReplayer/src/main/resources/jolt/operations/addAdminAuth.jolt, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/HeaderTransformerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/TrafficReplayerTest.java
This change fixes issues due to switching from the Log4J log lines to the protobuf captures.  Some of the events and signaling is different now.  As such, the state model to determine when a request and response has been fully received had to be updated.
NettyPacketToHttpHandler now handles its CompletableFutures more carefully.  null is no longer returned.  Instead values and exceptions are pushed back via the CompletableFutures value (or exceptionally prong).  I've also refactored the Request/Response packet arrays and friends into a helper HttpMessageAndTImestamp object to canonicalize the handling.  There's also a more formal state machine to track how data is accumulated.
There was also at least one bug within the JsonTuple writing code that was caused by headers that threw …
=> Replayer state model bugfixes

TrafficCapture/dockerSolution/src/main/docker/docker-compose.yml, TrafficCapture/nettyWireLogging/build.gradle, TrafficCapture/nettyWireLogging/src/main/java/org/opensearch/migrations/trafficcapture/netty/LoggingHttpRequestHandler.java, TrafficCapture/nettyWireLogging/src/main/java/org/opensearch/migrations/trafficcapture/netty/LoggingHttpResponseHandler.java, TrafficCapture/nettyWireLogging/src/test/java/org/opensearch/migrations/trafficcapture/netty/ConditionallyReliableLoggingHttpRequestHandlerTest.java, TrafficCapture/nettyWireLogging/src/test/java/org/opensearch/migrations/trafficcapture/netty/SimpleRequests.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/CloseableTrafficStreamWrapper.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/HttpMessageAndTimestamp.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/ReplayEngine.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/RequestResponsePacketPair.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/SourceTargetCaptureTuple.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/NettyPacketToHttpHandler.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NettyDecodedHttpRequestHandler.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NettySendByteBufsToPacketHandlerHandler.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/RequestPipelineOrchestrator.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/netty/BacksideHttpWatcherHandler.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/transform/JoltJsonTransformBuilder.java, TrafficCapture/trafficReplayer/src/main/resources/jolt/operations/addAdminAuth.jolt, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/HeaderTransformerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/TrafficReplayerTest.java
Make sure that a request or response that is fully contained within a single packet is fully processed.  The HttpDecoder was returning a list of multiple items in those cases and we need to iterate over all of them.
There were also further tweaks to the ReplayEngine state model to since there are now multiple EOM messages flowing for both requests and responses.
https://opensearch.atlassian.net/browse/MIGRATIONS-1115
Manual testing with docker compose …
=> Wire logging fixes for some response scenarios

TrafficCapture/dockerSolution/src/main/docker/docker-compose.yml, TrafficCapture/trafficCaptureProxyServer/build.gradle, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayer.java
Enable logging in the proxy server by striking slf4j jar files from the opensearch-security plugin zipfile from making it into the final build directory.  The proxy now exits after getting a parameter exception.  One of the command line args in the docker-compose config was off and it wasn't very noticeable - now it is...  and docker-compose has been updated too
No Jira
Manual testing
=> Minor fixes may24

TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/AggregatedRawResponse.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/PacketToTransformingProxyHandlerFactory.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/Utils.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/NettyPacketToHttpHandler.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/HttpJsonTransformer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NettyDecodedHttpRequestHandler.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NettyJsonBodyAccumulateHandler.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NettyJsonContentCompressor.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NettyJsonContentStreamToByteBufHandler.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NettyJsonToByteBufHandler.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NettySendByteBufsToPacketHandlerHandler.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NoContentException.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/RequestPipelineOrchestrator.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/AddCompressionEncodingTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/HeaderTransformerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/TestCapturePacketToHttpHandler.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/TestUtils.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/UtilsTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/datahandlers/http/HttpJsonTransformerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/transform/JsonTransformerTest.java
The HttpJsonTransformer builds up a netty pipeline on an EmbeddedChannel.  Early in the process (after NettyDecodedHttpRequestHandler receives the parsed header), it might be determined that the incoming HTTP message doesn't need any kind of transformation.  At that point, previously all of the subsequent handlers were removed and we attempted to just pass the raw packets directly through.
This was problematic for messages that had bodies in the same ByteBuf as headers.  That meant that some of the contents were being processed still by the previous handler, which hadn't yet fired them through the pipeline.  When the handler was removed, the extra parsed bytes/HttpContent/etc were dropped and we picked up on the last packet boundary NOT consumed by the handlers.
This code attempts to give …
=> Http json redrives

TrafficCapture/dockerSolution/README.md, TrafficCapture/dockerSolution/build.gradle, TrafficCapture/dockerSolution/src/main/docker/docker-compose.yml
I've left OpenSearchBenchmark commented out at the moment so that developers opt-in rather than opting out of it.
`./gradlew :dockerSolution:composeUp` brings up the entire stack, including the jupyter notebooks.
MIGRATIONS-1124
Manual testing
=> Integrate the traffic comparator and jupyter notebooks to the docker-compose solution

TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/PruferTreeGenerator.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/PruferTreeGeneratorTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/GenerateRandomNestedJsonObject.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/datahandlers/JsonAccumulatorTest.java
Category: New tests and new test infrastructure
This change includes the ability to generate a random json tree (object) and to use random trees to do some additional tests on the JsonAccumulator.  The random tree generation uses a Prufer sequence transformation to create a random sequence of integers and then maps that into a unique tree. There are a couple simple transformation layers placed on top of that to produce json w/ arrays and objects. This new functionality is used to drive the medium and large tests that the JsonAccumulator uses. All tests pass.
https://opensearch.atlassian.net/browse/MIGRATIONS-1142 
Additional unit tests were verified by hand
For more …
=> Add medium and large tests to the JsonAccumulator using the new random tree code

TrafficCapture/nettyWireLogging/src/main/java/org/opensearch/migrations/trafficcapture/netty/ConditionallyReliableLoggingHttpRequestHandler.java, TrafficCapture/nettyWireLogging/src/main/java/org/opensearch/migrations/trafficcapture/netty/LoggingHttpRequestHandler.java, TrafficCapture/nettyWireLogging/src/test/java/org/opensearch/migrations/trafficcapture/netty/ConditionallyReliableLoggingHttpRequestHandlerTest.java, TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/FrontsideHandler.java, TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/ProxyChannelInitializer.java, TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/InMemoryConnectionCaptureFactory.java, TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/NettyScanningHttpProxyTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/UtilsTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/datahandlers/JsonEmitterTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/datahandlers/http/ListKeyAdaptingCaseInsensitiveHeadersMapTest.java
* **_Category_**: Bug fix
* _**Why these changes are required**_?: To fix bugs when packet boundaries may be anywhere within an HTTP request.
* **_What is the old behavior before changes and new behavior after changes?_**: The TrafficStream recording would be incomplete and/or we would indefinitely hang on requests to ConditionallyReliableLoggingHttpRequestHandler that should have been stopped for the last bytes before flushing.  The old code would get confused and the state model would break.
This change replaces direct usage an HttpObjectDecoder for an HttpRequestDecoder.
ByteBufs are now passed through an EmbeddedChannel that has an HttpRequestDecoder (SImpleHttpRequestDecoder to be specific, which is a bit lighter on memory retention) followed by a SimpleDecodedHttpRequestHandler. …
=> MIGRATIONS-1080 - Stop directly using an HttpObjectDecoder

TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/NettyScanningHttpProxyTest.java
This PR consists of two commits.
[Test fix] The first one updates the `testRoundTrip` unit test to make the test pass more consistently. The current assertion checks for an exact byte size, which failed in some cases due to an off-by-one error (677 actual bytes versus 676 expected bytes). Rather than simply update the exact byte value, I've opted to make the check a little looser and incorporate a fudge factor of +/- 2 bytes.
[Refactoring] The second commit is a minor reformat of the file (via IntelliJ) for readability.
N/A
Unit test now consistently passes …
=> Make testRoundTrip assertion more reliable (and a little looser) 

TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/PruferTreeGeneratorTest.java
[Test fix] Prior to this change, `:trafficReplayer:spotbugsTest` was failing with SpotBugs complaining about a reliance on default character sets. Explicitly specifying the character set for the `PrintStream` object resolves this.
N/A
`:trafficReplayer:spotbugsTest` was failing before. Now it passes.
=> [Spotbugs] Explicitly specify character set for PrintStream object in unit test code

README.md, TrafficCapture/README.md
This PR adds a readme file to the TrafficCapture directory documenting how to run the solution and the compatibility of all the tools in that directory.
[Migrations-1126](https://opensearch.atlassian.net/browse/MIGRATIONS-1126
=> Migrations-1126 - Add documentation on compatibility and running one-click deployment locally

TrafficCapture/dockerSolution/src/main/docker/docker-compose.yml, TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/Main.java, TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/FrontsideHandler.java, TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/NettyScanningHttpProxy.java, TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/ProxyChannelInitializer.java, TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/NettyScanningHttpProxyTest.java
This change, similar to what has been done in the Traffic-Replayer [here](https://github.com/opensearch-project/opensearch-migrations/commit/7bb1eef8ea1f2a438f609e8aa1c03fb5c57ade2e#diff-b8c531f1b8f2cf3948ca4249f59868e7181dbc734e5a9f531b1ea32ae75f7641), allows the Logging Proxy to connect to a backside HTTPS server by creating an SslContext and allowing insecure connections if specified.
https://opensearch.atlassian.net/browse/MIGRATIONS-1105
Docker compose local testing
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certific …
=> Add Support for Proxy to connect to HTTPS Servers

.github/workflows/CI.yml, .github/workflows/gradle-build-and-test.yml, .github/workflows/gradle.yml, .github/workflows/python-tests.yml, TrafficCapture/build.gradle
This PR adds a github action for running `./gradlew build` and `./gradlew test` on the tools within the TrafficCapture directory. This will also add generating and uploading a coverage report for each tool (when applicable; has any tests)
This will also disable linting and pytest workflows for non-python directories.
[Migrations-1152](https://opensearch.atlassian.net/browse/MIGRATIONS-1152)
https://github.com/okhasawn/opensearch-migrations/actions/runs/5358402373/jobs/9720638919
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer- …
=> Github Workflow for Gradle Build and Test

TrafficCapture/kafkaPrinter/kafka.properties, TrafficCapture/kafkaPrinter/src/main/java/org/opensearch/migrations/KafkaPrinter.java
This PR achieves the following:
- Adds ability to specify a Kafka properties file for the Kafka Puller using the `--kafkaConfigFile` argument, while reverting to our default Kafka properties when no properties file is provided.
- Adds ability to enable certain required properties for the MSK IAM client using the `--enable-msk-client` argument.
[Migrations-1150](https://opensearch.atlassian.net/browse/MIGRATIONS-1150)
=> Migrations-1150 - Enhance Setting Kafka Properties for Kafka Puller

index_configuration_tool/index_operations.py, index_configuration_tool/main.py, index_configuration_tool/tests/test_main.py
This commit adds support for parsing the "insecure" flag from the Data Prepper YAML. This translates to a "verify" flag that is passed to the Python requests library. This commit also includes unit tests for this logic.
N/A
```
$ python -m coverage run -m unittest
.........................
----------------------------------------------------------------------
Ran 25 tests in 0.506s
OK
Name                  Stmts   Miss  Cover
-----------------------------------------
index_operations.py      29      2    93%
main.py                  88      0   100%
utils.py                 13      0   100%
-----------------------------------------
TOTAL                   130      2    98%
```
By submitting this pull request, I confirm …
=> [Index configuration tool] Add support for insecure HTTPS endpoint

index_configuration_tool/main.py, index_configuration_tool/tests/test_main.py
This change adds logic to read the "disable_authentication" key in the Data Prepper source and sink configuration. This flag was recently added to Data Prepper and removes the need to specify dummy username and password values in order to connect to an unauthenticated OpenSearch source/sink.
N/A
```
$ python -m coverage run -m unittest
..........................
----------------------------------------------------------------------
Ran 26 tests in 0.520s
OK
Name                  Stmts   Miss  Cover
-----------------------------------------
index_operations.py      37      2    95%
main.py                  92      0   100%
utils.py                 13      0   100%
-----------------------------------------
TOTAL …
```
=> [Index configuration tool] Support for disable_authentication key in Data Prepper YAML

index_configuration_tool/main.py, index_configuration_tool/tests/test_main.py
This change updates the validation logic to require both username and password unless the disable_auth key is present and set to True. If both username and password are missing, the tool now throws a ValueError.
N/A
```
$ python -m coverage run -m unittest
...........................
----------------------------------------------------------------------
Ran 27 tests in 0.031s
OK
Name                  Stmts   Miss  Cover
-----------------------------------------
index_operations.py      37      2    95%
main.py                  93      0   100%
utils.py                 13      0   100%
-----------------------------------------
TOTAL                   143      2    99%
```
By submitting this pull request, I confirm that my …
=> [Index configuration tool] Fix in validation logic for auth

TrafficCapture/captureKafkaOffloader/build.gradle, TrafficCapture/kafkaPrinter/build.gradle, deployment/cdk/opensearch-service-migration/README.md, deployment/cdk/opensearch-service-migration/lib/lambda/msk-public-endpoint-handler.ts, deployment/cdk/opensearch-service-migration/lib/migration-assistance-stack.ts, deployment/cdk/opensearch-service-migration/lib/msk-utility-stack.ts, deployment/cdk/opensearch-service-migration/lib/stack-composer.ts, deployment/cdk/opensearch-service-migration/package-lock.json, deployment/cdk/opensearch-service-migration/package.json, deployment/copilot/devDeploy.sh, deployment/copilot/environments/dev/manifest.yml
This change introduces the following features/enhancements:
**Allows enabling MSK public endpoints with CDK**
A current limitation of the MSK L1 construct is the absence to enable public broker endpoints. To handle this in CDK the next logical step would be to use a Custom Resource. Unfortunately, updating a cluster to have broker endpoints with a basic Custom Resource does not give us the desired result. If we simply make the SDK call to enable this we get a response immediately, however, the actual update can take over 20 minutes and users would be left in the dark. Alternatively simply using the Lambda that the CR creates to query the cluster continually and wait for completion also faces the issue of the maximum Lambda timeout being 15 minutes. The solution used here is loosely based …
=> Enhance IaC Deployments with MSK Public Endpoints and Dev Deployment Script

index_configuration_tool/main.py, index_configuration_tool/tests/test_main.py
The Index Configuration Tool has been updated to now produce a Data Prepper pipeline YAML file as an output. The tool now expects two positional arguments - the input pipeline YAML file like before, and an output path for the generated YAML file. The output YAML pipeline file is a modified version of the input that adds an index inclusion configuration for the sink, specifying only those indices that were created by the tool.
This change also adds two optional command line flags:
- "--report" prints a human-readable report to the command line in addition to generating an output YAML file
- "--dryrun" skips creation of indices on the target cluster
---
N/A
```
$ python -m coverage run -m unittest
.........................Wrote output YAML pipeline to: dummy
.... …
```
=> [Index Configuration Tool] Adds support for writing to an output YAML file

TrafficCapture/dockerSolution/src/main/docker/docker-compose.yml, TrafficCapture/dockerSolution/src/main/docker/openSearchBenchmark/Dockerfile, TrafficCapture/dockerSolution/src/main/docker/openSearchBenchmark/runTestBenchmarks.sh
Startup an OpenSearch Benchmark container, but put don't run tests up on startup.  Instead, put the tests into a shell script that can be invoked when the user wants to run it. That also lets the user run other tests too.
* **Category:** Enhancement, New feature, Refactoring
* **Why these changes are required?** Easier to control when a demo data load happens.  Also allows it to be run repeatedly, etc, etc.
* **What is the old behavior before changes and new behavior after changes?** The benchmark loaded with fixed tests, then the container completed.  Now, the container stays ready for a dev to run the tests when they're ready, however often they like, and with easier overrides.
No jira
Manual test.  To run - exec into the opensearch-benchmarks container and run `./runTestBenchmarks.sh ` …
=> Startup an OpenSearch Benchmark container, but put don't run tests up on startup

index_configuration_tool/Dockerfile
This change updates the Dockerfile definition for index_configuration_tool (ICT) to use Data Prepper as the base image. This will allow us to run (as a single Docker image) the index_configuration_tool Python logic to configure indices on the target cluster before kicking off Data Prepper execution to move data over. Note that since these steps must occur in sequence, the child Docker image overrides the parent's CMD definition and must manually invoke the data-prepper executable.
This is a POC implementation, so there are some limitations:
* The data migration pipeline does not shut down automatically once all data has been migrated. This is pending platform support in Data Prepper - https://github.com/opensearch-project/data-prepper/issues/2944
* If a `_bulk` call fails during data …
=> [Index Configuration Tool] Unified Dockerfile for ICT and Data Prepper

TrafficCapture/buildSrc/src/main/groovy/org.opensearch.migrations.java-common-conventions.gradle, TrafficCapture/settings.gradle, TrafficCapture/testUtilities/build.gradle, TrafficCapture/testUtilities/src/main/java/org/opensearch/migrations/testutils/PortFinder.java, TrafficCapture/testUtilities/src/main/java/org/opensearch/migrations/testutils/SimpleHttpClientForTesting.java, TrafficCapture/testUtilities/src/main/java/org/opensearch/migrations/testutils/SimpleHttpResponse.java, TrafficCapture/testUtilities/src/main/java/org/opensearch/migrations/testutils/SimpleHttpServer.java, TrafficCapture/trafficCaptureProxyServer/build.gradle, TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/NettyScanningHttpProxyTest.java, TrafficCapture/trafficReplayer/build.gradle, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/AggregatedRawResponse.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/NettyPacketToHttpConsumer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/netty/BacksideSnifferHandler.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/datahandlers/NettyPacketToHttpConsumerTest.java
The fix itself to NettyPacketToHttpConsumer is trivial.  I've spent more efforts on getting a unit test setup to be able to do more live testing with TLS. I've intentionally used client and server implementations different from netty since the real world will have clients that aren't just netty.
* **Category**: Bug fix
* **Why these changes are required**?  We were capturing encrypted responses rather than plaintext ones, making it impossible to compare them or reason with them in any way.
* **What is the old behavior before changes and new behavior after changes?** 
- Before: all response packets were encrypted when the target server was using TLS
- Now: response pieces are first decrypted before being added to the packet responess.
MIGRATIONS-1268
Is this a backport? If so, please add …
=> Fix MIGRATIONS-1268 (capturing encrypted, rather than plaintext data)

TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/Accumulation.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/CapturedTrafficToHttpTransactionAccumulator.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/traffic/expiration/ExpiringTrafficStreamMap.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/util/OnlineRadixSorter.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/util/OnlineRadixSorterForIntegratedKeys.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/ExpiringTrafficStreamMapSequentialTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/ExpiringTrafficStreamMapUnorderedTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/TrafficReplayerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/util/OnlineRadixSorterTest.java
* **Category** Enhancement / Bug fix
* **Why these changes are required**? The capture proxy makes no guarantee that the Kafka Records containing TrafficStream objects will be sequenced correctly.
* **What is the old behavior before changes and new behavior after changes**?  Misordered TrafficStream objects would cause undefined behavior.  Now the system should be resilient to TrafficStream objects being reordered.
From the commit message:
Introduce a new class (OnlineRadixSorter) that takes a sequence of indexed objects and then visits the current contiguous monotonic sequence from the first item that had yet to be visited.  The javadoc has examples.  This is used because the TrafficStream sequences may arrive in the observed order.  
The CapturedTrafficToHttpTransactionAccumulator now …
=> Fix misordered traffic streams

TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/KafkaPrinter.java, deployment/cdk/opensearch-service-migration/bin/app.ts, deployment/cdk/opensearch-service-migration/lib/migration-assistance-stack.ts, deployment/cdk/opensearch-service-migration/lib/msk-utility-stack.ts, deployment/cdk/opensearch-service-migration/lib/network-stack.ts, deployment/cdk/opensearch-service-migration/lib/stack-composer.ts, deployment/cdk/opensearch-service-migration/test/domain-cdk-stack.test.ts, deployment/cdk/opensearch-service-migration/test/network-stack.test.ts, deployment/cdk/opensearch-service-migration/test/stack-composer.test.ts, deployment/cdk/opensearch-service-migration/test/test-utils.ts, deployment/copilot/README.md, deployment/copilot/capture-proxy/addons/taskRole.yml, deployment/copilot/devDeploy.sh, deployment/copilot/opensearch-benchmark/manifest.yml, deployment/copilot/traffic-replayer/addons/taskRole.yml, deployment/copilot/traffic-replayer/manifest.yml
This PR accomplishes a few different smaller tasks. These include:
* Fixing bug preventing devDeploy script from deploying to multiple regions
* Allowing additional options to devDeploy script for more flexibility i.e. region and stage
* Adding concurrency option to cdk deploy to speed up its stack deployment
* Tightening IAM permissions across the board
https://opensearch.atlassian.net/browse/MIGRATIONS-1205
Manual testing in progress to verify IaC has basic functionality and experimenting with tightening Custom Resource IAM actions …
=> Enhance devDeploy script and tighten down IAM polices and Security Groups

FetchMigration/index_configuration_tool/endpoint_info.py, FetchMigration/index_configuration_tool/index_operations.py, FetchMigration/index_configuration_tool/main.py, FetchMigration/index_configuration_tool/tests/test_index_operations.py, FetchMigration/index_configuration_tool/tests/test_main.py
This change allows the Index Configuration Tool report to print the total number of documents that will be migrated, based on the indices identified for creation. The change includes a new API call under `index_operations.py` and updated unit tests. 
This PR also includes some other minor changes:
1. The output YAML file is now optional, allowing users to print a report without producing a YAML file. However, one of `--report` or an output YAML file path are required - omitting both will result in a `ValueError`
2. A new `EndpointInfo` [dataclass](https://docs.python.org/3/library/dataclasses.html) has been introduced to encapsulate endpoint information (URL, auth and SSL verification flag) for source and target
3. The default output of the tool has been changed to …
=> [Fetch Migration] Added total document count to report

TrafficCapture/trafficReplayer/build.gradle, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/AWSAuthService.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayer.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/AWSAuthServiceTest.java, deployment/cdk/opensearch-service-migration/lib/opensearch-service-domain-cdk-stack.ts, deployment/copilot/README.md, deployment/copilot/devDeploy.sh, deployment/copilot/traffic-replayer/addons/taskRole.yml, deployment/copilot/traffic-replayer/manifest.yml
This change adds two arguments to the Replayer to add support for adding an auth header from an AWS SecretsManager secret and users `--aws-auth-header-user admin --aws-auth-header-secret arn:123`
In the near future it is expected this structure will change as the Replayer is enhanced to support different users and providing a single user auth probably won't make sense. In the meantime this gives a structure to use a secret and construct an auth header with it for replayed requests. Another detail that presented itself is that the Jolt transformation library doesn't seem to easily support dynamic value transformations (i.e. we would want to access our SecretCache regularly and have it occasionally make requests to SecretsManager to get updated secrets). For now we are only fetching the …
=> Add option to use AWS secret in auth header for Replayer requests

TrafficCapture/README.md, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/runTestBenchmarks.sh
The current version of `runTestBenchmarks` has values in place that work for docker, but not for copilot, and the format of the script makes it challenging to update values quickly.
This version checks for a `COPILOT_SERVICE_NAME` env var. If it's present, it assumes we're in copilot and switches the default endpoint to the copilot-friendly one.
If the user is using a different endpoint or auth params (or no auth) on the source cluster, they can use a CL param to adjust those values. E.g.:
```
./runTestBenchmarks.sh --endpoint https://mycustomendpoint.com:9201 --auth_user admin123 --auth_pass admin123!
```
or
```
./runTestBenchmarks.sh --no_auth
```
not created yet
Manual testing. Documentation needs to be added!!
By submitting this pull request, I confirm that my contribution is made …
=> Update `runTestBenchmarks.sh` script with params and defaults for copilot vs docker

TrafficCapture/README.md, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/Dockerfile, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/humanReadableLogs.py
This adds a new feature as a follow up to #266 and #258 .
Those two PRs created a new EFS/shared volume attached to the replayer and migration console, and directed the replayer's output tuples to that volume.
The Replayer outputs base64 encoded message bodies in the tuples: this prevents issues where saving a gzipped message body in utf-8 in a json was corrupting them.
This PR adds a python script to the migration console that allows the user to specify a file of replayer-generated tuple logs. It loads each log line, extracts the tuple, and processes it:
- the message bodies are base64 decoded
- if the headers (Content-Encoding) indicate that the message is gzipped, it's unzipped
- if the headers (Content-Type) indicate that the …
=> Add script to transform tuples to human readable format

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/Dockerfile, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/runTestBenchmarks.sh
Small changes for the MIgration Console on the release branch.
1. Is re-adding the pip versioning locks that were added & explained [here](https://github.com/opensearch-project/opensearch-migrations/pull/274/files/928e55cae490ba84f5857b2a6a97f6ea600773bc#r1299298323). This breaks both `runTestBenchmarks` and `humanReadableLogs`
2. Remove geonames from the list opensearch-benchmark workloads that are run. Right now, we have an issue in the capture proxy/replayer that reacts particularly poorly to this dataset. After getting halfway through, there are one or more "poisonous" messages that break the replayer and make it difficult to revive, even with restarting. We're working on the real fix for this, but as a stopgap, this modifies `runTestBenchmarks` so that this workload isn't run …
=> Migration Console small bugfixes

TrafficCapture/testUtilities/src/main/java/org/opensearch/migrations/testutils/SimpleHttpClientForTesting.java, TrafficCapture/trafficReplayer/build.gradle, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/SigV4Signer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/Utils.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/transform/SigV4ExcisionJsonTransformer.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/SigV4SignerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/transform/SigV4AuthExcisionTest.java, TrafficCapture/trafficReplayer/src/test/resources/sampleJsonDocuments/sigV4/signed_request_input.txt, TrafficCapture/trafficReplayer/src/test/resources/sampleJsonDocuments/sigV4/signed_request_output.txt, TrafficCapture/trafficReplayer/src/test/resources/sampleJsonDocuments/sigV4/unsigned_request.txt
This PR copies what PR #257 (by @mikaylathompson ) does + adds the SigV4 signer class (Not yet used).
"
A task to add SigV4 signing to the replayer is underway.
In the meantime, testing against a cluster that does not require SigV4 revealed that if the original clients are signing the requests, the signature-related headers will be passed along to the target cluster. This signature will almost certainly fail to be validated because it includes the `Host` header, which we modify.
This PR, as a pre-req, to full SigV4 signing, simply strips out the signature-related headers: `Authorization` and `X-Amz-Security-Token`.
"
TODO: Enable SigV4 support
Copied from PR #257
Unit tests are included.
Additionally, evidence is available from deploying this in-situ for WhiteFir.
Pre-deployment, 100% of …
=> Copy of Sigv4excision (PR #257), and add SigV4Signer (Not yet used)

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/humanReadableLogs.py
We encountered several issues when running the humanReadableLogs on AWS:
1. It crashed on some gzipped messages. While it caught the error successfully, it output the in-progress byte string, and when that was written to JSON, JSON has no byte string type and it crashed.
2. When that was fixed, it became clear that the gzipped messages it was failing to unzip were both gzipped and had a "chunked" transfer encoding. This meant that they were split into several segments, with the length of those segments also written in, and generally were no longer gzip-compatible. By parsing through this data to extract the chunks, a continuous byte stream can be extracted, and that one is un-gzippable.
This also turned up an issue (hinted at in the …
=> Handle Chunked Transfer-Encoding for humanReadableLogs

TrafficCapture/trafficReplayer/README.md, deployment/cdk/opensearch-service-migration/lib/opensearch-service-domain-cdk-stack.ts, deployment/copilot/README.md, deployment/copilot/devDeploy.sh
Adjust devDeploy.sh with recent Replayer auth changes. Also remove additional "orchestration" logic from devDeploy surrounding setting the auth header, which will be taxing to keep up to date and probably doesn't belong there.
None
Manual deployment testing
=> Sync devDeploy with recent Replayer auth changes

TrafficCapture/trafficReplayer/README.md, deployment/cdk/opensearch-service-migration/lib/opensearch-service-domain-cdk-stack.ts, deployment/copilot/README.md, deployment/copilot/devDeploy.sh
Change has been verified with devDeploy to AWS
* Sync devDeploy with recent Replayer auth changes
Signed-off-by: Tanner Lewis <lewijacn@amazon.com>
(cherry picked from commit 4165dc48496deb0670d370d7c478fabc69b5c702)
For more information …
=> Backport: Sync devDeploy with recent Replayer auth changes (#279)

TrafficCapture/captureOffloader/src/main/java/org/opensearch/migrations/trafficcapture/CodedOutputStreamSizeUtil.java, TrafficCapture/captureOffloader/src/main/java/org/opensearch/migrations/trafficcapture/StreamChannelConnectionCaptureSerializer.java, TrafficCapture/captureOffloader/src/test/java/org/opensearch/migrations/trafficcapture/StreamChannelConnectionCaptureSerializerTest.java
This change primarily ensures that every observation we attempt to add to a TrafficStream performs a space check of the CodedOuputStream initially to ensure that there is ample space to store the observation and a closing index, or otherwise flush the stream so that space is available.
Beyond this, there is also some cleaning up of EndOfSegmentIndication size calculations as this will now be handled by the observation size check. As well as general naming and structuring to make things a bit cleaner and easier to follow.
https://opensearch.atlassian.net/browse/MIGRATIONS-1294
Unit testing and manual docker testing …
=> MIGRATIONS-1294: Improve remaining space checks for Capture Proxy

TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/ExpiringSubstitutableItemPoolTest.java, TrafficCapture/trafficReplayer/build.gradle, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/AWSAuthService.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayer.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/AWSAuthServiceTest.java
This reworks the SecretCache to be a SecretsManager async client that retrieves the secret. This will be helpful in the future as needed with integrating with Netty, for now it has a synchronous method for constructing an auth header from a secret.
None
Unit tests
=> Refactor secrets cache to sdk client

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/humanReadableLogs.py, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/SourceTargetCaptureTuple.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NettyJsonToByteBufHandler.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/HeaderTransformerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/TestUtils.java
This PR includes three (related) categories of changes:
1. It outputs the request that was replayed against the target cluster and the connection ID in the tuples that are logged as output.
2. It updates our terminology in the tuples & surrounding areas from primary/shadow to source/target, which matches what we're using in the rest of our code & documentation.
3. The NettyJsonToByteBufHandler was using line feeds (`\n`) when formatting HTTP messages, but [the spec is to use carriage return line feeds](https://www.ibm.com/docs/en/cics-ts/6.1?topic=protocol-http-requests#dfhtl21__title__3) (`\r\n`). This turned out to cause an issue in how we were parsing the HTTP message for the JSON, so rather than build in a workaround, I updated the …
=> Use CRLF in NettyJsonToByteBufHandler

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/humanReadableLogs.py, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/SourceTargetCaptureTuple.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NettyJsonToByteBufHandler.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/HeaderTransformerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/TestUtils.java
=> Backport #283 to capture-and-replay-v0.1.0

FetchMigration/index_configuration_tool/monitor.py, FetchMigration/index_configuration_tool/requirements.txt, FetchMigration/index_configuration_tool/tests/test_monitor.py
This change adds a `monitor.py` Python script that can monitor the running Data Prepper pipeline and shut it down once the target document count has been reached (as reported by Data Prepper's `documentsSuccess` Prometheus metric) and an idle pipeline is detected.
* Category: New feature
---
```
Name                  Stmts   Miss  Cover
-----------------------------------------
endpoint_info.py          6      0   100%
index_operations.py      35      0   100%
main.py                 121      1    99%
monitor.py               52      0   100%
utils.py                 13      0   100%
-----------------------------------------
TOTAL                   227      1    99%
```
1. Setup step (see the Index Configuration Tool …
=> [Fetch Migration] Monitoring script for Data Prepper

TrafficCapture/buildSrc/src/main/groovy/org/opensearch/migrations/common/CommonUtils.groovy, TrafficCapture/testUtilities/build.gradle, TrafficCapture/trafficReplayer/build.gradle
This PR brings one more critical mend fix.
Also adjusts the version comparison function and moves it to the common utilities build.gradle file since it's now needed in more than one file. (Addressing feedback gotten from @lewijacn here: `https://github.com/opensearch-project/opensearch-migrations/pull/293#discussion_r1316582995`)
=> Adjusting logic for version comparison + fix CVE-42920

.gitignore, TrafficCapture/dockerSolution/src/main/docker/docker-compose.yml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/Dockerfile, TrafficCapture/trafficReplayer/src/main/resources/log4j2.properties, deployment/cdk/opensearch-service-migration/README.md, deployment/cdk/opensearch-service-migration/default-values.json, deployment/cdk/opensearch-service-migration/lib/migration-assistance-stack.ts, deployment/cdk/opensearch-service-migration/lib/opensearch-service-domain-cdk-stack.ts, deployment/cdk/opensearch-service-migration/lib/stack-composer.ts, deployment/copilot/createReplayer.sh, deployment/copilot/devDeploy.sh, deployment/copilot/templates/traffic-replayer/manifest.yml
This includes several minor improvements to our IaC story for deploying multiple replayers that I have come across while deploying and testing our solution.
One additional point I want to make is that setting our log4j2.properties for the tuple directory at program startup before logging gets initialized was more involved than I originally thought. I am still open to going that direction but didn't want to get hung up here. This instead uses an env variable that seems to work well for the near term
None
E2E Cloud Testing …
=> Add set of minor improvements to our IaC and Replayer story

TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/SigV4SigningTransformationTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/TestUtils.java
Reran the unit test with example creds and it works as expected.
=> Use an example keypair (with the string "EXAMPLE" rather than a fabricated one) to satisfy scanners.

experimental/cluster_migration_core/setup.py
Testing if this fixes CVE-2022-42969.
I tested running the UTF again without the `py` library and also upgrading `pytest` to latest, and it worked as it previously was.
This is the reason I updated `pytest` to 7.4.2: https://github.com/advisories/GHSA-w596-4wvx-j9j6
=> Fix for CVE-2022-42969

TrafficCapture/coreUtilities/build.gradle, TrafficCapture/dockerSolution/build.gradle, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/Dockerfile, TrafficCapture/testUtilities/build.gradle, TrafficCapture/trafficReplayer/src/main/resources/log4j2.properties
By default, this is currently on, though the block could be commented out to disable that logging.  Personally, I find having logs console logging to be a major impediment. I've also commented out checkstyle or findbugs since they are respectively too verbose and don't work.
* Category Enhancements
* Why these changes are required? To make debugging and building better.
* What is the old behavior before changes and new behavior after changes?  No durable logs for docker or the replayer/migration console and lots of useless spew in the builds.  Now it's better.
No Issue
Manual testing.
For more information on …
=> Add time based file output that rotates and compresses every hour for up to 72 hours.

TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/ExpiringSubstitutableItemPool.java, TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/ExpiringSubstitutableItemPoolTest.java
* Category Bug fix/Test fix
* Why these changes are required? Fix a test
* What is the old behavior before changes and new behavior after changes? getStats() objects returned by the Expiring Pool will be immutable, but will be up-to-date and consistent at the time that getStats() was called.
The stats that were returned by the Lombok @Getter annotation weren't thread-safe.  The Pool itself isn't threadsafe.  The expectation is that all of the calls will be conducted on the event loop that the object is bound to.  Stats are also updated from that same event loop thread and the stats are implemented with plain old non-concurrent primitives and objects. The unit test, however, queried the stats object after various calls were made and got the same stats object that may have previously been …
=> Fixing at least one cause of test failures in ExpiringSubstitutableItemPool

TrafficCapture/captureKafkaOffloader/src/main/java/org/opensearch/migrations/trafficcapture/kafkaoffloader/KafkaCaptureFactory.java, TrafficCapture/coreUtilities/src/main/java/org/opensearch/migrations/coreutils/MetricsLogger.java, TrafficCapture/trafficReplayer/build.gradle, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/CapturedTrafficToHttpTransactionAccumulator.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/PacketToTransformingHttpHandlerFactory.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/ReplayEngine.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/RequestSenderOrchestrator.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/NettyPacketToHttpConsumer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/HttpJsonTransformingConsumer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NettyDecodedHttpRequestPreliminaryConvertHandler.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/RequestPipelineOrchestrator.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/kafka/KafkaProtobufConsumer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/netty/BacksideHttpWatcherHandler.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/netty/BacksideSnifferHandler.java, TrafficCapture/trafficReplayer/src/main/resources/log4j2.properties, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/AddCompressionEncodingTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/HeaderTransformerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/TestUtils.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/datahandlers/NettyPacketToHttpConsumerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/datahandlers/http/HttpJsonTransformingConsumerTest.java
Based on PR #297, which establishes a MetricsLogger convention and inserts metrics logging in various places in the capture proxy, this PR inserts metric logging in the Replayer.
In a fully successful replay of a given request, the events seen, with their contextual information are:
- Parsed traffic stream from Kafka (connectionId, sizeInBytes, topic name)
- Full captured source request was accumulated (requestId)
- Full captured source response was accumulated (requestId)
- Captured request parsed to HTTP (requestId, httpEndpoint, httpMethod)
- Request was transformed (channelId, requestId)
- Request scheduled to be sent (requestId, delayFromOriginalToScheduledStartInMs, scheduledStartTime)
- Request packet written to target (requestId, size, channelId)
- Component of response received …
=> Add MetricsLogger to Traffic Replayer

TrafficCapture/nettyWireLogging/build.gradle, TrafficCapture/nettyWireLogging/src/main/java/org/opensearch/migrations/trafficcapture/netty/ConditionallyReliableLoggingHttpRequestHandler.java, TrafficCapture/nettyWireLogging/src/main/java/org/opensearch/migrations/trafficcapture/netty/LoggingHttpRequestHandler.java, TrafficCapture/nettyWireLogging/src/test/java/org/opensearch/migrations/trafficcapture/netty/ConditionallyReliableLoggingHttpRequestHandlerTest.java, TrafficCapture/nettyWireLogging/src/test/resources/log4j2.properties, TrafficCapture/testUtilities/src/main/java/org/opensearch/migrations/testutils/CountingNettyResourceLeakDetector.java, TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/FrontsideHandler.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayer.java
Fixes two bugs in the NettyWireLogging, which the CaptureProxyServer uses.  This should make the memory consumption of the capture proxy more stable.  
* Category Bug fix
* Why these changes are required? So that the proxy can run for longer without running out of memory
* What is the old behavior before changes and new behavior after changes? Now it doesn't leak memory as fast
https://github.com/opensearch-project/opensearch-migrations/pull/316
TODO: Is this a backport? If so, please add backport PR # and/or commits #
Unit tests.
Plus, I’ve been running it for about 30 minutes (looping the 4 test cases from OpenSearch Benchmark) with PARANOID leak awareness.  I’m seeing a pretty stable 260 MB of Resident Memory usage in the docker solution.
By submitting this pull request, I confirm that …
=> Fix memory leaks in NettyWireLogging and improve leak tracking abilities in tests

deployment/copilot/README.md, deployment/copilot/devDeploy.sh
None
Manual deployment testing
=> Minor tag bug fix and README update for devDeploy

TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/ListKeyAdaptingCaseInsensitiveHeadersMap.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NettyDecodedHttpRequestPreliminaryConvertHandler.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/datahandlers/http/HttpJsonTransformingConsumerTest.java, TrafficCapture/trafficReplayer/src/test/resources/requests/raw/get_withAuthHeader.txt
First, wire up the remove method for the wrapper (list adapting) map of the case insensitive map implementation so that remove() is actually called on the underlying map, rather than calling an UnsupportedOperationException.  The second issue was that the original request headers and the newly transformed headers were deemed to be identical, even though an item was missing within the transformed map.  We only iterated through the transformed map and we didn't make sure that we were going to hit all of the elements.  Now we check that the lengths are the same too.
* Category Bug fix
* Why these changes are required? to make --remove-auth-header work
* What is the old behavior before changes and new behavior after changes? --remove-auth-header should now remove any authorization header in …
=> Two bugfixes to facilitate "--remove-auth-headers" (MIGRATIONS-1309).

deployment/cdk/opensearch-service-migration/README.md, deployment/copilot/devDeploy.sh
This PR updates the order of prerequisites for using CDK and deployment of the project.
Also fixes a possible error when running the `devDeploy` script, and now uses the provided app name if the `--destroy-all-copilot` flag is used.
[Migrations-1318](https://opensearch.atlassian.net/browse/MIGRATIONS-1318)
=> Update CDK documentation + minor changes to devDeploy script

.github/workflows/release-drafter.yml, README.md, jenkins/release.jenkinsFile
On board 1-click release for OpenSearch Migrations
Part of: https://github.com/opensearch-project/opensearch-build/issues/4085
=> On board 1-click release for OpenSearch Migrations

TrafficCapture/coreUtilities/build.gradle, TrafficCapture/coreUtilities/src/main/java/org/opensearch/migrations/trafficcapture/protos/TrafficStreamUtils.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/BlockingTrafficSource.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/CapturedTrafficToHttpTransactionAccumulator.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/ClientConnectionPool.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/InputStreamOfTraffic.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/ReplayEngine.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TimeShifter.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/HttpJsonTransformingConsumer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/traffic/expiration/BehavioralPolicy.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/traffic/expiration/ExpiringTrafficStreamMap.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/BlockingTrafficSourceTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/RequestSenderOrchestratorTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/TestHttpServerContext.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/TimeShifterTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/TrafficReplayerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/datahandlers/NettyPacketToHttpConsumerTest.java
This code fixes a major bug that was triggered when a TrafficStream's first set of records was missing its first (0) index.  That caused the BlockingTrafficSource to wait for the first TrafficStream to complete, but it never would.  How we manage bumping time at the beginning of the application has been significantly rethought.  We should still test that expirations are carrying through to bump all of the other cases.
The logging messages for when the expiration timeout window weren't big enough weren't helpful.  I've reworked those to provide the correct values and to provide stronger guidance to the user.
Other refactoring in a number of spots to try to improve out logging stories, including making the coreUtilities project dependent upon the captureProtobuf project so that it can add …
=> Fix some bugs and improve some log messages.

TrafficCapture/dockerSolution/src/main/docker/docker-compose.yml, TrafficCapture/trafficCaptureProxyServer/build.gradle, TrafficCapture/trafficCaptureProxyServerTest/src/main/docker/docker-compose.yml, deployment/copilot/capture-proxy-es/manifest.yml, deployment/copilot/capture-proxy/manifest.yml
The capture proxy class name was change recently, this PR will fix the instances where the classpath for the Capture Proxy was used.
=> Fix classpath for capture proxy after renaming

TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/kafka/KafkaProtobufConsumer.java
This is a bug fix to add back in a simple kafka commit until we have logic in place to commit in a more reliable manner
=> Fix missing kafka commit

test/tests.py
This PR adds a test to the E2E script that sends unauthorized credentials to the clusters.
This ensures the security of the authentication process and validates that unauthorized access is prevented.
[MIGRATIONS-1153](https://opensearch.atlassian.net/browse/MIGRATIONS-1153)
=> Add negative authorization test to E2E script

test/tests.py
This PR adds a test to the E2E script that uses invalid and incorrect URIs. This PR is built on #362.
[MIGRATIONS-1153](https://opensearch.atlassian.net/browse/MIGRATIONS-1153)
=> Add invalid and incorrect URI tests to E2E script

TrafficCapture/dockerSolution/src/main/docker/docker-compose-single.yml
Quick fix for renamed capture proxy when combined with ES in the same container.
=> Fix classpath for Capture Proxy

TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/Accumulation.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/AccumulationCallbacks.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/CapturedTrafficToHttpTransactionAccumulator.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/ClientConnectionPool.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/PacketConsumerFactory.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/PacketToTransformingHttpHandlerFactory.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/ReplayEngine.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/RequestResponsePacketPair.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/RequestSenderOrchestrator.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/SourceTargetCaptureTuple.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/NettyPacketToHttpConsumer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/HttpJsonTransformingConsumer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NettyDecodedHttpRequestPreliminaryConvertHandler.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/RequestPipelineOrchestrator.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datatypes/ConnectionReplaySession.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datatypes/UniqueReplayerRequestKey.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datatypes/UniqueRequestKey.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datatypes/UniqueSourceRequestKey.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/traffic/source/ISimpleTrafficCaptureSource.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/traffic/source/ITrafficCaptureSource.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/ExhaustiveCapturedTrafficToHttpTransactionAccumulatorTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/ExpiringTrafficStreamMapSequentialTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/ExpiringTrafficStreamMapUnorderedTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/FullTrafficReplayerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/SimpleCapturedTrafficToHttpTransactionAccumulatorTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/TestRequestKey.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/TrafficReplayerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/TrafficStreamGenerator.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/datahandlers/NettyPacketToHttpConsumerTest.java
From the commit message:
Continue work on making the replayer more reliable to the point where each TrafficStream is being committed after it's been fully processed.
Along the way, partially to build up the tools for testing that behavior, partially because other bugs were discovered along the way, a number of bugfixes, enhancements, and refactorings continue to pile up.
Accumulations now track the TrafficKey instead of the RequestResponsePair. There are moments (since the past couple commits) where the rrPair field may be null and we might not have access to the trafficStreamKey. This change was made a bit easier since I've also refactored the CapturedTrafficToHttpTransactionAccumulator to take in a help object of callbacks rather than 3 callbacks. It's actually now 4 callbacks because …
=> Bugfixes and better shutdowns

TrafficCapture/dockerSolution/src/main/docker/docker-compose-multi.yml
This PR restores the ability to create a setup that has 2 coordinator nodes with a Capture Proxy on each node.
This is needed after a change to the Dockerfile that creates the ES image was made, along with renaming the Capture Proxy.
=> Fixing Multi-Proxy build

TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/CaptureProxy.java, TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/ExpiringSubstitutableItemPoolTest.java, TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/NettyScanningHttpProxyTest.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/traffic/source/BlockingTrafficSource.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/traffic/source/TrafficStreamLimiter.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/TestCapturePacketToHttpHandler.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/TestHttpServerContext.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/TrafficReplayerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/util/StringTrackableCompletableFutureTest.java
Fix lint issues around IntteruptedExceptions.  See SonarQube rule: S2142.
=> Linting Round 2 - Flip the interrupt status back on in many places where InterruptedExceptions are handled

TrafficCapture/testUtilities/src/testFixtures/java/org/opensearch/migrations/testutils/PortFinder.java, TrafficCapture/testUtilities/src/testFixtures/java/org/opensearch/migrations/testutils/SimpleHttpServer.java, TrafficCapture/testUtilities/src/testFixtures/java/org/opensearch/migrations/testutils/SimpleNettyHttpServer.java, TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/CaptureProxy.java, TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/ExpiringSubstitutableItemPoolTest.java, TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/NettyScanningHttpProxyTest.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/HttpMessageAndTimestamp.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/PrettyPrinter.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/PayloadAccessFaultingMap.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/TransformedPacketReceiver.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/HttpJsonMessageWithFaultingPayload.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/HttpJsonTransformingConsumer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/ListKeyAdaptingCaseInsensitiveHeadersMap.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NettyDecodedHttpRequestPreliminaryConvertHandler.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NettyJsonBodySerializeHandler.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NettyJsonContentCompressor.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NettyJsonContentStreamToByteBufHandler.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NettyJsonToByteBufHandler.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NettySendByteBufsToPacketHandlerHandler.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/RequestPipelineOrchestrator.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/StrictCaseInsensitiveHttpHeadersMap.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/traffic/source/BlockingTrafficSource.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/traffic/source/TrafficStreamLimiter.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/transform/IAuthTransformerFactory.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/TestCapturePacketToHttpHandler.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/TestHttpServerContext.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/TrafficReplayerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/util/StringTrackableCompletableFutureTest.java
More improvements to fix issues caught in running a lint checker.
./gradlew allTests
=> Linting round3

TrafficCapture/testUtilities/src/testFixtures/java/org/opensearch/migrations/testutils/CountingNettyResourceLeakDetector.java, TrafficCapture/testUtilities/src/testFixtures/java/org/opensearch/migrations/testutils/HeapDumper.java, TrafficCapture/testUtilities/src/testFixtures/java/org/opensearch/migrations/testutils/NettyLeakCheckTestExtension.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/SourceTargetCaptureTuple.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayer.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/FullTrafficReplayerTest.java
=> Linting round6

FetchMigration/python/fetch_orchestrator.py, FetchMigration/python/metadata_migration.py, FetchMigration/python/migration_monitor.py, FetchMigration/python/migration_monitor_params.py, FetchMigration/python/progress_metrics.py, FetchMigration/python/tests/test_fetch_orchestrator.py, FetchMigration/python/tests/test_migration_monitor.py, FetchMigration/python/tests/test_progress_metrics.py
This commit introduces changes to track various Data Prepper metrics (as well as API failure counters) in order to detect an idle pipeline or non-responsive Data Prepper subprocess. A new `ProgressMetrics` class has been added to track these metrics and encapsulate detection logic. Much of the migration-success logic from the monitoring module has been moved to this class now. Unit test updates and improvements are also included.
This PR also includes a second commit which refactors/merges the `run` and `monitor_local` functions together (since most of their code/logic is identical) for improved unit test coverage.
* Category
* Enhancement, bug fix, Refactoring
* Without these logic changes, the monitoring module would _only_ shutdown the Data Prepper …
=> [Fetch Migration] Handle idle pipeline when target doc count is never reached

deployment/cdk/opensearch-service-migration/bin/app.ts, deployment/cdk/opensearch-service-migration/buildDockerImages.sh, deployment/cdk/opensearch-service-migration/lib/stack-composer.ts, deployment/cdk/opensearch-service-migration/package-lock.json, deployment/cdk/opensearch-service-migration/package.json
This is a small change to allow an existing AppRegistry application to be imported into our CDK, such that all stacks that get created are associated with the AppRegistry application. It is an optional setting this is enabled through the MIGRATIONS_APP_REGISTRY_ARN environment variable. 
https://opensearch.atlassian.net/browse/MIGRATIONS-1411
Manual deployment testing
=> Allow Existing App Registry for CDK

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/Dockerfile
Changed the version of kafka on the Kafka Docker image to match the version we are updating to after applying this security fix:
https://github.com/opensearch-project/opensearch-migrations/pull/340
https://github.com/opensearch-project/opensearch-migrations/pull/340
=> Bump Kafka version on Docker

FetchMigration/Dockerfile, FetchMigration/python/fetch_orchestrator.py, FetchMigration/python/fetch_orchestrator_params.py, FetchMigration/python/tests/resources/test_pipeline_input.yaml, FetchMigration/python/tests/test_fetch_orchestrator.py, FetchMigration/python/tests/test_fetch_orchestrator_params.py, deployment/cdk/opensearch-service-migration/lib/fetch-migration-stack.ts
This PR includes a few changes:
1 - Fetch Migration now supports supplying the target cluster endpoint via environment variable (`INLINE_TARGET_HOST`) similar to `INLINE_PIPELINE` behavior. If present, the value of this env variable is written as the hostname for the Data Prepper sink in the Data Prepper pipeline configuration file _before_ kicking off any steps in the Fetch Migration workflow.
2 - The CDK has been changed to utilize the above environment variable. This mitigates the [bug described here](https://github.com/opensearch-project/opensearch-migrations/pull/387)
3 - `fetch_orchestrator` has been updated to assume a local Data Prepper process, so it no longer accepts a Data Prepper "endpoint" URL but constructs this based on input parameters (port value and SSL flag). This …
=> [Fetch Migration] Support for dynamic target host substitution via environment variable, and fetch_orchestrator updates

FetchMigration/python/endpoint_info.py, FetchMigration/python/endpoint_utils.py, FetchMigration/python/tests/test_index_operations.py
This change swaps out the use of the `|` operator for `typing.Union` since `|` is only available in Python 3.10+ . Hence, `typing.Union` provides broader compatibility. Also included in this change is a name correction for the index_operations unit test class.
* Category:  Bug fix
```
Name                           Stmts   Miss  Cover
--------------------------------------------------
endpoint_info.py                  24      1    96%
endpoint_utils.py                107      1    99%
fetch_orchestrator.py             70      0   100%
fetch_orchestrator_params.py      22      0   100%
index_operations.py               38      0   100%
metadata_migration.py             62      0   100%
metadata_migration_params.py       7      0   100% …
```
=> Bugfix - Use typing.Union in Fetch Migration rather than "|" operator

FetchMigration/python/fetch_orchestrator.py, FetchMigration/python/index_diff.py, FetchMigration/python/index_doc_count.py, FetchMigration/python/index_operations.py, FetchMigration/python/metadata_migration.py, FetchMigration/python/metadata_migration_result.py, FetchMigration/python/migration_monitor.py, FetchMigration/python/requirements.txt, FetchMigration/python/tests/test_endpoint_utils.py, FetchMigration/python/tests/test_fetch_orchestrator.py, FetchMigration/python/tests/test_index_diff.py, FetchMigration/python/tests/test_index_operations.py, FetchMigration/python/tests/test_metadata_migration.py, deployment/cdk/opensearch-service-migration/dp_pipeline_template.yaml, deployment/cdk/opensearch-service-migration/lib/fetch-migration-stack.ts
>  Why these changes are required?
This change enables Fetch Migration to migrate data for indices that are identical between the source and target cluster, _and_ the document count on the target cluster is zero. Such behavior allow users to execute Fetch Migration in an idempotent manner without having to manually remove empty indices on the target cluster (that were created by a previous run of Fetch Migration that did not complete successfully)
> What is the old behavior before changes and new behavior after changes?
Prior to this change, all indices that were identical between the source and target clusters were ineligible for data migration. Now, we check the doc_count for identical indices on the target cluster and only exclude identical indices with a …
=> [Fetch Migration] Enable migration for identical, empty target cluster index

TrafficCapture/captureKafkaOffloader/build.gradle, TrafficCapture/trafficReplayer/build.gradle
Upgrade all transitive dependencies to use netty 4.1.100.
https://github.com/opensearch-project/opensearch-migrations/issues/397
=> Update all netty dependencies to wire up to be 4.1.100.Final

TrafficCapture/trafficReplayer/src/main/resources/log4j2.properties
Put log entries on separate lines, reduce verbosity & use an env variable, not a system property to pickup changes to WHERE the replayer logs should go.
Manual testing of the trafficReplayer and observed the output.
=> Fix logging regressions

deployment/cdk/opensearch-service-migration/README.md, deployment/cdk/opensearch-service-migration/cdk.context.json, deployment/cdk/opensearch-service-migration/default-values.json, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-console-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-service-core.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/traffic-replayer-stack.ts, deployment/cdk/opensearch-service-migration/package-lock.json
Sets the default traffic replayer number of instances to 0 and provides basic documentation for how a user should start the replayer.
Includes minor fixes from Brian's experience with deployment
Includes security fix for babel NPM
N/A
Deployment testing
=> Require manual start signal for the replayer for CDK

FetchMigration/python/index_operations.py, FetchMigration/python/tests/test_constants.py, FetchMigration/python/tests/test_index_operations.py, deployment/cdk/opensearch-service-migration/dp_pipeline_template.yaml
Small update to the metadata migration step of Fetch Migration to include [index aliases](https://opensearch.org/docs/latest/im-plugin/index-alias/) during metadata migration. This PR also includes unit test updates, as well as a minor fix to the Data Prepper pipeline template file used by the CDK to remove an invalid flag (Data Prepper does not require explicit configuration to toggle TLS).
* Category: Enhancement + Bug fix
```
Name                           Stmts   Miss  Cover
--------------------------------------------------
endpoint_info.py                  24      0   100%
endpoint_utils.py                107      1    99%
fetch_orchestrator.py             70      0   100%
fetch_orchestrator_params.py      22      0   100%
index_diff.py …
```
=> [Fetch Migration] Include index aliases in metadata migration

deployment/cdk/opensearch-service-migration/bin/app.ts, deployment/cdk/opensearch-service-migration/lib/stack-composer.ts
Minor change to allow a custom user agent for the Traffic Replayer to be specified from environment. If a user agent is also specified from a context option these users agents are joined and passed to the replayer.
N/A
Manual testing
=> Allow custom user agent to be specified from environment

TrafficCapture/replayerPlugins/jsonMessageTransformers/jsonMessageTransformerInterface/src/main/java/org/opensearch/migrations/transform/IJsonTransformerProvider.java, TrafficCapture/trafficReplayer/README.md, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TransformationLoader.java
By default, we'll still use classname, but this now gives us flexibility to use characters that cannot be in classnames. It will be up to the overall package and end-users bringing their own to NOT put conflicting transformers in place (as it always has been)
* Why these changes are required? Usability
* What is the old behavior before changes and new behavior after changes? No change, but this supports future changes
https://opensearch.atlassian.net/browse/MIGRATIONS-1439
gradle build
For more information on following Developer Certificate of Origin and signing off your commits, …
=> Use a name to look up transformers rather than the classname.

deployment/cdk/opensearch-service-migration/package-lock.json, deployment/cdk/opensearch-service-migration/package.json
Uses esbuild for bundling resources for lambda
N/A
Local jest tests
=> Add esbuild for quick packaging of lambda assests and avoids needing Docker

FetchMigration/python/endpoint_utils.py, FetchMigration/python/fetch_orchestrator.py, FetchMigration/python/index_operations.py, FetchMigration/python/metadata_migration.py, FetchMigration/python/migration_monitor.py, FetchMigration/python/tests/test_index_operations.py, FetchMigration/python/tests/test_metadata_migration.py, FetchMigration/python/tests/test_migration_monitor.py
This change adds more robust request error handling to network calls in Fetch Migration.
* The `GET` calls in metadata migration have been refactored into a helper method that executes the request and handles request errors by wrapping them in a `RuntimeError` and raising this.
* The `create_indices` logic to no longer throw on the first failure. Instead, the function attempts to create as many indices as possible and collects any failures into a `dict` that is then returned to the caller. Correspondingly, the metadata migration logic now handles raising a `RuntimeError` and also logs all failed index names along with their respective errors.
* All `requests` API calls also include a `timeout` value now to prevent an indefinite network wait
* Unit tests have been added and updated to …
=> [Fetch Migration] Improved request error handling

deployment/cdk/opensearch-service-migration/bin/app.ts
This protects against CDK failures when the `VERSION` file has [extra newlines in it](https://github.com/opensearch-project/opensearch-migrations/commit/3c4b9c7f9fd9c9ce27b0b75d13cd6793bfcbaf81), which would cause the tag value to be `1.0.0\n` which is invalid.
Tested manually and verified using `cdk synth`
=> [Bugfix] Strip newlines from VERSION file before using it as AWS tag value

FetchMigration/Dockerfile, FetchMigration/python/fetch_orchestrator.py, FetchMigration/python/metadata_migration.py, FetchMigration/python/tests/test_fetch_orchestrator.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/Dockerfile, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/showFetchMigrationCommand.sh
This change includes a few usability improvements and some bugfixes:
1. (Bugfix) `fetch_orchestrator.py` skips the check for a Data Prepper pipeline file if an `INLINE_PIPELINE` value is present
2. The Fetch Migration Dockerfile entrypoint has been updated to use the exec form. This allows command line arguments (such as flags) to be passed to it
3. A wrapper script (`showFetchMigrationCommand.sh`) has been added which provides an easy way to supply flags (such as `--create-only` or `--dryrun`) to the ECS task. The script does not run the AWS command - it only prints it for the user to copy and run themselves
4. The messaging in the metadata migration report has been tweaked to decrease confusion when performing a run where data isn't migrated
5. Added handling for scenarios where the …
=> [Fetch Migration] Usability updates and bugfixes

TrafficCapture/trafficReplayer/src/main/resources/log4j2.properties
Send Replayer tuple output to location specified by TUPLE_DIR_PATH (if defined).
Verified tuple files are available in specified output directory.
=> Update tuple output directory location

TrafficCapture/captureOffloader/src/main/java/org/opensearch/migrations/trafficcapture/IChannelConnectionCaptureListener.java, TrafficCapture/captureOffloader/src/main/java/org/opensearch/migrations/trafficcapture/StreamChannelConnectionCaptureSerializer.java, TrafficCapture/captureProtobufs/src/main/proto/TrafficCaptureStream.proto, TrafficCapture/coreUtilities/src/main/java/org/opensearch/migrations/trafficcapture/protos/TrafficStreamUtils.java, TrafficCapture/nettyWireLogging/src/main/java/org/opensearch/migrations/trafficcapture/netty/ConditionallyReliableLoggingHttpRequestHandler.java, TrafficCapture/nettyWireLogging/src/main/java/org/opensearch/migrations/trafficcapture/netty/HeaderValueFilteringCapturePredicate.java, TrafficCapture/nettyWireLogging/src/main/java/org/opensearch/migrations/trafficcapture/netty/LoggingHttpRequestHandler.java, TrafficCapture/nettyWireLogging/src/main/java/org/opensearch/migrations/trafficcapture/netty/PassThruHttpHeaders.java, TrafficCapture/nettyWireLogging/src/main/java/org/opensearch/migrations/trafficcapture/netty/RequestCapturePredicate.java, TrafficCapture/nettyWireLogging/src/test/java/org/opensearch/migrations/trafficcapture/netty/ConditionallyReliableLoggingHttpRequestHandlerTest.java, TrafficCapture/nettyWireLogging/src/test/java/org/opensearch/migrations/trafficcapture/netty/SimpleRequests.java, TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/CaptureProxy.java, TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/NettyScanningHttpProxy.java, TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/ProxyChannelInitializer.java, TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/NettyScanningHttpProxyTest.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/Accumulation.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/CapturedTrafficToHttpTransactionAccumulator.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/RequestResponsePacketPair.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/RequestSenderOrchestrator.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datatypes/ChannelTask.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datatypes/ChannelTaskType.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datatypes/ConnectionReplaySession.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datatypes/RawPackets.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datatypes/TimeToResponseFulfillmentFutureMap.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/ExhaustiveCapturedTrafficToHttpTransactionAccumulatorTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/KafkaRestartingTrafficReplayerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/SimpleCapturedTrafficToHttpTransactionAccumulatorTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/TrafficReplayerRunner.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/TrafficStreamGenerator.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/datatypes/TimeToResponseFulfillmentFutureMapTest.java
Add the ability to drop captures, while still forwarding the contents, for requests when a specific header matches some regex.
Since captures are really on a connection (socket) basis and not a request one, there are additional complications.
Data is captured as it is received.  We may not know that we want to drop packets early enough.  To compensate and to give the traffic stream enough details to differentiate this occurrence from a bug where packets were dropped, a new "RequestIntentionallyDropped" TrafficObservation has been introduced.  This observation will only be used when data for a request has been included.  That means that if we get a packet that has the entire HTTP preamble (first line + headers) that matches the drop filter, we won't capture anything at all.
The …
=> Drop user agent matches and a bugfix for over-committing KafkaRecords too early

FetchMigration/python/index_operations.py, FetchMigration/python/tests/test_index_operations.py
The [track_total_hits](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/search-your-data.html#track-total-hits) parameter forces an accurate doc-count even when the hit count for `_search` is above the default 10K limit. This resolves a bug where the total doc count was not being computed properly. Unit tests have also been updated to match the new path.
Tested emperically by performing a Fetch Migration between clusters, including an index with nested documents.
Unit tests:
```
Name                           Stmts   Miss  Cover
--------------------------------------------------
endpoint_info.py                  24      0   100%
endpoint_utils.py                106      1    99%
fetch_orchestrator.py …
```
=> [Fetch Migration] Add track_total_hits parameter to doc-count operation

test/conftest.py, test/requirements.txt, test/tests.py
This change contains improvements and refactors to the integration test script we have currently. It fixes some indentation errors that occurred at some point with the OSB test which was causing some indexes to not get checked. It also adds additional logic for the OSB test to add proper parameters for the `./runTestBenchmarks` script. Also included is a refactoring to not try and delete a given index after every test which can cause some flakiness between tests if using the proxy endpoint. Instead we use a unique index for each test now, and let the test delete the index if it chooses.
By …
=> Python Integ Test Updates

FetchMigration/python/fetch_orchestrator.py, FetchMigration/python/tests/test_fetch_orchestrator.py
The orchestrator now suppresses exit code `143` (graceful termination following a `SIGTERM`) if it is returned by the migration monitor, since this is a result of a workaround for https://github.com/opensearch-project/data-prepper/issues/3141
Unit tests have been added to cover this scenario. This change also ensures that a return_code is always returned by the function, and updates some stale comments.
Unit test coverage:
```
Name                           Stmts   Miss  Cover
--------------------------------------------------
endpoint_info.py                  24      0   100%
endpoint_utils.py                106      1    99%
fetch_orchestrator.py             76      0   100%
fetch_orchestrator_params.py      22      0 …
```
=> [Fetch Migration] Suppress exit code for graceful termination (SIGTERM)

FetchMigration/python/component_template_info.py, FetchMigration/python/index_operations.py, FetchMigration/python/index_template_info.py, FetchMigration/python/metadata_migration.py, FetchMigration/python/tests/test_index_operations.py, FetchMigration/python/tests/test_metadata_migration.py, FetchMigration/python/tests/test_template_info.py
This change enables index template and component template migration from source to target cluster as a part of the metadata migration step of Fetch Migration. Now that metadata migration performs multiple distinct steps, these have been refactored into encapsulated functions rather than being inline in the `run` entrypoint.
New functions have been added to `index_operations.py` to fetch and create component templates and index templates. The `IndexTemplateInfo` class derives from the `ComponentTemplateInfo` class since the former can include a "template" definition that overrides its components, and it includes additional fields (such as "composed_of", "priority" and "index_patterns")
Unit tests have been added to maintain high test coverage.
* Category: Enhancement, New feature, …
=> [Fetch Migration] Migrate index templates and component templates as a part of metadata migration

TrafficCapture/build.gradle, TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/proxyserver/testcontainers/annotations/HttpdContainerTest.java, TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/proxyserver/testcontainers/annotations/KafkaContainerTest.java, TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/proxyserver/testcontainers/annotations/TestContainerTest.java, TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/proxyserver/testcontainers/annotations/ToxiproxyContainerTest.java
Increase reliability of capture proxy tests by correctly passing longTest tag and lowering concurrency to numberOfCores/2
* Category: Test Fix
* Why these changes are required? Currently, proxy tests are running for both slow test 
* What is the old behavior before changes and new behavior after changes? Current, KafkaConfigurationCaptureProxyTest tests run for both test and slowTest tasks which is not desired, new behavior is that KafkaConfigurationCaptureProxyTest only runs with SlowTest with dynamic parallelization in half.
N/A
N/A
Tested with gradle test to ensure tests are not being run
For more …
=> Slow test fixup

deployment/cdk/opensearch-service-migration/lib/migration-assistance-stack.ts
Changing default S3 bucket name to be globally unique given S3 naming constraints via adding in account name.
* Category  - Bug Fix
* Why these changes are required? S3 buckets will fail to be created if not globally unique.
* What is the old behavior before changes and new behavior after changes? Before, no account name in bucket name, collisions can occur if multiple deployments happen with same stage name and region across any customer.
N/A
N/A
Ran CDK Diff on a stack where this was already deployed previously.
```
Stack migrationInfraStack (OSMigrations-dev-us-west-2-MigrationInfra)
Creating a change set, this may take a while...
Resources
[~] AWS::S3::Bucket migrationArtifactsS3 migrationArtifactsS35D99BC6A replace …
```
=> Make globally unique default bucket name

FetchMigration/python/progress_metrics.py, deployment/cdk/opensearch-service-migration/dp_pipeline_template.yaml, deployment/cdk/opensearch-service-migration/lib/fetch-migration-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-service-core.ts
* Updated default disk size for the Migration Console so larger OpenSearch Benchmark data sets can be run on it
* Updated Data Prepper container resources (vCPU, mem) per expert recommendation.
* Updated Data Prepper Pipeline parameters per expert recommendation
* Fixed a bug in how Fetch assesses idle Pipelines
https://opensearch.atlassian.net/browse/MIGRATIONS-1497
Manually tested the migration using the `awsE2ESolutionSetup.sh` test setup, running the Fetch Migration process from the Migration Console against my source which contains the `geonames` and `http_logs` indices from the OpenSearch Benchmark tool.  More details/logs in the linked JIRA.
For more information on …
=> Improvements to Fetch Migration stability

TrafficCapture/README.md, TrafficCapture/build.gradle, TrafficCapture/nettyWireLogging/build.gradle, TrafficCapture/settings.gradle
Adds support for local maven repo publish
* Category: New Feature
* Why these changes are required? Current projects wishing to import code from this project need a way to develop locally and import jars from local builds.
* What is the old behavior before changes and new behavior after changes? Did not support publishing, now support publishing.
[MIGRATIONS-1508](https://opensearch.atlassian.net/browse/MIGRATIONS-1508)
No
Created a sample external gradle project and imported all projects and attempted to build with some class imports.
Extract from test project build.gradle:
```groovy
repositories {
mavenCentral()
mavenLocal()
}
dependencies {
// This dependency is used by the application.
implementation libs.guava …
```
=> Local maven publish

TrafficCapture/dockerSolution/src/main/docker/docker-compose.yml
This is a temporary change to unblock PR testing github actions until the needed fix for 2.12 is released here: https://github.com/opensearch-project/opensearch-migrations/pull/480
N/A
Local docker testing
=> Update default docker OS version to 2.11

TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/CaptureProxy.java, TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/NettyScanningHttpProxy.java, TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/ProxyChannelInitializer.java
Add fields as protected to allow for class extension
* Why these changes are required? To allow for other projects to extend from this one
* What is the old behavior before changes and new behavior after changes? Classes did not allow visibility into member variables which would be needed in superclass extension.
N/A
N/A
Unit Tests
- [ x] New functionality has been documented
For more information on following Developer …
=> Add fields as protected to allow for class extension

TrafficCapture/coreUtilities/src/testFixtures/java/org/opensearch/migrations/tracing/InMemoryInstrumentationBundle.java, TrafficCapture/nettyWireLogging/build.gradle, TrafficCapture/nettyWireLogging/src/test/java/org/opensearch/migrations/trafficcapture/netty/ConditionallyReliableLoggingHttpHandlerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/FullReplayerWithTracingChecksTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/ParsedHttpMessagesAsDictsTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/ResultsToLogsConsumerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/datahandlers/NettyPacketToHttpConsumerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/tracing/TracingTest.java
Fix some flaky tests that were checking if metrics were being emitted.
They had a resource lock around them because they were using some static constructs provided by the Otel SDK. Now the resource locks on tests are gone for the ConditionallyReliableLoggingHttpHandlerTest and each test constructs its own non-static otel sdk. I've also tried to make tests that confirm otel instrumentation a bit safer.  They properly shut down metric exporter threads now.  They also wait a couple cycles before returning the in-memory exported metrics. I really wish that there were an exporter that didn't have to wait, but at least for now, this seems like the only option. At some point, it might be worth implementing a different MeterProvider which would in turn build out a different implementation …
=> Fix some flaky tests that were checking if metrics were being emitted.

deployment/cdk/opensearch-service-migration/lib/opensearch-domain-stack.ts, test/awsRunIntegTests.sh, test/tests.py
Minor fixes around console script calls that have recently changed, as well as adding specific dependencies between SSM parameters for the OpenSearch Domain stack and the resources they are for. This dependency link has not been an issue before but have noticed a case recently where the SSM parameter for an OpenSearch Domain endpoint tries to create before the Domain is finished deploying which results in an error as the Domain endpoint is not available yet.
https://opensearch.atlassian.net/browse/MIGRATIONS-1523
Deployment testing …
=> Minor E2E edits from Jenkins testing

TrafficCapture/testUtilities/src/testFixtures/java/org/opensearch/migrations/testutils/SimpleHttpServer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/NettyPacketToHttpConsumer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/netty/BacksideHttpWatcherHandler.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/datahandlers/NettyPacketToHttpConsumerTest.java
Currently, our replayer netty pipeline can only handle responses < 1MB due to configuration in HttpObjectAggregator. This change removes that restriction by enabling the BacksideHttpWatcherHandler to stream in content until HttpLastContent is received.
* Why these changes are required? Allow > 1 MB Responses
* What is the old behavior before changes and new behavior after changes? Old Behavior was an error after > 1 MB Responses with full content being buffered, this removes that failure mode and reduces memory footprint.
[MIGRATIONS-1605](https://opensearch.atlassian.net/browse/MIGRATIONS-1605)
Unit Tests
By submitting this pull request, I confirm that my contribution is made under the terms of …
=> Allow Larger Responses

TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/kafka/TrackingKafkaConsumer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/tracing/KafkaConsumerContexts.java
Improves logging in TrackingKafkaConsumer by improving clarity when an empty partition collection is assigned/revoked and correcting the behavior with `this` is logged by adding a toString method. Fixes metrics by only emitting metrics when a nonEmpty partition collection is modified and corrected for negative delta when partitions are revoked. Also moved a couple Warn Messages to Info for partition assginment/revocation.
* Why these changes are required? Improving correctness of observability in the replayer
* What is the old behavior before changes and new behavior after changes? Old Behavior, partition assignment increased during revocations and some logs were unintelligible, e.g.: 
```
[WARN ] 2024-03-08 17:42:18,263 [kafkaConsumerThread-1-1] TrackingKafkaConsumer …
```
=> Fix logging and metrics for TrackingKafkaConsumer with partition assignment

deployment/cdk/opensearch-service-migration/buildDockerImages.sh, test/awsE2ESolutionSetup.sh
Minor fixes
N/A
Manual testing
=> E2E Script very minor fixes

TrafficCapture/captureKafkaOffloader/src/main/java/org/opensearch/migrations/trafficcapture/kafkaoffloader/KafkaCaptureFactory.java, TrafficCapture/captureOffloader/src/main/java/org/opensearch/migrations/trafficcapture/CodedOutputStreamAndByteBufferWrapper.java, TrafficCapture/captureOffloader/src/main/java/org/opensearch/migrations/trafficcapture/CodedOutputStreamHolder.java, TrafficCapture/captureOffloader/src/main/java/org/opensearch/migrations/trafficcapture/StreamChannelConnectionCaptureSerializer.java, TrafficCapture/captureOffloader/src/test/java/org/opensearch/migrations/trafficcapture/StreamChannelConnectionCaptureSerializerTest.java, TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/CaptureProxy.java, TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/proxyserver/CaptureProxyConfigurationTest.java, TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/proxyserver/testcontainers/CaptureProxyContainer.java
This change adds functionality within the CodedOutputStreamHolder and refactors the StreamChannelConnectionCaptureSerializer to support limitless CodedOutputStreams through new interface method `getOutputStreamBytesLimit` which can be set to the limit of an underlying byte buffer or `-1` for a limitless CodedOutputStreams. 
* Why these changes are required? Currently, the CaptureProxy `--noCapture` parameter is broken and prevents proxy functionality.
* What is the old behavior before changes and new behavior after changes? Without this change `--noCapture` prevents proxy from forwarding requests to the destination, with this change the proxy behaves as expected
[Issues#540](https://github.com/opensearch-project/opensearch-migrations/issues/540) …
=> Support Limitless CodedOutputStreams

TrafficCapture/testUtilities/src/testFixtures/java/org/opensearch/migrations/testutils/SimpleNettyHttpServer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/Accumulation.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/HttpByteBufFormatter.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/ParsedHttpMessagesAsDicts.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/ReplayEngine.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/RequestSenderOrchestrator.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/ResultsToLogsConsumer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/NettyPacketToHttpConsumer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/netty/BacksideHttpWatcherHandler.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/traffic/expiration/AccumulatorMap.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/traffic/source/TrafficStreamLimiter.java, TrafficCapture/trafficReplayer/src/main/resources/log4j2.properties, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/ExhaustiveCapturedTrafficToHttpTransactionAccumulatorTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/HttpByteBufFormatterTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/ResultsToLogsConsumerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/SimpleCapturedTrafficToHttpTransactionAccumulatorTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/TrafficReplayerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/datahandlers/NettyPacketToHttpConsumerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/e2etests/KafkaRestartingTrafficReplayerTest.java, TrafficCapture/trafficReplayer/src/testFixtures/java/org/opensearch/migrations/replay/TestHttpServerContext.java
* Put some protections around time windows.  The default lookahead timeout is now 300 seconds.  That value must be > the packet timeout value.  If the lookahead was < the packet timeout, we could be waiting for streams to be expired but never get to the end of those streams, holding work remaining to be completed, resulting in a deadlock.  Warnings are printed out to the user and exit is called if configured incorrectly.
* Be more careful about when the trafficStreamLimiter should consider work to have been completed.  Now that work is marked as done once the response is returned by the target.  That may put more memory pressure on the system by processing many tuples, some of which may be outstatnding/buffered while more traffic is accumulated from the buffered stream.  However, this …
=> Assorted bugfixes and improvements 

.gitignore, RFS/README.md, RFS/build.gradle, RFS/docker/TestSource_ES_7_10/Dockerfile, RFS/docker/TestSource_ES_7_10/container-start.sh, RFS/src/main/java/com/rfs/ReindexFromSnapshot.java, RFS/src/main/java/com/rfs/common/ConnectionDetails.java, RFS/src/main/java/com/rfs/common/RestClient.java, RFS/src/main/java/com/rfs/common/S3SnapshotCreator.java, RFS/src/main/java/com/rfs/version_os_2_11/GlobalMetadataCreator_OS_2_11.java, RFS/src/main/java/com/rfs/version_os_2_11/IndexCreator_OS_2_11.java
* Updated README with better instructions on how to set up and run, test
* Added the ability for the RFS script to take the source snapshot from an existing cluster
* Added a Dockerfile to use as a source cluster in local testing
* https://opensearch.atlassian.net/browse/MIGRATIONS-1621
* Tested manually snapshotting w/ the new Dockerfile as a source against an AOS 2.11 Domain target in own AWS Account
* Also manually confirmed that using a local directory or existing snapshot in S3 still works
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTI …
=> RFS can now take the source snapshot

.github/workflows/release-drafter.yml
Update release-drafter.yml to use subshell for traffic capture building
* Why these changes are required? Fix release drafter action
* What is the old behavior before changes and new behavior after changes? Action would remain in TrafficCapture directory and not find the artifacts
N/A
Tested build commands locally
=> Update release-drafter.yml to use subshell for traffic capture building

.github/workflows/release-drafter.yml
Update release-drafter.yml artifact path to correctly include both source code and traffic capture jars.
Also updates softprops/action-gh-release to version 2 to comply with Node 16 EOL
* Category: New Feature
* Why these changes are required? Maven publishing
* What is the old behavior before changes and new behavior after changes? release workflow did not publish artifacts
=> Update release-drafter.yml artifact path

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/kafkaExport.sh, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/KafkaPrinter.java
Updates the KafkaPrinter with the ability to take in a commit offset to start printing from per partition.
Updates the KafkaExport script to be able to provide the commit offsets and record limits per partition.
Updates the KafkaExport script to directly compress the kafkaPrinter output script instead of first writing the uncompressed output to disc.
Note: Unit tests are currently lacking for the kafkaPrinter. Will focus on usability enhancements first then add testing once we know what we need.
* Why these changes are required? Improved usability of the KafkaExport script.
* What is the old behavior before changes and new behavior after changes? KafkaExport script now can process more data with less disk space and has increased functionality with commit offsets …
=> Kafka printer improvements

.github/workflows/release-drafter.yml, TrafficCapture/build.gradle
Add snapshot publish and snapshot version property
* Why these changes are required? Prereq for maven publishing
* What is the old behavior before changes and new behavior after changes? When `-Dbuild.snapshot=false` is provided, snapshot will not be included in the version tag.
https://opensearch.atlassian.net/browse/MIGRATIONS-1606
Ran publish commands locally with and without `-Dbuild.snapshot=false` 
- [x ] New functionality has been documented
- [ x] Commits are signed per the DCO using --signoff
By submitting this pull request, I confirm that my contribution is made under the …
=> Add snapshot publish and snapshot version property

TrafficCapture/build.gradle, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NettyJsonContentStreamToByteBufHandler.java
Add Artifacts in format for maven central, including scm on pom, sources, and javadoc
* Why these changes are required? Publish to maven central
* What is the old behavior before changes and new behavior after changes? Publish jar contains scm on pom, sources, and javadoc where they were missing before
[[MIGRATIONS-1606]
](https://opensearch.atlassian.net/browse/MIGRATIONS-1606)
Uploaded artifacts manually and verified existing errors. …
=> Add Artifacts in format for maven central

TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/HttpByteBufFormatter.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/traffic/source/TrafficStreamLimiter.java, TrafficCapture/trafficReplayer/src/main/resources/log4j2.properties
A memory leak for errantly formed http messages going through HttpByteBufFormatter; log4j2 config bug that stopped old replayer logs from compressing. I've also further improved the logging on shutdown.
* Category  Bug fixes
No Jira
=> Assorted bugfixes

TrafficCapture/captureKafkaOffloader/build.gradle, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/Dockerfile, TrafficCapture/trafficCaptureProxyServer/build.gradle, TrafficCapture/trafficCaptureProxyServerTest/build.gradle, TrafficCapture/trafficReplayer/build.gradle
* Why these changes are required? Fixing vulnerabilities identified by Mend
* What is the old behavior before changes and new behavior after changes? hopefully exactly the same
Resolves #397 
Resolves #482
Resolves #528
Unit tests & manual testing
=> Mend Fixes: MSK IAM Auth, Testcontainers, ApacheJMeter

TrafficCapture/buildSrc/src/main/groovy/org/opensearch/migrations/common/CommonUtils.groovy
Add ExitOnOutOfMemoryError flag to JVM Start
* Why these changes are required? Currently, various code paths squash observed exceptions. This can cause unexpected behavior with OutOfMemoryError as threads may die in unexpected state and leave the system unrecoverable but running. This was the observed behavior in [MIGRATIONS-1626](https://opensearch.atlassian.net/browse/MIGRATIONS-1626). This change sets the JVM flag to kill the jvm on out of memory which will allow better visibility and recovery at the container level.
* What is the old behavior before changes and new behavior after changes? Replayer may continue running incorrectly after OutOfMemoryError, now replayer jvm will die. 
[MIGRATIONS-1626](https://opensearch.atlassian.net/browse/MIGRATIONS-1626)
Is this a …
=> Add ExitOnOutOfMemoryError to Docker JVM Options

.github/workflows/release-drafter.yml, TrafficCapture/build.gradle
Previously, the Traffic Capture maven artifacts were always published under version 0.1.0. Now, the version will be based on the cut tag with the preface of `0.` signaling the potential for class interface changes.
* Why these changes are required? In order to publish subsequent releases and release candidates, the version needs to be based on the tag
* What is the old behavior before changes and new behavior after changes? Version was hardcoded at 0.1.0, now it is configurable based on tag
https://opensearch.atlassian.net/browse/MIGRATIONS-1606
- [ N/A ] New functionality includes testing
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> Update Release Drafter and Traffic Capture to define a variable for publishing version based on tag

TrafficCapture/build.gradle, TrafficCapture/trafficReplayer/build.gradle, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/TrafficReplayerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/datahandlers/NettyPacketToHttpConsumerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/e2etests/FullReplayerWithTracingChecksTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/e2etests/FullTrafficReplayerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/e2etests/SlowAndExpiredTrafficStreamBecomesTwoTargetChannelsTest.java
We're seeing some intermittent test failures during parallel execution due. While we would like to make the tests robust to these timing differences, for the maturity of the project and for the meantime, seeking to disable parallel test execution. 
Also, marked some long running tests (> 2s per run) as longTest
* Why these changes are required? Test Reliablity
* What is the old behavior before changes and new behavior after changes? Tests would intermittently fail, now tests take ~30 seconds and run reliably
[MIGRATIONS-1666](https://opensearch.atlassian.net/browse/MIGRATIONS-1666)
Ran on M1 Pro macbook, got build and test execution down to 29s https://gradle.com/s/6sybg3hsa6lry
- [x ] New …
=> Remove parallel test execution and mark long tests

RFS/src/main/java/com/rfs/ReindexFromSnapshot.java
* Category : Enhancement
* Previously all indices were suffixed with `_reindexed`. Now, they are 
https://opensearch.atlassian.net/browse/MIGRATIONS-1672
Manual testing
=> [RFS] Make indexSuffix a parameter

TrafficCapture/captureKafkaOffloader/build.gradle, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/Dockerfile, TrafficCapture/trafficReplayer/build.gradle
The latest version of aws-msk-iam-auth has a bug that prevents it from correctly acquiring IAM credentials on an EC2 instance. This bug is documented in their GH (https://github.com/aws/aws-msk-iam-auth/issues/168) and a PR has been merged, but no release with this fix has been cut.
We are downgrading our version of this library to the latest without this bug (2.0.3), which has been tested and verified on one of our EC2 instances.
n/a (but it's breaking the build on main)
Manual testing
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#de …
=> Downgrade aws-msk-iam-auth to latest good version (2.0.3)

RFS/README.md, RFS/build.gradle, RFS/docker/docker-compose.yml, RFS/src/main/java/com/rfs/ReindexFromSnapshot.java, RFS/src/main/java/com/rfs/common/S3Repo.java, RFS/src/test/java/com/rfs/common/S3RepoTest.java
* Updated the DockerCompose file for RFS to accept AWS Creds for the containers
* Updated RFS README to explain how to leverage the new behavior
* Fixed a bug in the S3Repo class' handling of S3 URI's (it was failing to handle passing in the bucket root path as an acceptable repo location)
* Unit tested the S3Repo class
Done while working on https://opensearch.atlassian.net/browse/MIGRATIONS-1600
* Ran the new unit tests (`./gradlew tests`)
* Ran the RFS process from snapshot through reindexing using the docker compose setup …
=> Updated RFS Docker Compose to handle AWS Creds; fix S3Repo bug

TrafficCapture/build.gradle, TrafficCapture/trafficCaptureProxyServer/build.gradle, TrafficCapture/trafficCaptureProxyServer/src/main/resources/log4j2.component.properties, TrafficCapture/trafficCaptureProxyServer/src/main/resources/log4j2.properties, TrafficCapture/trafficReplayer/build.gradle, TrafficCapture/trafficReplayer/src/main/resources/log4j2.component.properties, TrafficCapture/trafficReplayer/src/main/resources/log4j2.properties, TrafficCapture/trafficReplayer/src/test/resources/log4j2.properties, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-service-core.ts
Move log4j2 appenders to high performance async loggers:
* Existing logging was performed synchronous and blocking based on appender behavior. Moves this logic to be async with higher performance appender configuration.
* Note: This will still eventually block on flushing out the appenders, but there will be a buffer between logging and io streams.
* Existing Data Flow (All Blocking Calls):
Application → Log4j2 Appender → Standard Out → ECSLogDriver → Cloudwatch Logs
* New Data Flow (Blocking unless specified):
Application → [AsyncLogger](https://github.com/apache/logging-log4j2/blob/f0bd87818d43efa8337f56526ced2020c308d9bf/log4j-core/src/main/java/org/apache/logging/log4j/core/async/AsyncLogger.java#L66) (async)→ Log4j2 Appender → ECSLogDriver → Cloudwatch Logs
The AsyncLogger internally …
=> Enhance logging with Async and high performance appenders

TrafficCapture/build.gradle, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/HttpByteBufFormatter.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/HttpMessageAndTimestamp.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/ParsedHttpMessagesAsDicts.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/SourceTargetCaptureTuple.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/util/ByteBufUtils.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/util/NettyUtils.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/util/RefSafeHolder.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/util/RefSafeStreamUtils.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/HttpByteBufFormatterTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/RequestSenderOrchestratorTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/util/RefSafeStreamUtilsTest.java
Previously, we relied on stream mapping to create the byte buffs with an assumption that no exception would occur in the stream mapping. There was some uncertainty regarding lazy processing of the stream, and overall it was difficult to reason with. 
This change seeks to simplify this behavior by introducing a helper method `ByteBufUtils::createCloseableByteBufStream` which constructs a byte buf stream from a collection of byte arrays that keeps track of the reference counted objects it creates and releases them upon the Stream:close which can be leveraged by try-with-resources constructs.
This change also adds in static semantic analysis with google checkerror `MustBeClosed`
* Category: Bug fix/Enhancement
* Why these changes are required? Simplifies tracking of RefCount bugs by …
=> Simplify Netty RefCounting and ByteBuf Consumption

RFS/build.gradle, RFS/src/main/java/com/rfs/ReindexFromSnapshot.java, RFS/src/main/java/com/rfs/common/ConnectionDetails.java, RFS/src/main/java/com/rfs/common/DocumentReindexer.java, RFS/src/main/java/com/rfs/common/LuceneDocumentsReader.java, RFS/src/main/java/com/rfs/common/RestClient.java, RFS/src/main/java/com/rfs/common/Uid.java, RFS/src/test/java/com/rfs/common/ConnectionDetailsTest.java, RFS/src/test/java/com/rfs/common/LuceneDocumentsReaderTest.java, RFS/src/test/resources/log4j2-test.xml
* Updated RFS to use the reactor-netty library to perform asynchronous HTTP operations
* Updated RFS to perform indexing against the target cluster w/ bulk operations
* Added logging to capture when there's a wacky Lucene document we can't parse correctly (such as not having an `_id`)
* https://opensearch.atlassian.net/browse/MIGRATIONS-1600
* https://opensearch.atlassian.net/browse/MIGRATIONS-1651
* https://opensearch.atlassian.net/browse/MIGRATIONS-1671
* https://opensearch.atlassian.net/browse/MIGRATIONS-1649
* Added unit tests for the changes to the ConnectionDetails class
* Manually tested the changes to the reindexing behavior.  Example output below:
```
16:31:59.167 INFO  Blob files unpacked successfully
16:31:59.167 INFO …
```
=> RFS now uses reactor-netty for bulk indexing

RFS/build.gradle, TrafficCapture/buildSrc/src/main/groovy/org/opensearch/migrations/common/CommonUtils.groovy
There is a step in our gradle build that copies jar files from the project (e.g. Replayer) build artifacts directory into a `dockerSolution` build directory, which is where the generated Dockerfile expects them to be to copy them into the image.
However, this `dockerSolution` build directory is only "emptied" on a `gradle clean`, which means that as versions of our dependencies are updated, that build directory is effectively append-only and continues collecting old versions of jars, which are then copied into our images.
This causes issues. In this specific case, conflicting versions of log4j2 were causing the replayer to crash on startup, when the image was being built in a non-clean environment.
We're also probably making our images larger than they need to be.
The same pattern was …
=> Change gradle copy to sync to clear old jars

TrafficCapture/nettyWireLogging/src/main/java/org/opensearch/migrations/trafficcapture/netty/tracing/WireCaptureContexts.java, TrafficCapture/nettyWireLogging/src/test/java/org/opensearch/migrations/trafficcapture/netty/ConditionallyReliableLoggingHttpHandlerTest.java, TrafficCapture/nettyWireLogging/src/test/java/org/opensearch/migrations/trafficcapture/netty/RootWireLoggingContextTest.java, TrafficCapture/nettyWireLogging/src/test/java/org/opensearch/migrations/trafficcapture/netty/TestRootContext.java, TrafficCapture/nettyWireLogging/src/test/java/org/opensearch/migrations/trafficcapture/netty/TestStreamManager.java
The `gatheringRequest` span was missing from `GET` requests, but present for mutating requests. There was an unnecessary overridden method specifically for non-blocking requests, which wasn't closing that request.
The override is now removed, and tests are added to demonstrate the fixed behavior. The testing in this section was refactored a bit to prepare for additional trace-related testing. 
https://opensearch.atlassian.net/browse/MIGRATIONS-1658
Unit tests & manual testing …
=> Fix missing gatheringRequest trace for non-blocking requests

RFS/build.gradle
As part of our Solutions scanning we need to be able to generate a jacoco test report and provide list of jars for SonarQube to scan.
N/A
Local gradle builds
=> Add RFS gradle tasks for jacoco test report and copying of jars

TrafficCapture/replayerPlugins/jsonMessageTransformers/jsonJoltMessageTransformerProvider/src/test/java/org/opensearch/migrations/replay/AddCompressionEncodingTest.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/HttpByteBufFormatter.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/HttpMessageAndTimestamp.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/Utils.java
Increases MAX_PAYLOAD_BYTES_TO_PRINT to 100 MiB to keep in line with [AWS Opensearch Support](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/limits.html#network-limits)
* Why these changes are required? The default configuration should work with aws opensearch 
* What is the old behavior before changes and new behavior after changes? Large requests over 1MB would not be included in the tuple output. Now by default all requests that are supported within AWS Managed Opensearch will work.
[MIGRATIONS-1715](https://opensearch.atlassian.net/browse/MIGRATIONS-1715)
Unit Testing
- [x ] New functionality includes testing
- [ x] All tests pass, including unit test, integration test and …
=> Increase default MAX_PAYLOAD_BYTES_TO_PRINT to 100MiB

.github/workflows/gradle-build-and-test.yml
The TrafficCapture output sent to GitHub Actions is unyieldy for web broswers when you want to quickly see the source of a failure.  This change disable the 'info' logging level, causing the console output to go from ~238mb to 363kb.  Test results can be found as part of the workflow artifacts
=> Upload TrafficCapture test results as artifacts in GitHub workflow

test/awsE2ESolutionSetup.sh
Currently, if a step of the E2E setup script fails, it will just keep going, leading things to be deployed in incompatible orders.
It's preferable to just exit as soon as a failure occurs so that it's surfaced to the user and the rest of setup is paused, instead of creating confusing mixed situations.
Contributes to the demo pipeline
Manual testing
=> Add a bit of error checking and early exiting to the E2E Setup Script

TrafficCapture/captureOffloader/build.gradle, TrafficCapture/captureOffloader/src/main/java/org/opensearch/migrations/trafficcapture/CodedOutputStreamSizeUtil.java, TrafficCapture/captureOffloader/src/main/java/org/opensearch/migrations/trafficcapture/StreamChannelConnectionCaptureSerializer.java, TrafficCapture/captureOffloader/src/test/java/org/opensearch/migrations/trafficcapture/CodedOutputStreamSizeUtilTest.java, TrafficCapture/captureOffloader/src/test/java/org/opensearch/migrations/trafficcapture/StreamChannelConnectionCaptureSerializerTest.java, TrafficCapture/nettyWireLogging/src/test/java/org/opensearch/migrations/trafficcapture/netty/ConditionallyReliableLoggingHttpHandlerTest.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/ParsedHttpMessagesAsDicts.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/HttpJsonTransformingConsumer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NettyJsonContentAuthSigner.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NettyJsonContentCompressor.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datatypes/TransformedPackets.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/netty/BacksideSnifferHandler.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/RequestSenderOrchestratorTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/ResultsToLogsConsumerTest.java, TrafficCapture/trafficReplayer/src/testFixtures/java/org/opensearch/migrations/replay/TestCapturePacketToHttpHandler.java, TrafficCapture/trafficReplayer/src/testFixtures/java/org/opensearch/migrations/replay/TestUtils.java
This change seeks to simplify the complexity ByteBuf reading and duplicating indexes through use of `.duplicate` over `.slice` and being more intentional about side effects to the buffer after reading.
This change also seeks to harden NettyJsonContentAuthSigner by flushing the buffer in error cases and removing unnecessary release/retains.
Furthermore, moved to the Netty Base64 Encoder in ParsedHttpMessagesAsDicts to directly decode from ByteBufs.
Also, fixed up some trace logging that previously wasn't using a supplier to reduce unnecessary cycles.
This change also refactors StreamChannelConnectionCaptureSerializer to clean up the interfaces, improve performance, and remove bugs around chunking and serializing data.
* Category: Refactoring
* Why these changes are required? Simplify logic …
=> Favor ByteBuf Duplicates, NettyJsonContentAuthSigner and StreamChannelConnectionCaptureSerializer Refactoring

TrafficCapture/trafficCaptureProxyServer/src/main/resources/log4j2.component.properties, TrafficCapture/trafficReplayer/src/main/resources/log4j2.component.properties
With the current  Yield AsyncLogger.WaitStrategy, we are seeing high CPU usage. Updating to block removes this.
The [YieldingWaitStrategy javadoc states](https://lmax-exchange.github.io/disruptor/javadoc/com.lmax.disruptor/com/lmax/disruptor/YieldingWaitStrategy.html): 
>This strategy will use 100% CPU, but will more readily give up the CPU than a busy spin strategy if other threads require CPU resource.
While this could be more performant in a production system if log flushing was the primary bottleneck, it seems like not the best default value.
Compare this with [BlockingWaitStrategy](https://lmax-exchange.github.io/disruptor/javadoc/com.lmax.disruptor/com/lmax/disruptor/BlockingWaitStrategy.html):
>This strategy can be used when throughput and low-latency are not as important as CPU …
=> Update AsyncLogger.WaitStrategy to Block to fix high CPU

TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/ClientConnectionPool.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayerTopLevel.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/NettyPacketToHttpConsumer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/netty/BacksideHttpWatcherHandler.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/RequestSenderOrchestratorTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/datahandlers/NettyPacketToHttpConsumerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/e2etests/FullReplayerWithTracingChecksTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/e2etests/FullTrafficReplayerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/e2etests/SlowAndExpiredTrafficStreamBecomesTwoTargetChannelsTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/e2etests/TrafficReplayerRunner.java, TrafficCapture/trafficReplayer/src/testFixtures/java/org/opensearch/migrations/replay/RootReplayerConstructorExtensions.java
Currently with the traffic replayer, in the NettyPacketToHttpConsumer, the ReadTimeoutHandler is coupled with the  ConnectionClosedListenerHandler.
This means that we count the time in between request towards the ReadTimeout. This causes the channel to throw an exception while it is waiting to be re-used and may cause race conditions if the channel is reused exactly at the timeout interval.
This change places the ReadTimeoutHandler behind the handlers which remain between requests.
This change also fixes an issue where the BacksideHttpWatcherHandler was propagating exceptions through even though  it shouldn't since it handles them through the callback finalization.
* Why these changes are required? Properly handle read timeouts
* What is the old behavior before changes …
=> Fix ReadTimeoutException between requests

TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/CapturedTrafficToHttpTransactionAccumulator.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/RequestSenderOrchestrator.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/ResultsToLogsConsumer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayerCore.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/NettyPacketToHttpConsumer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/HttpJsonTransformingConsumer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/kafka/KafkaTrafficCaptureSource.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/kafka/TrackingKafkaConsumer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/util/ActiveContextMonitor.java, TrafficCapture/trafficReplayer/src/main/resources/log4j2.properties
This change fixes illegal argument exception in a few places where the replayer logs messages contain "{}".
* Category: Enhancement/Bug Fix
* Why these changes are required? Reduce log injection attacks and log formatting exceptions
* What is the old behavior before changes and new behavior after changes? Before this change, some logs contained errors around missing arguments. Now that is removed
Progress towards [Bug #633](https://github.com/opensearch-project/opensearch-migrations/issues/633)
Ran some end to end testing locally with various log levels and checking for errors. 
- [ x] New functionality has …
=> Fix IllegalArgumentException in Replayer logging

TrafficCapture/build.gradle, TrafficCapture/captureOffloader/src/main/java/org/opensearch/migrations/trafficcapture/StreamChannelConnectionCaptureSerializer.java, TrafficCapture/coreUtilities/src/main/java/org/opensearch/migrations/utils/SequentialSpanCompressingReducer.java
Fix Javadoc Errors
* Category: Documentation
* Why these changes are required? Required for release to maven
* What is the old behavior before changes and new behavior after changes? Javadoc fails on build
N/A
` ./gradlew javadoc`
- [ x] New functionality has been documented
- [ x] Commits are signed per the DCO using --signoff
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/m …
=> Fix Javadoc

RFS/docker/Dockerfile, TrafficCapture/buildSrc/src/main/groovy/org/opensearch/migrations/common/CommonUtils.groovy
Update base java image to amazoncorretto:11-al2023-headless removing [deprecated openjdk:11-jre](https://hub.docker.com/_/openjdk)
* Why these changes are required? Docker Image openjdk is depreacted
* What is the old behavior before changes and new behavior after changes? Base image used now amazoncorretto instead of openjdk
[MIGRATIONS-1724](https://opensearch.atlassian.net/browse/MIGRATIONS-1724)
Docker Solution startup and integration tests
- [N/A ] New functionality has been documented
By submitting this pull request, I …
=> Update base java image to amazoncorretto:11-al2023-headless

README.md
Refresh on supported version lsit.
=> Update supported versions in documentation

RFS/src/main/java/com/rfs/cms/CmsEntry.java, RFS/src/main/java/com/rfs/cms/OpenSearchCmsEntry.java, RFS/src/main/java/com/rfs/worker/MetadataStep.java, RFS/src/test/java/com/rfs/cms/CmsEntryTest.java, RFS/src/test/java/com/rfs/worker/MetadataStepTest.java
* Added simple backoff to the RFS Metadata Migration work lease
* https://opensearch.atlassian.net/browse/MIGRATIONS-1733
* Updated existing unit tests
* Added new unit tests
=> [RFS] Added backoff to RFS Metadata work leases

.flake8, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/README.md, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/osiMigrationLib/dev-requirements.txt, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/osiMigration.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/osiPipelineTemplate.yaml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/test/resources/basicAuthSourceAndSigv4Target.yaml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/test/resources/basicAuthSourceWithMultipleIndexInclusionRule.yaml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/test/resources/basicAuthSourceWithSingleIndexInclusionRule.yaml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/test/resources/sigv4SourceAndSigv4Target.yaml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/test/testOSIMigration.py, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-console-stack.ts
This change makes the following minor modifications for our OSI migration setup for the migration console
* Removes incorrect separate OSI pipeline IAM roles for source and target clusters. This must be the same role and have adjusted accordingly
* Add option to `include-index-regex`. This allows a user to specify multiple selection regexes that we will use to select which indices to migrate when configuring the template for OSI. As a default we will still try to move everything except system indices if not specified.
* Properly hookup missing CW log settings following OSI required conventions
* Minor cleanup in spots of OSI script
Local and AWS testing
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> Add/Modify OSI options on Migration Console

.gitignore, deployment/cdk/opensearch-service-migration/lib/lambda/msk-ordered-endpoints-handler.ts, deployment/cdk/opensearch-service-migration/lib/stack-composer.ts, deployment/cdk/opensearch-service-migration/test/common-utilities.test.ts, deployment/cdk/opensearch-service-migration/test/network-stack.test.ts, deployment/cdk/opensearch-service-migration/test/resources/invalid-context-file.json, deployment/cdk/opensearch-service-migration/test/resources/sample-context-file.json, deployment/cdk/opensearch-service-migration/test/stack-composer.test.ts, deployment/cdk/opensearch-service-migration/test/test-utils.ts, test/awsE2ESolutionSetup.sh, test/defaultCDKContext.json
This change includes the following changes to allow more customization with our awsE2ESolutionSetup.sh script as well as minor bug fixes:
* Allow option to migration CDK to provide a file path for loading CDK context and add tests cases around this
* Update e2e script to load CDK context for both source and target via a provided context file
* Add `clean-up-all` option to e2e script for cleaning up all deployed resources after running
* Modify spots in e2e script to use absolute path from single variable instead of on-the-fly relative paths
* Bug fix around Custom Resource for getting MSK broker endpoints which still tried to retrieve these endpoints on 'Delete' lambda events
https://opensearch.atlassian.net/browse/MIGRATIONS-1690
CDK tests and manual AWS testing
By submitting this pull …
=> Extend E2E script to allow CDK customization

test/awsE2ESolutionSetup.sh, test/awsRunIntegTests.sh
Resolves stack name change, verified pipeline is green with this branch
N/A
Manual/Jenkins testing
=> [Bug] Minor fix for runInteg script to use new stack name

test/operations.py, test/tests.py
Add test that verifies replayer function when waiting a minute between requests
Adds functionality within E2E test suite to explicitly reuse connection for requests
This was created in part to trigger potential edge cases that could have been associated with [ReadTimeoutHandler bug](https://opensearch.atlassian.net/browse/MIGRATIONS-1723)
* Why these changes are required? Verify no impact for bug
* What is the old behavior before changes and new behavior after changes? New test case
[MIGRATIONS-1722](https://opensearch.atlassian.net/browse/MIGRATIONS-1722)
E2E testing, verified bug is triggered during test case
- [x ] All tests pass, including unit test, …
=> Add test that verifies replayer function when waiting a minute between requests

TrafficCapture/dockerSolution/src/main/docker/elasticsearchWithSearchGuard/Dockerfile, test/README.md, test/operations.py, test/tests.py
Add E2E large request test
Fix documentation for E2E target_password
This task builds on top of #637
* Why these changes are required? Current E2E script misses tests on large requests which can have differing behavior
* What is the old behavior before changes and new behavior after changes? New Test which checks behavior for 20MB requests
Ran tests
- [x ] New functionality has been documented
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
=> Add E2E large request test

.github/workflows/linkCheck.yml
Lychee was scanning every file in the repo and then following the links to these external services... that seems overkill.  Maybe on some very specific files we can add it back in, but for our generic project we should only verify internal links. 
=> Fix lychee failures

deployment/cdk/opensearch-service-migration/lib/common-utilities.ts, deployment/cdk/opensearch-service-migration/lib/fetch-migration-stack.ts, deployment/cdk/opensearch-service-migration/lib/opensearch-domain-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/capture-proxy-es-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/capture-proxy-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-console-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-service-core.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/reindex-from-snapshot-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/traffic-replayer-stack.ts
We need to parameterize the partition every time we use `arn:aws` in order to support other partitions (a.k.a. gov cloud)
* Why these changes are required? GovCloud Support
* What is the old behavior before changes and new behavior after changes? CDK failed to deploy on gov cloud
[MIGRATIONS-1737](https://opensearch.atlassian.net/browse/MIGRATIONS-1737)
Deployed to gov cloud
- [ x] New functionality has been documented …
=> Parameterize AWS Partition for GovCloud

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/Dockerfile
Restore AWS integ test setup file on Console
N/A
=> Restore AWS integ test setup file on Console

TrafficCapture/dockerSolution/src/main/docker/elasticsearchTestConsole/catIndices.sh, deployment/cdk/opensearch-service-migration/lib/fetch-migration-stack.ts, deployment/cdk/opensearch-service-migration/lib/migration-assistance-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/capture-proxy-es-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/capture-proxy-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/elasticsearch-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/kafka-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-console-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-service-core.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/opensearch-container-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/reindex-from-snapshot-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/traffic-replayer-stack.ts, deployment/cdk/opensearch-service-migration/lib/stack-composer.ts
Removes ECS ServiceConnect from the infrastructure. This change builds off of [MIGRATIONS-1735](https://opensearch.atlassian.net/browse/MIGRATIONS-1735) which removes a hard dependency on service-connect.
* Why these changes are required? Support GovCloud
* What is the old behavior before changes and new behavior after changes? Service connect is deployed within services as a sidecar, this change removes that as it is currently not used for service communication with [OTEL Sidecar Change](https://opensearch.atlassian.net/browse/MIGRATIONS-1735)
[MIGRATIONS-1736](https://opensearch.atlassian.net/browse/MIGRATIONS-1736)
Deployed to AWS, verified functionality including migration console access to …
=> Remove ECS ServiceConnect

RFS/src/main/java/com/rfs/ReindexFromSnapshot.java, RFS/src/main/java/com/rfs/common/DocumentReindexer.java
Small refactor for testability of document indexer actions, following from the snapshot test cases [1].
- [1] https://github.com/opensearch-project/opensearch-migrations/pull/664#discussion_r1609036461
=> Reuse target client in doc reindexer

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/cli.py
This was supposed to be included in #667, but I missed the diff.
It adjusts the logging levels so that default is errors & warnings, `-v` adds info, and `-vv` adds debug.
Related to https://opensearch.atlassian.net/browse/MIGRATIONS-1743
manual
=> [Console Library] Log level adjustment

.github/workflows/release-drafter.yml
Current script is not correctly mapped to the build directory with https://github.com/opensearch-project/opensearch-migrations/pull/671
* Why these changes are required? Current release drafter failing
* What is the old behavior before changes and new behavior after changes? Release drafter failing, with this succeeding
N/A
Ran commands locally to verify correct operation
- [x ] New functionality includes testing
- [x ] New functionality has been documented
For …
=> Fix Release Drafter for Gradle Restructuring

RFS/src/main/java/com/rfs/RunRfsWorker.java, RFS/src/main/java/com/rfs/cms/CmsClient.java, RFS/src/main/java/com/rfs/cms/CmsEntry.java, RFS/src/main/java/com/rfs/cms/OpenSearchCmsClient.java, RFS/src/main/java/com/rfs/cms/OpenSearchCmsEntry.java, RFS/src/main/java/com/rfs/common/OpenSearchClient.java, RFS/src/main/java/com/rfs/common/SnapshotCreator.java, RFS/src/main/java/com/rfs/worker/GlobalState.java, RFS/src/main/java/com/rfs/worker/MetadataRunner.java, RFS/src/main/java/com/rfs/worker/MetadataStep.java, RFS/src/main/java/com/rfs/worker/Runner.java, RFS/src/main/java/com/rfs/worker/SnapshotRunner.java, RFS/src/main/java/com/rfs/worker/SnapshotStep.java, RFS/src/test/java/com/rfs/worker/MetadataRunnerTest.java, RFS/src/test/java/com/rfs/worker/MetadataStepTest.java, RFS/src/test/java/com/rfs/worker/SnapshotRunnerTest.java, RFS/src/test/java/com/rfs/worker/SnapshotStepTest.java
* Perform some refactoring of the RFS Worker and select, underlying libraries to better log exceptional situations
* https://opensearch.atlassian.net/browse/MIGRATIONS-1731
* Ran the `ReindexFromSnapshot.java` all-in-one script against the docker compose test setup
* Updated unit tests
* Provoked an exception to demonstrate the new logging behavior, displayed below:
```
chelma@3c22fba4e266 RFS % gradle runRfsWorker --args='--snapshot-name reindex-from-snapshot --s3-local-dir /tmp/s3_files --s3-repo-uri s3://chelma-iad-rfs-local-testing --s3-region us-east-1 --source-host http://localhost:19200 --target-host http://localhost:29200 --min-replicas 0 --index-template-whitelist "my_index_template" --component-template-whitelist "my_component_template"'
> Task :runRfsWorker
19:21:31.379 INFO …
```
=> [RFS] Improved RFS Worker exception logging

RFS/build.gradle, RFS/src/test/java/com/rfs/framework/ClusterOperations.java, commonDependencyVersionConstraints/build.gradle
Centralize RFS dependencies under the common shared `commonDependencyVersionConstraints` project
- Resolves https://github.com/opensearch-project/opensearch-migrations/issues/669
- Resolves https://github.com/opensearch-project/opensearch-migrations/issues/687
=> Centralize RFS dependencies

RFS/src/main/java/com/rfs/DemoPrintOutSnapshot.java, RFS/src/main/java/com/rfs/ReindexFromSnapshot.java, RFS/src/main/java/com/rfs/RunRfsWorker.java, RFS/src/main/java/com/rfs/cms/CmsClient.java, RFS/src/main/java/com/rfs/cms/CmsEntry.java, RFS/src/main/java/com/rfs/cms/OpenSearchCmsClient.java, RFS/src/main/java/com/rfs/cms/OpenSearchCmsEntry.java, RFS/src/main/java/com/rfs/common/IndexMetadata.java, RFS/src/main/java/com/rfs/common/OpenSearchClient.java, RFS/src/main/java/com/rfs/version_es_6_8/IndexMetadataFactory_ES_6_8.java, RFS/src/main/java/com/rfs/version_es_7_10/IndexMetadataFactory_ES_7_10.java, RFS/src/main/java/com/rfs/version_os_2_11/IndexCreator_OS_2_11.java, RFS/src/main/java/com/rfs/worker/GlobalState.java, RFS/src/main/java/com/rfs/worker/IndexRunner.java, RFS/src/main/java/com/rfs/worker/IndexStep.java, RFS/src/main/java/com/rfs/worker/MetadataStep.java, RFS/src/main/java/com/rfs/worker/SnapshotStep.java, RFS/src/test/java/com/rfs/cms/CmsEntryTest.java, RFS/src/test/java/com/rfs/framework/SimpleRestoreFromSnapshot_ES_7_10.java, RFS/src/test/java/com/rfs/worker/IndexRunnerTest.java, RFS/src/test/java/com/rfs/worker/IndexStepTest.java, RFS/src/test/java/com/rfs/worker/MetadataRunnerTest.java, RFS/src/test/java/com/rfs/worker/MetadataStepTest.java, RFS/src/test/java/com/rfs/worker/SnapshotRunnerTest.java, RFS/src/test/java/com/rfs/worker/SnapshotStepTest.java
* Updates the RFS Worker code to enable multi-node, coordinated index creation
* Added unit tests for the new code
* Will add component test in a follow-up PR as it is expected to require a fair amount of additional changes and I want to keep these PRs smaller if possible.
* https://opensearch.atlassian.net/browse/MIGRATIONS-1751
* Ran the unit tests successfully
* Ran the RFS Worker code locally using the Docker Compose setup to test the full behavior with a single node
```
chelma@3c22fba4e266 RFS % gradle runRfsWorker --args='--snapshot-name reindex-from-snapshot --s3-local-dir /tmp/s3_files --s3-repo-uri s3://chelma-iad-rfs-local-testing --s3-region us-east-1 --source-host http://localhost:19200 --target-host http://localhost:29200 --min-replicas 0 --index-template-whitelist …
```
=> [RFS] Updated RFS to perform coordinated index migration

.github/workflows/e2eTest.yml
We’re frequently encountering issues where builds fail due to rate limiting in the github actions workflows for pulling docker images.
For example, see https://github.com/opensearch-project/opensearch-migrations/pull/695#issuecomment-2148465012.
While we’ve considered multiple ways to resolve this, a quick one (suggested in the comment above) is to use the github actions caching mechanism to cache our docker images.
One issue I hit along the way was that I was defining the action as:
```
- name: Cache Docker Images
uses: ScribeMD/docker-cache@0.5.0
with:
key: docker-${{ runner.os }}-${{ hashFiles('**/docker-compose.yml', '**/Dockerfile') }}
```
which does the same thing as now--a hash of the file contents of all docker-compose and Dockerfiles in the repo. However, it turns out that this …
=> Cache docker images for E2E testing workflow in Github Actions

deployment/cdk/opensearch-service-migration/package-lock.json
For [CVE-2024-4068](https://nvd.nist.gov/vuln/detail/CVE-2024-4068), which affects 3.0.2 but is fixed in 3.0.3,
```
npm update braces
```
=> [Dependency Update] Update braces 3.0.2 dependency

RFS/build.gradle, commonDependencyVersionConstraints/build.gradle
Replacing a dependency that got lost in the shuffle of https://github.com/opensearch-project/opensearch-migrations/commit/fab14e282d020960ed1a9a3748cf66f1cb80ff01
* N/A; the build was working but RFS failed at runtime
Ran the RFS unit tests and manually performed a migration using the docker compose setup:
```
chelma@3c22fba4e266 RFS % gradle runRfsWorker --args='--snapshot-name reindex-from-snapshot --s3-local-dir /tmp/s3_files --s3-repo-uri s3://chelma-iad-rfs-local-testing --s3-region us-east-1 --source-host http://localhost:19200 --target-host http://localhost:29200 --min-replicas 0 --index-template-whitelist "my_index_template" --component-template-whitelist "my_component_template"'
.
.
.
> Task :RFS:runRfsWorker
11:22:10.903 INFO  Running RfsWorker
11:22:11.202 INFO  Checking if …
```
=> [RFS} Fixed a missing RFS dependency

test/tests.py
`test_0008_largeRequest` Seems to be failing constantly and we are merging changes without passing CI which seems like a bad habit to get into, disabling this test until it is addressed.
=> Disabling largeRequest test since it is flaky

FetchMigration/Dockerfile, TrafficCapture/dockerSolution/src/main/docker/elasticsearchTestConsole/runTestBenchmarks.sh, deployment/cdk/opensearch-service-migration/lib/msk-utility-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-console-stack.ts
This puts out a few fixes for issues encountered during a deployment to govcloud.
Fixes Fetch Migration dockerfile with older docker versions which requires a trailing / on COPY path when used with multiple files
> docker build --tag cdkasset-a31209dcc7fee0fb320f2e2f78921261a47ec36a2006da15987b8222825e3062 . exited with error code 1: When using COPY with more than one source file, the destination must be a directory and end with a /
Parameterizes aws partition in ARNs that are remaining
Fixes benchmark script when run with no parameters on AWS 
* Why these changes are required? Govcloud support
* What is the old behavior before changes and new behavior after changes? On some docker versions (e.g. 20.10.25), cdk deploy would fail with fetch migration. CDK deploy also …
=> Govcloud fix

FetchMigration/python/requirements.txt, test/requirements.txt
Mend is concerned about Requests 2.31.0. I suspect we're not actually using it because our definition is >= 2.31, but obviously it's necessary to guarantee that.
#670
This issue is also on the security dashboard, so we get a two-for-one.
One is a testing requirement, so it's tested via our tests. Ran unit tests for fetch.
=> Update requests lib for mend

FetchMigration/python/dev-requirements.txt
I don't have particularly high hopes for this one, but Mend now says that Werkzeug needs to be at 3.0.3 due to a new concern (previously it needed to be at 3.0.1). Somewhat confusingly, both the old (satisfied by 3.0.1) and new (needs 3.0.3) vulnerabilities are handled in issue #402 .
If we're very lucky, #402
Ran the fetch unit tests
=> [Mend] Update Werkzeug to 3.0.3 in Fetch

deployment/cdk/opensearch-service-migration/lib/service-stacks/capture-proxy-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-console-stack.ts, deployment/cdk/opensearch-service-migration/lib/stack-composer.ts
Friday's demo session was very helpful for finding bugs in my code to put the services.yaml file on the migration console in ECS.
Namely:
- better logic around what the source cluster endpoint is if we're not setting up the capture proxy ourselves
- making sure `loadServices` script is called even if the API is enabled  
Related to #695 , which resolved [MIGRATIONS-1744](https://opensearch.atlassian.net/browse/MIGRATIONS-1744)
Manual
=> [Migration Console] Fix bugs related to putting services.yaml file on migration console in ECS

RFS/docs/DESIGN.md, RFS/src/main/java/com/rfs/DemoPrintOutSnapshot.java, RFS/src/main/java/com/rfs/ReindexFromSnapshot.java, RFS/src/main/java/com/rfs/RunRfsWorker.java, RFS/src/main/java/com/rfs/cms/CmsClient.java, RFS/src/main/java/com/rfs/cms/CmsEntry.java, RFS/src/main/java/com/rfs/cms/OpenSearchCmsClient.java, RFS/src/main/java/com/rfs/cms/OpenSearchCmsEntry.java, RFS/src/main/java/com/rfs/common/DocumentReindexer.java, RFS/src/main/java/com/rfs/common/LuceneDocumentsReader.java, RFS/src/main/java/com/rfs/common/ShardMetadata.java, RFS/src/main/java/com/rfs/common/SnapshotShardUnpacker.java, RFS/src/main/java/com/rfs/version_es_6_8/ShardMetadataFactory_ES_6_8.java, RFS/src/main/java/com/rfs/version_es_7_10/ShardMetadataFactory_ES_7_10.java, RFS/src/main/java/com/rfs/version_os_2_11/GlobalMetadataCreator_OS_2_11.java, RFS/src/main/java/com/rfs/worker/DocumentsRunner.java, RFS/src/main/java/com/rfs/worker/DocumentsStep.java, RFS/src/main/java/com/rfs/worker/GlobalState.java, RFS/src/main/java/com/rfs/worker/IndexStep.java, RFS/src/main/java/com/rfs/worker/MetadataStep.java, RFS/src/test/java/com/rfs/cms/CmsEntryTest.java, RFS/src/test/java/com/rfs/common/LuceneDocumentsReaderTest.java, RFS/src/test/java/com/rfs/framework/SimpleRestoreFromSnapshot_ES_7_10.java, RFS/src/test/java/com/rfs/worker/DocumentsRunnerTest.java, RFS/src/test/java/com/rfs/worker/DocumentsStepTest.java, RFS/src/test/java/com/rfs/worker/IndexStepTest.java
* Added initial implementation of decentralized, coordinated document migration to the RFS Worker
* https://opensearch.atlassian.net/browse/MIGRATIONS-1752
* Added/ran unit tests
* Performed successful migrations using local Docker Compose setup:
```
chelma@3c22fba4e266 RFS % gradle runRfsWorker --args='--snapshot-name reindex-from-snapshot --s3-local-dir /tmp/s3_files --s3-repo-uri s3://chelma-iad-rfs-local-testing --s3-region us-east-1 --lucene-dir /tmp/lucene_files --source-host http://localhost:19200 --target-host http://localhost:29200 --min-replicas 0 --index-template-whitelist "my_index_template" --component-template-whitelist "my_component_template"'
.
.
.
> Task :RFS:runRfsWorker
11:24:33.905 INFO  Running RfsWorker
11:24:34.150 INFO  Checking if work remains in the Snapshot …
```
=> [RFS] Added coordinated doc migration to RFS Worker

.github/workflows/gradle-build-and-test.yml
This PR follows #698, which added docker image caching for the e2e tests pipeline. That has had a few days of bake time and has been working well, so this adds it to the gradle build and test workflow.
As mentioned in the JIRA task, one important consideration is that the cache key for this workflow is the same as for the e2e tests so that the cache can be shared. This is pretty straightforward because both workflows have the same first few steps, so I'm using exactly the same caching step and have verified that the results are the same (see my testing PR below).
[MIGRATION-1766](https://opensearch.atlassian.net/browse/MIGRATIONS-1766)
Manual, including in https://github.com/mikaylathompson/opensearch-migrations/pull/2
By submitting this pull request, I confirm that my contribution is …
=> Add docker image caching for Gradle github actions workflow

RFS/build.gradle, RFS/src/main/java/com/rfs/RfsCreateSnapshot.java, RFS/src/main/java/com/rfs/RfsMigrateDocuments.java, RFS/src/main/java/com/rfs/RfsMigrateMetadata.java, RFS/src/main/java/com/rfs/common/TryHandlePhaseFailure.java, RFS/src/main/java/com/rfs/worker/DocumentsStep.java, RFS/src/main/java/com/rfs/worker/IndexStep.java
* Split the all-in-one RFS Worker into phase-specific scripts to be more compatible with the Migration Console's CLI
* Some light refactoring to avoid copy/pasting code
* https://opensearch.atlassian.net/browse/MIGRATIONS-1785
* Ran the scripts manually against a local ES 7.17 Docker Compose source:
```
chelma@3c22fba4e266 RFS % gradle createSnapshot --args='--snapshot-name reindex-from-snapshot --s3-repo-uri s3://chelma-iad-rfs-local-testing --s3-region us-east-1 --source-host http://localhost:19200 --target-host http://localhost:29200'
> Task :RFS:createSnapshot
08:49:46.678 INFO  Running RfsWorker
08:49:47.178 INFO  Checking if work remains in the Snapshot Phase...
08:49:48.748 INFO  Snapshot not yet completed, entering Snapshot Phase...
08:49:48.748 INFO  Snapshot CMS Entry not found, …
```
=> [RFS] Split RFS Worker into phase-specific entrypoints

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/README.md, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/cluster.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/metrics_source.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/schema_tools.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/services.yaml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_cluster.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_metrics_source.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_osi_utils.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/utils.py
The services.yaml file is the core location for information about the current deployment and making the implementation clean and easy to validate will be helpful moving forward.
There were a few recent comments regarding the file format in the reviews of the e2e branch merge & the OSI backfill additions:
- ensure that the yaml file itself, and the README about it use spaces rather than tabs: https://github.com/opensearch-project/opensearch-migrations/pull/690#discussion_r1619216618
- write yaml structure with mutually-exclusive "nodes": https://github.com/opensearch-project/opensearch-migrations/pull/680#discussion_r1617504021
For the second point, the idea is to move AWAY from:
```
source_cluster:
authorization:
type: basic_auth
details:
user: abc
password: xyz
```
And towards:
``` …
```
=> [Console] Update format of services.yaml

RFS/build-preloaded-source-image.gradle, RFS/build.gradle, RFS/docker/TestSource_ES_7_10/container-start.sh, RFS/docker/TestSource_ES_7_17/container-start.sh
* Fixed a few RFS gradle bugs
* Switched RFS Docker Compose back to ES 7.10
* ES 7.17 test source container is not standing up correctly
N/A
manual testing
=> Fixed a few bugs in the gradle setup for rfs

RFS/src/main/java/com/rfs/version_es_7_10/SnapshotRepoData_ES_7_10.java, RFS/src/test/java/com/rfs/version_es_7_10/SnapshotRepoData_ES_7_10Test.java
Fix Jackson deserialization for 7.17 snapshot repo data
* Why these changes are required? 7.17 support
* What is the old behavior before changes and new behavior after changes? 7.17 failed with "unknown field uuid"
N/A
Manual testing in the cloud with a self managed 7.17.21 cluster on the migration console
TODO in a followup task. Automated testing added for various versions
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-or …
=> Fix Jackson deserialization for 7.17 snapshot repo data

test/requirements.txt
When running `python3 -m pip install -r requirements.txt` on this file an errors occurs because `>==` isn't a validate qualifier for version information.  This is causing issue with GitHub dependency scans and might have been the source of issues with mend and other tools configuration.
- See https://github.com/opensearch-project/opensearch-migrations/security/dependabot/11
Validated locally - with `python3 -m pip install -r requirements.txt`.  I'll follow up separaretely on #688 to make sure we are using the error checking form of this build script …
=> Fix broken python requirements file

.github/workflows/CI.yml
GitHub allows 'requiring' a job to be run before a pull request can be merged, by adding a new job that 'needs' all the other ci jobs, this job will run last and only if they all pass.
After this is merged someone from the admin team can update the repo settings to enforce this requirement.
=> Add job that passed when all other CI jobs have completed

.github/workflows/CI.yml, FetchMigration/Dockerfile
We believe that the docker cache is causing the e2e tests to fail, possibly by taking up too much disk space and forcing the target cluster to lock indices.
One solution (assuming a correct diagnosis) is to delete docker caching altogether. This, of course, also means we lose the benefits of caching the external images (namely, not being rate limited). This PR is an attempt to split the difference--keep the cache for external images, but don't cache all the `migrations/` images, which we're rebuilding anyways.
Hopefully https://opensearch.atlassian.net/browse/MIGRATIONS-1797
Several tests in the commits to this PR.
- The first commit is the actual content.
- The second commit makes a change to a Dockerfile and therefore creates a fresh cache (see run here: …
=> Add step to delete all `migrations` images from docker cache

CreateSnapshot/src/main/java/com/rfs/CreateSnapshot.java, RFS/src/main/java/com/rfs/common/ConnectionDetails.java, RFS/src/main/java/com/rfs/common/RestClient.java, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/cli.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/environment.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/logic/backfill.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/logic/snapshot.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/cluster.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/snapshot.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/utils.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/services.yaml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/data/services.yaml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_cli.py, deployment/cdk/opensearch-service-migration/lib/migration-services-yaml.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/reindex-from-snapshot-stack.ts, deployment/cdk/opensearch-service-migration/lib/stack-composer.ts, deployment/cdk/opensearch-service-migration/test/migration-console-stack.test.ts
Adds `console snapshot create` command full stack.
Adds stubbing for `console snapshot status`
* Category: New feature
* Why these changes are required? Enhance coverage of console library for end to end migrations
* What is the old behavior before changes and new behavior after changes? No snapshot group in console library
Part 1 for [MIGRATIONS-1792](https://opensearch.atlassian.net/browse/MIGRATIONS-1792)
Manual testing in both cloud and local environments.
```
root@ip-12-0-2-241:~# console snapshot create
17:36:46.236 INFO  Running RfsWorker
17:36:47.428 INFO  Checking if work remains in the Snapshot Phase...
17:36:49.526 INFO  Snapshot not yet completed, entering Snapshot Phase...
17:36:49.526 INFO  Snapshot CMS …
```
=> Add initial migration console snapshot support

CreateSnapshot/src/main/java/com/rfs/CreateSnapshot.java, MetadataMigration/src/main/java/com/rfs/MetadataMigration.java, RFS/src/main/java/com/rfs/common/FileSystemRepo.java
This allows testing snapshots and metadata migration locally (and long-term supporting it in our docker option)
My development speed
Manual -- we're flying pretty blind here.
Steps for manual testing:
- disable password verification on source and target cluster
- create a shared volume in the docker-compose file
- for source cluster in docker-compose:
- mount shared volume (in this case `/snapshot`)
- set in environment: path.repo=/snapshot
- for migration console in docker-compose
- mount shared volume
- run `chmod -R a+rwX /snapshot/` (there is absolutely a better way to do this, which is in part why I'm not checking in the pieces of this test setup, but it works for this)
- .`/createSnapshot/bin/CreateSnapshot --snapshot-name 2024-06-21-test-0001 --file-system-repo-path /snapshot/test …
=> Support local snapshots from CLI fro SnapshotCreate & MetadataMigration

.github/workflows/CI.yml, FetchMigration/Dockerfile
Fix FetchMigration build
* Why these changes are required? Error below
* What is the old behavior before changes and new behavior after changes? See error code below, with change, no error
Currently getting 
```
#10 [ 6/10] RUN pipenv install --system --deploy --ignore-pipfile
#10 1.257 Usage: pipenv install [OPTIONS] [PACKAGES]...
#10 1.257 
#10 1.257 ERROR:: --system is intended to be used for Pipfile installation, not installation of specific packages. Aborting.
#10 1.257 See also: --deploy flag.
#10 ERROR: process "/bin/sh -c pipenv install --system --deploy --ignore-pipfile" did not complete successfully: exit code: 2
------
> [ 6/10] RUN pipenv install --system --deploy --ignore-pipfile:
1.257 Usage: pipenv install [OPTIONS] [PACKAGES]...
1.257 
1.257 ERROR:: …
```
=> Fix FetchMigration build

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/environment.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/snapshot.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/services.yaml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/data/services.yaml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_snapshot.py, deployment/cdk/opensearch-service-migration/lib/migration-services-yaml.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/reindex-from-snapshot-stack.ts, deployment/cdk/opensearch-service-migration/test/migration-services-yaml.test.ts
Console library support for the Java changes in #754.
Supports snapshot descriptions like:
```
snapshot:
snapshot_name: "snapshot_2023_01_01"
s3:
repo_uri: "s3://os-demo-us-east-1-snapshots/2024-06-20-snapshot-test-0001/"
aws_region: "us-east-1"
```
or
```
snapshot:
snapshot_name: "snapshot_2023_01_01"
fs:
repo_path: "/snapshot/test"
```
Tests are fixed up (and a number are added), includes CDK support, etc.
n/a
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main …
=> [Console] Make changes for filesystem snapshots

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/logic/clusters.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_cli.py
Between different versions of ES and OS they have different system indices definitions, this can lead to the cat outputs looking different that is confusing
Tested the cat indices command on a ES7.10 cluster and OS2.14 cluster, no updates to existing test infrastructure
=> Cat command always shows all indices

DocumentsFromSnapshotMigration/src/main/java/com/rfs/RfsMigrateDocuments.java, DocumentsFromSnapshotMigration/src/test/java/com/rfs/FullTest.java, MetadataMigration/src/main/java/com/rfs/MetadataMigration.java, RFS/src/main/java/com/rfs/RunRfsWorker.java, RFS/src/main/java/com/rfs/common/FilterScheme.java, RFS/src/main/java/com/rfs/worker/IndexRunner.java, RFS/src/main/java/com/rfs/worker/ShardWorkPreparer.java
* Updated the RFS index creation and document migration code to filter out system indices (those starting w/ `.`) by default.  The user can still set an explicit allowlist to bypass this default behavior
Bug fix
Tested manually on my laptop.  Spun up the docker compose setup for RFS and manually added a new index called `.test_should_not_migrate`:
```
chelma@80a9970a4d02 opensearch-migrations % curl -X GET "http://localhost:19200/_cat/indices?v"
health status index                    uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   logs-221998              g2fDhAowSeO2L7bK0IFkOg   5   0       1000            0    165.7kb        165.7kb
green  open   logs-211998              GFJ4chDGT4mv9RnYCw0bVg   5   0       1000            0    162.3kb …
```
=> Updated RFS to filter out system indices by default

CreateSnapshot/src/main/java/com/rfs/CreateSnapshot.java, DocumentsFromSnapshotMigration/src/main/java/com/rfs/RfsMigrateDocuments.java, DocumentsFromSnapshotMigration/src/test/java/com/rfs/FullTest.java, RFS/src/main/java/com/rfs/ReindexFromSnapshot.java, RFS/src/main/java/com/rfs/common/ClusterVersion.java, RFS/src/main/java/com/rfs/common/DocumentReindexer.java, RFS/src/main/java/com/rfs/common/OpenSearchClient.java, RFS/src/main/java/com/rfs/common/S3SnapshotCreator.java, RFS/src/main/java/com/rfs/common/SnapshotCreator.java, RFS/src/main/java/com/rfs/common/SnapshotShardUnpacker.java, RFS/src/main/java/com/rfs/version_es_7_10/ShardMetadataData_ES_7_10.java, RFS/src/main/java/com/rfs/version_es_7_10/ShardMetadataFactory_ES_7_10.java, RFS/src/main/java/com/rfs/version_es_7_10/SnapshotMetadataFactory_ES_7_10.java, RFS/src/main/java/com/rfs/worker/DocumentsRunner.java, RFS/src/main/java/com/rfs/worker/SnapshotRunner.java, RFS/src/main/resources/log4j2.xml, TrafficCapture/dockerSolution/src/main/docker/elasticsearchTestConsole/testDocumentGenerator.py, TrafficCapture/dockerSolution/src/main/docker/elasticsearchTestConsole/testDocumentQuery.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/Dockerfile, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/cli.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/environment.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/logic/snapshot.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/snapshot.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/data/services.yaml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_cli.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_metadata.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_snapshot.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/loadServicesFromParameterStore.sh, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-service-core.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/reindex-from-snapshot-stack.ts
Implements several changes for performance and usability:
* Implements Snapshot Status
* Adds Snapshot Max Throughput parameter to Create
* Makes Snapshot Create Asynchronous with `--wait` option
* Modifies RFS to support ES 7.17
* Changes the RFS ECS Worker to use the right document migration main class
* Adds Bash-Completion to migration console with support for console-link library
* Fixes RFS logging pattern in Cloudwatch
_______
* Category: New Features
* Why these changes are required? Usability improvements for RFS and Migration Console
[MIGRATIONS-1792](https://opensearch.atlassian.net/browse/MIGRATIONS-1792)
Lots of manual testing locally …
=> Snapshot status

TrafficCapture/dockerSolution/src/main/docker/elasticsearchTestConsole/testDocumentGenerator.py, TrafficCapture/dockerSolution/src/main/docker/elasticsearchTestConsole/testDocumentQuery.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/logic/clusters.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/cluster.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/snapshot.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_snapshot.py, test/awsRunIntegTests.sh
Makes some improvements and fixes for the console printing.
The logic had a bug that didn't parse the response correctly.
* Why these changes are required? Currently status deep check not working
Manual testing and unit tests added
=> Update Console Status Printing

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/cli.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/logic/backfill.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/backfill_base.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/backfill_osi.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/backfill_rfs.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/cluster.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/ecs_service.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/snapshot.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/data/ecs_describe_services_5d_2p_1r.json, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/data/migrations_working_state_search.json, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/data/services_with_ecs_rfs.yaml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_backfill.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_cli.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_ecs.py
Add status output for `backfill` if the backfill type is RFS running on ECS.
`console backfill status` will print:
- status (e.g. BackfillStatus.RUNNING, BackfillStatus.STOPPED, etc.)
- number of running instances
- number of pending instances
- number of desired instances
Additionally, if `--deep-check` is added to the command, it will query the `.migrations_working_state` index on the target cluster and check how many shards are remaining.
```
root@ip-12-0-3-146:~# console backfill status
BackfillStatus.STOPPED
Running=0
Pending=0
Desired=15
root@ip-12-0-3-146:~# console backfill status --deep-check
BackfillStatus.RUNNING
Running=12
Pending=3
Desired=15
Remaining shards: 11
root@ip-12-0-3-146:~# console backfill status --deep-check
BackfillStatus.RUNNING
Running=15
Pending=0
Desired=15 …
```
=> [Console] Status for RFS Backfill

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/cli.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/environment.py
Bug came up in a demo test run where the command `console replayer start` was available but didn't work. This command shouldn't even be available, the correct one is `console replay start`. There was some code from a much earlier prototype of replayer control left in that caused this.
Removing all references to it now. …
=> [Console] Remove all duplicate replayer references

TrafficCapture/dockerSolution/src/main/docker/elasticsearchTestConsole/testDocumentGenerator.py
Improve testDocumentGenerator defaults with 10 requests per second which allows for faster replay and fixes a bug that caused an incorrect sleep calculation.
* Why these changes are required? Improve usage
N/A
Manual Testing
=> Improve testDocumentGenerator defaults

RFS/src/main/java/com/rfs/cms/OpenSearchWorkCoordinator.java, RFS/src/test/java/com/rfs/cms/WorkCoordinatorTest.java
Make the check for the setup index more reliable and only scan for work that is currently expired.
The HEAD check has now been rolled into the doUntil block for running setup() so that even 400s from the PUT command can be ignored and retried again in a sane manner.  The HEAD call should be the authoritative call when it returns 200. The second fix is for searching for items to update.  I had been searching for items that weren't even updated yet, causing a lot more pressure to create false positives and inefficiencies all around.
* Category Bug fix
* Why these changes are required? Too much contention/no guarantee on convergence for RFS Work coordination.
* What is the old behavior before changes and new behavior after changes? Lots of thrashing to setup an initial index and a large …
=> Two fixes to work coordination

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/backfill_rfs.py
The backfill status deep check now gives more detailed information about the state of the shards:
```
root@ip-12-0-3-187:~# console backfill status --deep-check
BackfillStatus.RUNNING
Running=1
Pending=0
Desired=3
Shards total: 46
Shards completed: 20
Shards incomplete: 26
Shards in progress: 0
Shards unclaimed: 26
``` …
=> [Console] Add detailed shard statuses

.github/workflows/CI.yml, gradle.properties
Now that we have multiple projects on the base, moving the TrafficCapture gradle properties to the top level will enable caching over the whole project so code changes in RFS don't trigger a rebuild of traffic capture
* Why these changes are required? Faster build and test times
* What is the old behavior before changes and new behavior after changes? GHA took ~30 min. We will see how long they take after this change is merged
N/A - Teammate request
GHA, Local Building …
=> Enable gradle caching over the whole project

DocumentsFromSnapshotMigration/build.gradle, DocumentsFromSnapshotMigration/src/main/java/com/rfs/RfsMigrateDocuments.java, DocumentsFromSnapshotMigration/src/test/java/com/rfs/FullTest.java, RFS/build.gradle
* Updated the `RfsMigrateDocuments.java` entrypoint to accept a local snapshot
* Added a new, local test that runs the full `RfsMigrateDocuments.java` against local target/source in Docker containers and a local snapshot.  The test asserts that the process exits with the expected status code.
* https://opensearch.atlassian.net/browse/MIGRATIONS-1807
* https://opensearch.atlassian.net/browse/MIGRATIONS-1809
Ran the new tests using `gradle DocumentsFromSnapshotMigration:slowTest`
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-c …
=> Updated RFS Doc Migration main() to use local snapshot

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/backfill_rfs.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_backfill.py
There was a bug in the `console backfill status --deep-check` command implementation where--if it were called before the working state index was created--it would give a very messy output like:
```
root@ip-12-0-2-195:~# console backfill status --deep-check
ERROR:console_link.models.backfill_rfs:Failed to execute query: 404 Client Error: Not Found for url: [https://vpc-storage-optimized-wdbsagz46uj6ptkjxjwwsmnhgm.us-east-2.es.amazonaws.com:443/.migrations_working_state/_search](https://vpc-storage-optimized-wdbsagz46uj6ptkjxjwwsmnhgm.us-east-2.es.amazonaws.com/.migrations_working_state/_search)
ERROR:console_link.models.backfill_rfs:Failed to execute query: 404 Client Error: Not Found for url: [https://vpc-storage-optimized-wdbsagz46uj6ptkjxjwwsmnhgm.us-east-2.es.amazonaws.com:443/.migratio …
```
=> [Console] Check whether working state index exists before querying

DocumentsFromSnapshotMigration/src/test/java/com/rfs/FullTest.java, RFS/build.gradle, RFS/src/testFixtures/java/com/rfs/http/SearchClusterRequests.java
I was seeing failures in `testDocumentMigration`, where the `sonested` index was listed as having ~3x the number of documents on the source as the destination.  By switching to `{index}/_count` it will prevent this weird behavoir
```
Expected: <{logs-221998=1000, geonames=1000, logs-211998=1000, reindexed-logs=0, nyc_taxis=1000, logs-231998=1000, logs-241998=1000, sonested=2977, logs-181998=1000, logs-201998=1000, logs-191998=1000}>
but: was <{logs-221998=1000, geonames=1000, logs-211998=1000, nyc_taxis=1000, logs-231998=1000, sonested=1000, logs-241998=1000, logs-181998=1000, logs-201998=1000, logs-191998=1000}>
``` …
=> Fix flaky behavior when comparing _cat/indices

DocumentsFromSnapshotMigration/build.gradle, coreUtilities/build.gradle
Sync'd the Gradle build behavior across our code projects so we can more effectively scan it w/ SonarQube
* https://opensearch.atlassian.net/browse/MIGRATIONS-1826
N/A
=> Syncing Gradle build/test behavior for SonarQube

CreateSnapshot/build.gradle, DocumentsFromSnapshotMigration/build.gradle, MetadataMigration/build.gradle, RFS/build.gradle, TrafficCapture/build.gradle, build.gradle, coreUtilities/build.gradle
* Centralized behavior of the `copyDependencies` and `jacocoTestReport` at the root Gradle level, per discussion in https://github.com/opensearch-project/opensearch-migrations/pull/806
* https://opensearch.atlassian.net/browse/MIGRATIONS-1826
Ran `gradle transformation:test`, `gradle transformation:copyDependencies`, and `gradle transformation:jacocoTestReport` successfully
=> Centralized Gradle behavior for sub-projects

vars/defaultIntegPipeline.groovy
One-line fix to resolve spacing between command arguments as being separate args for script
N/A
Cloud testing, successful pipeline run can be seen in Jenkins
=> [1 line] Wrap awsRunIntegTests command

deployment/cdk/opensearch-service-migration/options.md
* Fixed an incorrect documentation link that was causing the link checker to fail in https://github.com/opensearch-project/opensearch-migrations/pull/813
* https://opensearch.atlassian.net/browse/MIGRATIONS-1826
N/A
=> Fixed incorrect documentation link

RFS/src/main/java/com/rfs/common/OpenSearchClient.java, RFS/src/main/java/com/rfs/transformers/Transformer_ES_7_10_OS_2_11.java, RFS/src/main/java/com/rfs/version_es_6_8/IndexMetadataData_ES_6_8.java, RFS/src/main/java/com/rfs/version_es_7_10/IndexMetadataData_ES_7_10.java, RFS/src/main/java/com/rfs/version_os_2_11/IndexCreator_OS_2_11.java, RFS/src/test/java/com/rfs/framework/ClusterOperations.java, RFS/src/test/java/com/rfs/integration/EndToEndTest.java, RFS/src/testFixtures/java/com/rfs/framework/SearchClusterContainer.java
* Updated the RFS EndToEnd test to run 7.10 and 7.17 sources
* Fixed a bug in the `OpenSearchClient` where it would consider any response in the final `put` of  `createObjectIdempotent` successful
* Fixed a bug in `Transformer_ES_7_10_OS_2_11` where we were returning the wrong object from the `transformIndexMetadata` method
* Did NOT update the end-to-end tests to perform document migration yet in order to reduce the scope of this particular PR.
* https://opensearch.atlassian.net/browse/MIGRATIONS-1857
* Ran the various local tests …
=> [RFS] Added 7.10 and 7.17 sources to RFS EndToEndTest

build.gradle
Currently, spotless checks build and dependency directories (opensearch-cluster-cdk and node_modules). This can cause a failure if they are pulled through a build before the check is run.
* Why these changes are required? Spotless failing on non-clean workspace
* What is the old behavior before changes and new behavior after changes? Spotless fails on some yaml failures, not anymore
N/A
Ran locally
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#dev …
=> Fix spotless check ignore build and dependency directories

README.md, build.gradle
Spotless will no longer require or apply the java formatter.  I've updated the documentation to make it a recommendation.
=> Make the java code formatter optional

CreateSnapshot/README.md, CreateSnapshot/src/main/java/com/rfs/CreateSnapshot.java, RFS/src/main/java/com/rfs/common/OpenSearchClient.java
* Added a simple README for the CreateSnapshot tool
* Fixed a breaking bug in the CreateSnapshot tool.
* https://opensearch.atlassian.net/browse/MIGRATIONS-1840
Ran the CreateSnapshot tool:
```
chelma@80a9970a4d02 opensearch-migrations % ./gradlew CreateSnapshot:run --args='--snapshot-name reindex-from-snapshot --s3-repo-uri s3://chelma-iad-rfs-local-testing --s3-region us-east-1 --source-host http://localhost:19200'
> Task :CreateSnapshot:run
2024-07-17 15:45:59,921 WARN o.o.m.t.RootOtelContext [main] Collector endpoint=null, so serviceName parameter 'rfs' is being ignored since a no-op OpenTelemetry object is being created
2024-07-17 15:45:59,936 INFO c.r.CreateSnapshot [main] Running CreateSnapshot with --snapshot-name reindex-from-snapshot --s3-repo-uri …
```
=> Added CreateSnapshot README; fixed bug in that tool

.github/workflows/CI.yml, FetchMigration/Dockerfile, FetchMigration/python/Pipfile, FetchMigration/python/Pipfile.lock, TrafficCapture/dockerSolution/src/main/docker/elasticsearchTestConsole/Dockerfile, TrafficCapture/dockerSolution/src/main/docker/elasticsearchTestConsole/Pipfile, TrafficCapture/dockerSolution/src/main/docker/elasticsearchTestConsole/Pipfile.lock, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/Dockerfile, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/console_api/Pipfile, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/console_api/Pipfile.lock, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/Pipfile, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/Pipfile.lock, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/README.md, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/Pipfile, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/Pipfile.lock
Migration Console to AmazonLinux2023 Base.
To support Opensearch-Benchmark on ARM, required building yappi and hdf5 from source.
Updated to python 3.11 because that's what's available on AL2023
Moved to a shared virtual environment model across the whole console
* Category: New Feature
* Why these changes are required? Secure base images to prep for publish to dockerhub and ecr
* What is the old behavior before changes and new behavior after changes? Migration console was built on ubuntu, now it's on AL2023
[MIGRATIONS-1880](https://opensearch.atlassian.net/browse/MIGRATIONS-1880)
Building locally with arm, included starting up migration console api.
Also tested locally with FetchMigration container
By submitting this …
=> Migration Console to AmazonLinux Base

TrafficCapture/dockerSolution/src/main/docker/elasticsearchTestConsole/Dockerfile, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/Dockerfile, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/docker-compose-console-only.yml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/loadServicesFromParameterStore.sh, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-console-stack.ts
Set migration console venv on bash start
* Why these changes are required? Enable migration console to be accessible throughout image
* What is the old behavior before changes and new behavior after changes? Console was not accessible without manually loading the venv
N/A
Local testing with docker solution
Tested in AWS with Migration Console API Enabled
=> Set migration console venv on bash start

vars/defaultIntegPipeline.groovy
Jenkins is encountering a pattern where the gradle build fails every other run with:
```
* What went wrong:
Gradle build daemon has been stopped: since the JVM garbage collector is thrashing
```
In these cases, the gradle daemon expires and the next build succeeds. The following build fails again, indicating that a gradle daemon can "handle" only one run before running out of memory. We don't encounter this on github actions because we run with a new daemon each time.
This flag will run gradle without a daemon on Jenkins, thus avoiding the long-living-daemon-runs-out-of-memory issue.
By …
=> Add `--no-daemon` to jenkins gradle command

jenkins/migrationIntegPipelines/rfsBackfillE2EPipeline.groovy, test/awsRunIntegTests.sh, vars/defaultIntegPipeline.groovy
prepend pipenv run to integ
* Why these changes are required? Execute pytest within virtual environment 
* What is the old behavior before changes and new behavior after changes? Pytest not found on ath
Jenkins Tests
Tested with docker exec commands
=> prepend pipenv run to integ

TrafficCapture/dockerSolution/src/main/docker/elasticsearchTestConsole/Dockerfile
In [this change](https://github.com/opensearch-project/opensearch-migrations/pull/836/files#diff-7a2cd35c5f7cc5312dfb67e949e2cdc97ed00459df4214de5c8cd15887123415L10), the line that installs java onto the elasticsearch_test_console (and therefore the migration console) was removed from the install list. This was causing Jenkins failures, first of all because of Kafka tools not being runnable, but it would presumably proceed to Snapshot Creation & Metdata Migration failures as well.
Broken build in Jenkins pipeline
Manually tested locally. …
=> Install java on migration console

deployment/cdk/opensearch-service-migration/package-lock.json
`npm audit` details:
```
node_modules/fast-xml-parser
@aws-sdk/core  3.529.1 - 3.620.1
Depends on vulnerable versions of fast-xml-parser
node_modules/@aws-sdk/core
@aws-sdk/client-acm  3.529.1 - 3.620.1
Depends on vulnerable versions of @aws-sdk/client-sso-oidc
Depends on vulnerable versions of @aws-sdk/client-sts
Depends on vulnerable versions of @aws-sdk/core
Depends on vulnerable versions of @aws-sdk/credential-provider-node
node_modules/@aws-sdk/client-acm
@aws-sdk/client-kafka  3.529.1 - 3.620.1
Depends on vulnerable versions of @aws-sdk/client-sso-oidc
Depends on vulnerable versions of @aws-sdk/client-sts
Depends on vulnerable versions of @aws-sdk/core
Depends on vulnerable versions of @aws-sdk/credential-provider-node
node_modules/@aws-sdk/client-kafka
@aws-sdk/client-lambda …
```
=> [CVE] Update fast-xml-parser to version 4.4.1

.github/workflows/CI.yml
When the "all-ci-checks-pass" was marked as `Skipped` it wouldn't prevent merging.  I've change the job to always run, even if a downstream job hasn't passed, and it validates the results to be sure that all jobs completed successful.
Note; created this PR as a follow up after contacting GitHub support over the `Required` check not working as expected.
- Failure case verified with [#1](https://github.com/peternied/opensearch-migrations/actions/runs/10152498555)
- Passing case should be confirmed with this PR without any failures. …
=> Always run all checks job

RFS/src/main/java/com/rfs/common/RestClient.java, RFS/src/test/java/com/rfs/common/RestClientTest.java, gradle.properties
As it was, there was potential for an unbounded amount of repetitive counting because each request had a new pair of metering handlers attached to the connection.  Since reactor doesn't have a clear way to cleanup after each and every single request (consider retries), I've taken the view that every request that we make, first we try to remove any handlers that might have been present for the last request + removing them entirely in the doFinally() block.  Notice that we want to track the values on a request by request basis, hence the reason that we don't want to even reuse the handlers on different requests. I had to update the test to trigger this because the reactor HttpClient will use multiple connections by default, hence the reason that we weren't previously seeing this within the …
=> Fix connection metering for reactor clients.

commonDependencyVersionConstraints/build.gradle
Fix for [CVE-2020-13956](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-13956)
Only automated tests.  The existing versions were either already this version or 4.5.12. Given it's a patch update, I beleive the automated tests should be sufficient, but let me know if there are any specific areas of concern.
=> [CVE] Update org.apache.httpcomponents:httpclient to version '4.5.13'

.github/workflows/CI.yml, .github/workflows/release-drafter.yml
Adding a workflow on our release action to build and tag the docker images. I've commented out the section for engineering-effectiveness to add their secrets for the staging account.
Currently only builds the architecture the runner is on, will add cross arch build in a followup pr.
* Why these changes are required? Publishing to docker enables our solution to be consumed by other partners without building from source
* What is the old behavior before changes and new behavior after changes? Release action will build docker images, no publishing occurring at this step
https://opensearch.atlassian.net/browse/MIGRATIONS-1570
Tested in GHA https://github.com/opensearch-project/opensearch-migrations/act …
=> DockerHub Build and Tag on Release

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/README.md, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/cluster.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_cluster.py, deployment/cdk/opensearch-service-migration/lib/migration-services-yaml.ts, deployment/cdk/opensearch-service-migration/lib/opensearch-domain-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-console-stack.ts, deployment/cdk/opensearch-service-migration/lib/stack-composer.ts, deployment/cdk/opensearch-service-migration/test/migration-services-yaml.test.ts
Migration console side is verified in a real deployment; currently workign on CDK.
Adds support for a secrets manager secret to be used as the password value.
[MIGRATIONS-1760](https://opensearch.atlassian.net/browse/MIGRATIONS-1760) & [MIGRATIONS-1900](https://opensearch.atlassian.net/browse/MIGRATIONS-1900)
Good unit test coverage. Need to manually test.
=> [Console] Use credentials from secrets manager (python & CDK)

deployment/cdk/opensearch-service-migration/cdk.context.json
Our default CDK still deploys Fetch. This is in a pretty unsupported and untested state in our repo. It makes more sense to deploy RFS as our default, including because all of our documentation handles the RFS case.
Manual
=> Replace Fetch with RFS for default demo deploy

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/integ_test/common_operations.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/integ_test/e2e_tests.py
The `reindexed-logs` has been known to sometimes appear on clusters based on if the reindexing operation has run - even if there are zero items in it.  This can cause our test cases to fail intermittently if a background reindex was run, but no documents were created - excluding this index entirely.
I've also modified the code to use the default ignore list for all the existing cases - we can always tweak if need be in the future.
```
_____________________ ReplayerTests.test_replayer_0006_OSB _____________________
self = <replayer_tests.ReplayerTests testMethod=test_replayer_0006_OSB>
def test_replayer_0006_OSB(self):
source_cluster: Cluster = pytest.console_env.source_cluster
target_cluster: Cluster = pytest.console_env.target_cluster
run_test_benchmarks(cluster=source_cluster) …
```
=> Add reindexed-logs to default ignore list

DocumentsFromSnapshotMigration/docker/Dockerfile, DocumentsFromSnapshotMigration/docker/entrypoint.sh, deployment/cdk/opensearch-service-migration/lib/common-utilities.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-console-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/reindex-from-snapshot-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/traffic-replayer-stack.ts, deployment/cdk/opensearch-service-migration/lib/stack-composer.ts, deployment/cdk/opensearch-service-migration/test/reindex-from-snapshot-stack.test.ts
* Updated the RFS Documents Migration Container to use user-supplied values for the username/password if they are supplied via ENV variables and an entrypoint script.  In the event the password is supplied as an AWS Secret ARN, we unpack it in the entrypoint script.
* If the user has already supplied a username/password in the Run Command for RFS (also an ENV variable), we neglect the values specified in the ENV Variables for them.  This is to support the user being able to explicitly set those values via a top-level "Extra Args" setting in a previous PR (see: https://github.com/opensearch-project/opensearch-migrations/pull/861).
* Longer term, it is anticipated we'll pull all the args for RFS from a centralized configuration management store via the new entrypoint script.  This will …
=> RFS container uses entrypoint script for arg configuration

deployment/cdk/opensearch-service-migration/README.md, deployment/cdk/opensearch-service-migration/cdk.context.json, deployment/cdk/opensearch-service-migration/default-values.json, deployment/cdk/opensearch-service-migration/lib/migration-assistance-stack.ts, deployment/cdk/opensearch-service-migration/lib/network-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-console-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/opensearch-container-stack.ts, deployment/cdk/opensearch-service-migration/lib/stack-composer.ts, deployment/cdk/opensearch-service-migration/test/msk-utility-stack.test.ts, jenkins/migrationIntegPipelines/ec2SourceE2EPipeline.groovy, test/defaultMigrationContext.json
1. MSK is only deployed if we need it: any of the capture proxies OR the replayer.
2. Guarantee that the OS_USER_AND_SECRET parameter is created by sticking it in the network stack.
Bugs found while deploying for the Thousand Eyes project.
Unit tests are in place & pass, but I'm doing a full manual deploy & run through now.
=> CDK fixes for thousandeyes

.github/workflows/release-drafter.yml, jenkins/release.jenkinsFile
Update Release Drafter and Jenkinsfile with Docker credentials and promotions
Closes https://github.com/opensearch-project/opensearch-build/issues/4857
=> Update Release Drafter and Jenkinsfile with Docker credentials and promotions

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/integ_test/common_operations.py
Switch from _cat/indices to {index}/_count for reliable doc count - mirroring the same changes from the java codebase.
I consider the results on `_cat/indices` to be wrong, based on this comment [1] it checks the raw lucene count, whereas `{index}/_count` correctly maths together created / deleted / updated docs in that specific index.  The reason this count could fluctuate time could be relayed to when refreshes are triggered or segment merges that would cause the consolidation of delete/updated items.   It is hard to know the full set of potential triggers / edge cases with any given version of Elasticsearch or OpenSearch cluster.
- [1] https://stackoverflow.com/a/36857604/533057
- Related https://github.com/opensearch-project/opensearch-migrations/pull/801
- Fixes …
=> Switch from _cat/indices to {index}/_count for reliable doc count

.github/CODEOWNERS, .github/workflows/release-drafter.yml, MAINTAINERS.md
Fixes github actions for release, the release workflow needed issue permission.
Fixes AndreKurait maintainer (the approval workflow is case sensitive) 
* Why these changes are required? Fix release workflow
* What is the old behavior before changes and new behavior after changes? Release workflow wouldn't accept andre as approver, it also failed on permission creating issues.
[MIGRATIONS-1570](https://opensearch.atlassian.net/browse/MIGRATIONS-1570)
Tested in github actions by triggering workflow, was not able to test anything with assuming the role and after since it requires to be cut on the tag.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
=> Fix permissions for github release

.github/workflows/release-drafter.yml
Need to publish latest tags otherwise getting error on later step.
* Why these changes are required? Release script needs latest tags
* What is the old behavior before changes and new behavior after changes? Script fails
=> Publish latest tags to staging repo

RFS/src/main/java/com/rfs/tracing/BaseRootRfsContext.java, RFS/src/main/java/org/opensearch/migrations/metadata/tracing/RootMetadataMigrationContext.java, RFS/src/main/java/org/opensearch/migrations/reindexer/tracing/RootDocumentMigrationContext.java, RFS/src/main/java/org/opensearch/migrations/snapshot/creation/tracing/RootSnapshotContext.java
Sets the names snapshotCreation, metadataMigration, and documentMigration instead of "rfs" for all of them. 
=> Rfs root metric name switchout

DocumentsFromSnapshotMigration/src/main/java/com/rfs/RfsMigrateDocuments.java, DocumentsFromSnapshotMigration/src/test/java/com/rfs/ParallelDocumentMigrationsTest.java, RFS/src/main/java/com/rfs/common/DocumentReindexer.java, RFS/src/main/java/com/rfs/common/OpenSearchClient.java, RFS/src/main/java/com/rfs/common/RestClient.java, RFS/src/test/java/com/rfs/framework/SimpleRestoreFromSnapshot.java, RFS/src/test/java/com/rfs/framework/SimpleRestoreFromSnapshot_ES_7_10.java
New args are --documents-per-bulk-request and --max-connections.
Now users can specify:
* how many documents should be put into each bulk request to the target server.
* the maxConnection value to the ConnectionProvider that the reactor HttpClients will use.
gradle testing
=> Add two new command line flags for RfsMigrateDocuments 

DocumentsFromSnapshotMigration/src/main/java/com/rfs/RfsMigrateDocuments.java
* Updated the default, maximum shard size for RFS doc migrations from 50 GB to 80 GB.  This is to better match the available disk space on the ECS Fargate Containers the process runs on, which [have 200 GB of disk](https://github.com/opensearch-project/opensearch-migrations/blob/main/deployment/cdk/opensearch-service-migration/lib/service-stacks/reindex-from-snapshot-stack.ts#L101).
* RFS currently requires ~2X shard-size disk space in order to do its work.  This is because it first needs to download the shard from S3, then unpack/reassemble it into a Lucene index on disk.  This creates two copies of the shard in different formats.
* We have a task (https://opensearch.atlassian.net/browse/MIGRATIONS-1750) to switch from Fargate ephemeral storage to EBS/EFS and resolve this problem.
N/A …
=> Updated default max shard size for RFS to 80 GB

RFS/src/main/java/com/rfs/common/InvalidResponse.java, RFS/src/main/java/com/rfs/common/OpenSearchClient.java, RFS/src/main/java/com/rfs/version_os_2_11/IndexCreator_OS_2_11.java, RFS/src/test/java/com/rfs/common/InvalidResponseTest.java, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/integ_test/replayer_tests.py
We've found issues when creating indexes from Elasticsearch contain schema elements that are not supported in OpenSearch.  Rather than attempting to write these all down we are parsing out the error response on 400 requests and attempting to remove these illegal arguments.
Here is an example where the index the creation date and other information included and the service returns an error, and then by parsing the error the illegal arguments can be stripped of a reattempted request.
```json
{
"aliases" : { },
"mappings" : {...},
"settings" : {
"creation_date" : "1723061506227",
"number_of_replicas" : 1,
"number_of_shards" : "1",
"provided_name" : "blog_2023",
"uuid" : "2IpsjQoHQsm7tSobRZmCJg"
}
}
```
```json
{
"error": {
"root_cause": [
{
"type": "illegal_argument_exception",
"reason": …
```
=> Handle InvalidResponse cases during index creation

RFS/src/main/java/com/rfs/common/OpenSearchClient.java, RFS/src/main/java/com/rfs/version_os_2_11/IndexCreator_OS_2_11.java, RFS/src/test/java/com/rfs/version_os_2_11/IndexCreator_OS_2_11Test.java
Keep index creator exception behavior consistent and add unit tests
- Following up on https://github.com/opensearch-project/opensearch-migrations/pull/876
=> Keep index creator exception behavior consistent and add unit tests

DocumentsFromSnapshotMigration/README.md, DocumentsFromSnapshotMigration/src/main/java/com/rfs/RfsMigrateDocuments.java, DocumentsFromSnapshotMigration/src/test/java/com/rfs/ParallelDocumentMigrationsTest.java, RFS/src/main/java/com/rfs/common/DocumentReindexer.java, RFS/src/main/java/com/rfs/common/OpenSearchClient.java, RFS/src/test/java/com/rfs/framework/SimpleRestoreFromSnapshot.java, RFS/src/test/java/com/rfs/framework/SimpleRestoreFromSnapshot_ES_7_10.java
Properly implement max connections through flux concurrency in RFS with flatmap(_, concurrency)
> @param concurrency the maximum number of in-flight inner sequences
Current implementation with client connection provider resulted in exceptions being thrown when the flux requested more than were available.
Also, fixed a bug where the backoff logic appeared to occur in two places.
Set's the max concurrency here to 50 by default (previously was reactor.util.concurrent.Queues.SMALL_BUFFER_SIZE which is default to 256
* Why these changes are required? Correct backoff and concurrency, will allow for greater horizontal scaling
* What is the old behavior before changes and new behavior after changes? Concurrency was at 256 and threw errors if trying to set lower than that. …
=> Properly implement max connections through flux concurrency in RFS

.codecov.yml
I noticed that java hasn't be producing code coverage reports on pull requests and according to code cov the uploaded java report are outside the 12h allowed window.  Inspecting the python report 1723150943042 was the start time vs 1722619505248 in java.  Translated the java report is 6 days behind - unsure how this happened.
Since the time recorded in the report isn't critical disabling the codecov max_report_age check.
_Report from a recent pull request [[link]](https://app.codecov.io/gh/opensearch-project/opensearch-migrations/commit/1b08cfe79059780f991b813a3f81a7c656d724a7)_
- Resolves https://opensearch.atlassian.net/browse/MIGRATIONS-1934
Verified the new file with the following command:
`curl --data-binary @.codecov.yml https://codecov.io/validate`
By submitting this pull request, …
=> Remove the max report age requirement on codecov

deployment/cdk/opensearch-service-migration/lib/service-stacks/capture-proxy-es-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/capture-proxy-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/reindex-from-snapshot-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/traffic-replayer-stack.ts, deployment/cdk/opensearch-service-migration/lib/stack-composer.ts
The RFS stack was accepting an `otelEnabled` parameter, but it wasn't actually being passed in or affecting the args passed in.
n/a
Manual (these changes are currently deployed for RFS testing)
=> Add otel to RFS stack

TrafficCapture/dockerSolution/src/main/docker/elasticsearchTestConsole/Dockerfile, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/Dockerfile
Build failures have occurred when the 'Connection timed out.' or 'Network is unreachable.' errors have been seen by wget calls to download Kafka.  To make this more rebust add a set of retry parameters to all usages of wget during docker builds.
=> Improve robustness on docker wget calls

RFS/src/main/java/com/rfs/common/OpenSearchClient.java, RFS/src/test/java/com/rfs/common/OpenSearchClientTest.java
Add OpenSearchClientTest to verify creation and retry behavior
- Follow up to https://github.com/opensearch-project/opensearch-migrations/pull/876
=> Add OpenSearchClientTest to verify creation and retry behavior

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/cli.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/environment.py
We're currently working on a scenario in which a target cluster is defined, but the source cluster is not and all work proceeds off of a snapshot.
The console lib _tolerates_ this, but it doesn't handle it particularly well. This PR allows it to specifically handle undefined source clusters.
It's also plausible for user to want to use the create snapshot tooling without having a target cluster defined, so I'm supporting that scenario as well, but giving a warning log message to make it clear that functionality may be impaired without a target cluster (e.g. metadata migration, backfill status checks, etc.).
Example output with no source cluster defined:
```
(.venv) bash-5.2# console clusters connection-check
SOURCE CLUSTER
No source cluster defined.
TARGET CLUSTER …
```
=> [Console] Add more flexibility around which clusters are defined

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/snapshot.py
The message that the snapshot had been created successfully was confusing, changed to "initiated successfully"
Noted from testing with Prashant
=> [Console] Created -> initiated in snapshot logging

TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/transform/SigV4AuthTransformerFactory.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/transform/SigV4AuthTransformerFactoryTest.java, TrafficCapture/trafficReplayer/src/testFixtures/java/org/opensearch/migrations/replay/TestUtils.java, TrafficCapture/transformationPlugins/jsonMessageTransformers/jsonJoltMessageTransformerProvider/src/test/java/org/opensearch/migrations/replay/PayloadRepackingTest.java
Fixed a bug that was in the replayer on sigv4 requests without payloads when content-type did not exist.
Cleaned up the unit tests for this 
* Why these changes are required? sigv4 failures without payloads
* What is the old behavior before changes and new behavior after changes? sigv4 failures without payloads
Added unit tests
=> Fix replayer sigv4 logic without payload

commonDependencyVersionConstraints/build.gradle
[CVE] Updated jersey-common from 2.30.1 -> 2.34
- Mitigates this issue https://github.com/eclipse-ee4j/jersey/security/advisories/GHSA-c43q-5hpj-4crv
=> [CVE] Updated jersey-common from 2.30.1 -> 2.34

.github/workflows/release-drafter.yml
Update release drafter permission with `content: write` to submit releases as specified in https://github.com/softprops/action-gh-release?tab=readme-ov-file#permissions
* Why these changes are required? Required to publish a release with the github action (new since the docker changes started specifying permissions)
* What is the old behavior before changes and new behavior after changes? Release failed to publish since https://github.com/opensearch-project/opensearch-migrations/pull/860
N/A
N/A, verified through documentation …
=> Update release drafter permissions

DocumentsFromSnapshotMigration/src/test/java/com/rfs/PerformanceVerificationTest.java, RFS/src/main/java/com/rfs/common/DocumentReindexer.java
Updates the DocumentReindexer logic to use shared threads for subscribing on the bulk request mono (which can be done due to async non-blocking client) as well as updated the unit tests against this behavior.
Updates the DocumentReindexer buffering logic to be 50 bulk requests which can be a more consistent size based on workloads than on a document level.
* Why these changes are required? Improve throughput and reduce memory pressure
* What is the old behavior before changes and new behavior after changes? See Testing below
[MIGRATIONS-1961](https://opensearch.atlassian.net/browse/MIGRATIONS-1961)
Tested in AWS against main commit e8e2770 with OR1 and 4vcpu 8gb tasks with `--max-connections 20` …
=> NonBlocking Sender Scheduling and Bulk Request Buffering

TrafficCapture/trafficReplayer/src/main/resources/log4j2.properties
Fix broken variable reference in traffic capture
=> Fix broken variable reference in traffic capture

deployment/cdk/opensearch-service-migration/lib/common-utilities.ts, deployment/cdk/opensearch-service-migration/lib/network-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-console-stack.ts, deployment/cdk/opensearch-service-migration/lib/stack-composer.ts
Remove Migration Console API from ALB to simplify security story since this API is experimental and does not support auth.
* Category: Simplification
* Why these changes are required? Simplify Security
* What is the old behavior before changes and new behavior after changes? No ALB Listener for Migration Console API, TG remains for customer to associate with their own listener.
[MIGRATIONS-1971](https://opensearch.atlassian.net/browse/MIGRATIONS-1971)
Existing unit tests for cdk synth. …
=> Remove Migration Console API from ALB

DocumentsFromSnapshotMigration/src/test/java/com/rfs/EndToEndTest.java, DocumentsFromSnapshotMigration/src/test/java/com/rfs/ParallelDocumentMigrationsTest.java, MetadataMigration/src/test/java/org/opensearch/migrations/EndToEndTest.java, RFS/src/main/java/com/rfs/transformers/TransformFunctions.java, RFS/src/main/java/com/rfs/version_es_7_10/SnapshotReader_ES_7_10.java
Support for OpenSearch 1.3 to be a source cluster & readme updates
Expanded end to end test to include OS 1.3 in all tests that we had for ES 7.17
=> Support for OpenSearch 1.3 to be a source cluster

RFS/src/main/java/com/rfs/common/S3Repo.java, RFS/src/test/java/com/rfs/common/S3RepoTest.java
Fix for this error because the snapshot repo doesn't exist:
```
2024-09-05 21:56:33,737 INFO o.o.m.MetadataMigration [main] Starting Metadata Migration
2024-09-05 21:56:33,758 INFO o.o.m.c.Migrate [main] Command line arguments {0}
2024-09-05 21:56:33,758 INFO o.o.m.c.Migrate [main] Running Metadata worker
2024-09-05 21:56:35,523 INFO o.o.m.c.ClusterProviderRegistry [main] Found snapshot resource reader for version: Elasticsearch 7.10.2
2024-09-05 21:56:38,340 INFO o.o.m.c.ClusterProviderRegistry [main] Found remote writer for version: OpenSearch 2.9.0
2024-09-05 21:56:38,677 INFO o.o.m.c.Migrate [main] Using transformation com.rfs.transformers.Transformer_ES_7_10_OS_2_11@3a1f2a1
2024-09-05 21:56:38,730 INFO c.r.w.MetadataRunner [main] Migrating the Templates...
2024-09-05 21:56:39,514 …
```
=> Detect when the snapshot repo bucket cannot be found and return a clear error message

.github/workflows/CI.yml, CreateSnapshot/build.gradle, DocumentsFromSnapshotMigration/build.gradle, MetadataMigration/build.gradle, RFS/build.gradle, TrafficCapture/build.gradle, TrafficCapture/captureKafkaOffloader/build.gradle, TrafficCapture/captureOffloader/build.gradle, TrafficCapture/captureProtobufs/build.gradle, TrafficCapture/trafficReplayer/build.gradle, TrafficCapture/transformationPlugins/build.gradle, TrafficCapture/transformationPlugins/jsonMessageTransformers/jsonMessageTransformerInterface/build.gradle, awsUtilities/build.gradle, build.gradle, buildSrc/build.gradle, buildSrc/src/main/groovy/org.opensearch.migrations.java-common-conventions.gradle, commonDependencyVersionConstraints/build.gradle, coreUtilities/build.gradle, testHelperFixtures/build.gradle, transformation/build.gradle
Generates a task mergeJacocoReports which runs all tests that run jacoco and generates one shared report.
Cleans up some of the duplicated definitions in build.gradle
Fixes an issue where some classes weren't showing adequate coverage when tested by a different project.
* Category: Bug Fix, Refactoring
[MIGRATIONS-1976](https://opensearch.atlassian.net/browse/MIGRATIONS-1976)
Missing coverage verified to exist
Overall coverage + 7%
For more information on following Developer Certificate of Origin and …
=> Unified code coverage

.github/workflows/CI.yml
Fixes codcov failues by not running on push events. Codecov has been failing on push events for a long time, but recently in #928 codecov was modified to fail on error instead of silently failing. This caused the push events to fail.
This is because of the codecov token requirements as mentioned in the comment. 
* Why these changes are required? Codecov failures on main
* What is the old behavior before changes and new behavior after changes? Codecov failures on main
N/A
Testing on GHA, will verify on the push event after merging …
=> Only run codecov on pr

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/metadata.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_metadata.py
Fix extra args command parsing used by Metadata migration
Added a new test case that validates all the end cases 
=> Fix extra args command parsing used by Metadata migration

MetadataMigration/src/main/java/org/opensearch/migrations/MetadataArgs.java
Metadata migration requires a default version parameter just like RFS when reading from snapshot.  RFS was defaulting to ES 7.10, doing the same for metadata tool.
- Resolves https://opensearch.atlassian.net/browse/MIGRATIONS-1995
=> Add default source version for metadata migration

.github/workflows/CI.yml, DocumentsFromSnapshotMigration/src/test/java/com/rfs/PerformanceVerificationTest.java, TrafficCapture/README.md, settings.gradle
Update gradle scan plugin to 3.18 giving new features such as performance introspection which will help identify resource utilization.
* Why these changes are required? 
* What is the old behavior before changes and new behavior after changes? Scan was missing features that are now present.
N/A
=> Update gradle scan plugin

build.gradle
When running full test suites printing all the output to std out blows out the console window and overloads the github action logs.  All this data is still avaliable in the junit reports that can be downloaded from the GitHub actions or avaliable in
`${project.dir}/build/reports/tests/...`
- Related https://github.com/opensearch-project/opensearch-migrations/pull/928
I consulted the most recent build [1] after downloading the job logs, the gradle check was _600mb_, and this was truncated by GitHubs systems.
Doing the same check on [2] which was before the unified CC job, the gradle check was _277kb_.
- [1] https://github.com/opensearch-project/opensearch-migrations/actions/runs/10800784819/job/29959542405
- [2] https://github.com/opensearch-project/opensearch-migrations/actions/runs/107457 …
=> Reduce gradle test output from +599 MB -> 300kb

MetadataMigration/src/main/java/org/opensearch/migrations/cli/Items.java, MetadataMigration/src/main/java/org/opensearch/migrations/commands/Migrate.java, MetadataMigration/src/test/java/org/opensearch/migrations/EndToEndTest.java, RFS/src/main/java/com/rfs/worker/IndexMetadataResults.java, RFS/src/main/java/com/rfs/worker/IndexRunner.java, RFS/src/testFixtures/java/com/rfs/http/ClusterOperations.java
Add aliases to the metadata migration output
- Updated end to end test verification
```
Clusters:
Source:
Snapshot: Elasticsearch 6.8.23 FileSystemRepo(repoRootDir=/tmp/junit1212427663916343992)
Target:
Remote Cluster: OpenSearch 2.14.0 ConnectionContext(uri=http://localhost:32911, protocol=HTTP, insecure=false, compressionSupported=false)
Migrated Items:
Index Templates:
simple_index_template
Component Templates:
<NONE FOUND>
Indexes:
blog_2023, movies_2023
Aliases:
alias1, movies-alias
Results:
0 issue(s) detected
```
- Resolves https://opensearch.atlassian.net/browse/MIGRATIONS-1997
- Related https://opensearch.atlassian.net/browse/MIGRATIONS-1867
For more information on …
=> Add aliases to the metadata migration output

deployment/cdk/opensearch-service-migration/lib/common-utilities.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-console-stack.ts
- bug fix for source cluster permissions when configured with a password in a secret
- bug fix to ensure sigv4 auth outputs a valid services.yaml
=> Source password secret permssions + sigv4 yaml fixes

DocumentsFromSnapshotMigration/src/main/java/com/rfs/RfsMigrateDocuments.java, DocumentsFromSnapshotMigration/src/test/java/com/rfs/PerformanceVerificationTest.java, DocumentsFromSnapshotMigration/src/test/java/com/rfs/SourceTestBase.java, RFS/build.gradle, RFS/src/main/java/com/rfs/common/DocumentReindexer.java, RFS/src/main/java/com/rfs/common/LuceneDocumentsReader.java, RFS/src/main/java/com/rfs/common/RfsLuceneDocument.java, RFS/src/main/java/com/rfs/worker/DocumentsRunner.java, RFS/src/test/java/com/rfs/common/DocumentReindexerTest.java, RFS/src/test/java/com/rfs/common/LuceneDocumentsReaderTest.java, commonDependencyVersionConstraints/build.gradle
* This change enables reading Lucene indices v6+ by upgrading RFS to use Lucene 9 and leveraging the backwards compatibility codecs embedded in that release.
* Add a new test for the LuceneDocumentsReader that ensures it's able to read an ES 6.8 snapshot whose indices were created in ES 5.X
* Updated unit tests elsewhere in the code where necessary
* https://opensearch.atlassian.net/browse/MIGRATIONS-1965
Unit tests; manually running RFS against a Snapshot created in ES 5 and upgraded to ES 6
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING …
=> "Back to the Future" - Upgrading to Lucene 9 to read Lucene 6

CreateSnapshot/src/test/resources/log4j2.properties, DocumentsFromSnapshotMigration/src/test/resources/log4j2.properties, MetadataMigration/src/test/resources/log4j2.properties, RFS/src/test/resources/log4j2.properties, TrafficCapture/captureKafkaOffloader/src/test/resources/log4j2.properties, TrafficCapture/captureOffloader/src/test/resources/log4j2.properties, TrafficCapture/nettyWireLogging/src/test/resources/log4j2.properties, TrafficCapture/trafficCaptureProxyServer/src/test/resources/log4j2.properties, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/ExhaustiveCapturedTrafficToHttpTransactionAccumulatorTest.java, TrafficCapture/trafficReplayer/src/test/resources/log4j2.properties, TrafficCapture/transformationPlugins/jsonMessageTransformers/jsonJMESPathMessageTransformerProvider/src/test/resources/log4j2.properties, TrafficCapture/transformationPlugins/jsonMessageTransformers/jsonJoltMessageTransformerProvider/src/test/resources/log4j2.properties, TrafficCapture/transformationPlugins/jsonMessageTransformers/openSearch23PlusTargetTransformerProvider/src/test/resources/log4j2.properties, awsUtilities/src/test/resources/log4j2.properties, build.gradle, coreUtilities/src/test/resources/log4j2.properties, dashboardsSanitizer/src/test/resources/log4j2.properties
Enable trace logging during `./gradlew test`, and debug logging for slowTests.
Enables unit tests to execute code paths at trace logging which were otherwise unexecuted.
Adds system property `migrationLogLevel` which controls the test logging level
Retains existing test logging level when `migrationLogLevel` is not provided
Note: Changed `status = ERROR` in test log4j2 to WARN in order to identify misconfigurations in log4j2 properties 
Unified appender.console.layout.pattern across across the packages for consistent timestamp and formatting
* Category: Test Fix
* Why these changes are required? Enable unit tests to cover branches in trace/debug logging
* What is the old behavior before changes and new behavior after changes? Only changes to test log4j2 properties and behavior. Some tests …
=> Enable trace/debug logging during test/slowTest

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/cli.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/environment.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/middleware/kafka.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_cli.py
Test Coverage PR #1 of the day.
These tests bring the overall `console_link` uncovered lines from 378 to 330.
=> Improve migration console cli.py test coverage

RFS/src/test/java/com/rfs/cms/WorkCoordinatorTest.java, RFS/src/testFixtures/java/com/rfs/framework/SearchClusterContainer.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/http/retries/HttpRetryTest.java
Extend acceptible docker container startup time in tests to 5 minutes from the default 1 minute.
* Category:  Test fix
* Why these changes are required? Make tests more reliable on hosts with more parallelization
* What is the old behavior before changes and new behavior after changes? Sometimes this would fail when run in parallel on larger hosts (8vcpu)
Fix issue:
```
WorkCoordinatorTest > testAcquireLeaseHasNoUnnecessaryConflicts() FAILED
4241 | org.testcontainers.containers.ContainerLaunchException: Container startup failed for image opensearchproject/opensearch:1.3.16
4242 | at app//org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:359)
4243 | at app//org.testcontainers.containers.GenericContainer.start(GenericContainer.java:330)
4244 | at …
```
=> Extend acceptable docker container startup time in tests

MetadataMigration/build.gradle, MetadataMigration/src/main/java/org/opensearch/migrations/MetadataMigration.java, MetadataMigration/src/main/java/org/opensearch/migrations/cli/ClusterReaderExtractor.java, MetadataMigration/src/main/java/org/opensearch/migrations/cli/Clusters.java, MetadataMigration/src/main/java/org/opensearch/migrations/cli/Format.java, MetadataMigration/src/main/java/org/opensearch/migrations/cli/Items.java, MetadataMigration/src/main/java/org/opensearch/migrations/commands/Configure.java, MetadataMigration/src/main/java/org/opensearch/migrations/commands/ConfigureResult.java, MetadataMigration/src/main/java/org/opensearch/migrations/commands/EvaluateResult.java, MetadataMigration/src/main/java/org/opensearch/migrations/commands/MigrateResult.java, MetadataMigration/src/main/java/org/opensearch/migrations/commands/MigrationItemResult.java, MetadataMigration/src/main/java/org/opensearch/migrations/commands/Result.java, MetadataMigration/src/test/java/org/opensearch/migrations/MetadataMigrationTest.java, MetadataMigration/src/test/java/org/opensearch/migrations/cli/ClusterReaderExtractorTest.java, MetadataMigration/src/test/java/org/opensearch/migrations/cli/ClustersTest.java, MetadataMigration/src/test/java/org/opensearch/migrations/cli/ItemsTest.java, MetadataMigration/src/test/java/org/opensearch/migrations/commands/MigrationItemResultTest.java, RFS/src/main/java/com/rfs/common/http/ConnectionContext.java, testHelperFixtures/build.gradle, testHelperFixtures/src/testFixtures/java/org/opensearch/migrations/matchers/ContainsStringCount.java, testHelperFixtures/src/testFixtures/java/org/opensearch/migrations/matchers/HasLineCount.java
Fix code smells in Metadata Cli
- Reduce access on fields and make final
- Create indentation function to ensure consistant output, reduce duplicate logic
- Improve code coverage on command line parsing code
- Bonus fix bugs where some error messages were not being thrown
- Related https://opensearch.atlassian.net/browse/MIGRATIONS-2004
=> Fix code smells in Metadata Cli

TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/proxyserver/testcontainers/HttpdContainerTestBase.java, TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/proxyserver/testcontainers/KafkaContainerTestBase.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/PruferTreeGeneratorTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/e2etests/KafkaRestartingTrafficReplayerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/http/retries/HttpRetryTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/kafka/KafkaCommitsWorkBetweenLongPollsTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/kafka/KafkaKeepAliveTests.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/kafka/KafkaTrafficCaptureSourceLongTermTest.java, testHelperFixtures/src/testFixtures/java/org/opensearch/migrations/testutils/SharedDockerImageNames.java
The other tests use kafka version 7.5.0 so aligning it here.
* Why these changes are required? Reduce number of docker pulls
* What is the old behavior before changes and new behavior after changes? Different version could be used
N/A
GHA
=> Use Same Kafka Version

TrafficCapture/captureOffloader/src/main/java/org/opensearch/migrations/trafficcapture/StreamChannelConnectionCaptureSerializer.java
Resolve some sonar lint issues in captureOffloader
* Why these changes are required? SonarLint Issues
* What is the old behavior before changes and new behavior after changes? No behavior changes
https://opensearch.atlassian.net/browse/MIGRATIONS-2015
Ran SonarQube locally, resolved all issues except FileConnectionCaptureFactory deprecation notice.
=> Resolve some sonar lint issues in captureOffloader

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/Dockerfile
When I started up the migration console from I notice that I was getting an error message instead of the welcome message, I believe that I spaced when adding the echo command - `@echo` is a windows thing.  
Verified locally with ` ./gradlew TrafficCapture:dockerSolution:composeUp`, here is the output:
```shell
ubuntu@ip-172-31-18-157:~/git/opensearch-migrations$ docker exec -i -t $(docker ps -aqf "ancestor=migrations/migration_console:latest") /bin/bash
Welcome to the Migration Assistant Console
(.venv) bash-5.2# 
``` …
=> Ensure the migration console welcome message appears correctly

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/cli.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/snapshot.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_cli.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_snapshot.py
1. Code coverage 💪 So far, this resolves another 33 uncovered lines with a combo of deleting unused code & adding tests.
2. Passes any extra args submitted with `snapshot create` through to the underlying `subprocess.run` call (and therefore to the java snapshot tool). This is a prereq for allowing filtered snapshots (only certain indices, etc.).
Sonarqube
=> [Console] Test Coverage & `snapshot create` passes through extra args

deployment/cdk/opensearch-service-migration/default-values.json
Bug fix for invalid default-values
```
SyntaxError: /home/ec2-user/workspace/rfs-default-e2e-test/deployment/cdk/opensearch-service-migration/default-values.json: Unexpected token } in JSON at position 482
at parse (<anonymous>)
at Object.Module._extensions..json (node:internal/modules/cjs/loader:1440:39)
at Module.load (node:internal/modules/cjs/loader:1203:32)
at Function.Module._load (node:internal/modules/cjs/loader:1019:12)
at Module.require (node:internal/modules/cjs/loader:1231:19)
at require (node:internal/modules/helpers:177:18)
at Object.<anonymous> (/home/ec2-user/workspace/rfs-default-e2e-test/deployment/cdk/opensearch-service-migration/lib/stack-composer.ts:6:1)
at Module._compile (node:internal/modules/cjs/loader:1364:14)
at Module.m._compile …
```
=> [Bug] Fix invalid character in default-values

TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/http/retries/OpenSearchDefaultRetry.java
One liner to quiet down the logs
=> Reduce verbosity to trace for parsing bulk responses when determining to retry or not

RFS/src/main/java/org/opensearch/migrations/bulkload/common/OpenSearchClient.java, RFS/src/test/java/org/opensearch/migrations/bulkload/common/OpenSearchClientTest.java
Fix double trailing slash in getClusterVersion since rest client was adding "/" which was causing 400 Bad Request in AWS against OS 2.15 (Note, was not causing issues in containers or other versions) 
Bug Introduced in #922 
* Why these changes are required? AWS Opensearch Service Support
* What is the old behavior before changes and new behavior after changes? Any Metadata Migrations to AWS Opensearch Service failed for this getVersionCall since #922 
Testing in AWS and unit tests added
For more information on following Developer Certificate of Origin and signing off your commits, please …
=> Fix metadata migrate get version

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/cli.py
* Made it clearer to use the `--refresh` option with `cat-indices` to get up-to-date results
* N/A
```
(.venv) bash-5.2# console clusters cat-indices
WARNING: Cluster information may be stale. Use --refresh to update.
SOURCE CLUSTER
health status index                uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   test_updates_deletes -DqPQDrATw25hhe5Ss34bQ   1   0          3            0     12.7kb         12.7kb
TARGET CLUSTER
health status index                     uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   .opensearch-observability 8HOComzdSlSWCwqWIOGRbQ   1   1          0            0       416b           208b
green  open   .plugins-ml-config        9tld-PCJToSUsMiyDhlyhQ   5   1 …
```
=> Updated `console cluster cat-indices` to warn when you don't refresh

RFS/src/main/java/org/opensearch/migrations/bulkload/common/InvalidResponse.java
* Per the title, removing some greedy matching to mitigate DOS concern
* https://tiny.amazon.com/wtrxh53p/sonar
* Ran the existing unit tests
=> Removed greedy matching from a regex to address DOS concern.

deployment/cdk/opensearch-service-migration/lib/common-utilities.ts, deployment/cdk/opensearch-service-migration/lib/network-stack.ts, deployment/cdk/opensearch-service-migration/lib/stack-composer.ts, deployment/cdk/opensearch-service-migration/test/network-stack.test.ts
Remove public communication from migration assistant services by removing VPC and declaring VPCe's for all services.
* Why these changes are required? Cost and Security requirements
* What is the old behavior before changes and new behavior after changes? Communication went through nat gateway
https://opensearch.atlassian.net/browse/MIGRATIONS-1969
Deployed and ran migration console commands in us-east-1 and us-gov-west-1 …
=> Add VPCe for all aws services

TrafficCapture/dockerSolution/otelConfigs/consConfigSnippets.py
Tiny little sonarqube code smell for variable naming.
n/a
=> Rename `consConfigSnippets` camelcase vars

deployment/cdk/opensearch-service-migration/cdk.context.json, deployment/cdk/opensearch-service-migration/default-values.json
=> Set explicit defaults w/ placeholders in the cdk.context.json

deployment/cdk/opensearch-service-migration/cdk.context.json, test/defaultMigrationContext.json, vars/rfsDefaultE2ETest.groovy, vars/trafficReplayDefaultE2ETest.groovy
My last PR, #1021, broke the build.  Having a not-quite-json `cdk.context.json` was bad anytime a `cdk` command was used, _even_ if it specifically specified a different context file.
So first, I just made it valid (if kind of ugly) JSON, but that broke the build in a different way because removing a lot of the default values changed the behavior of the cdk deployments in the CI pipelines. I copied the old values from the defaults into these blocks and have tested redeploying, successfully now.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTI …
=> Make cdk.context.json valid json

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/cli.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/middleware/snapshot.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_cli.py
We had `snapshot delete` implemented in the backend, but not extended to the CLI.
Added a cli-level test.
=> Add snapshot delete to cli

CreateSnapshot/src/main/java/org/opensearch/migrations/CreateSnapshot.java, DocumentsFromSnapshotMigration/src/main/java/org/opensearch/migrations/RfsMigrateDocuments.java, MetadataMigration/src/main/java/org/opensearch/migrations/MetadataMigration.java, MetadataMigration/src/test/java/org/opensearch/migrations/MetadataMigrationTest.java
CreateSnapshot, DocumentsFromSnapshotMigration, and MetadataMigration printed args which could contain secret value password
* Why these changes are required? Password could be printed in plaintext
* What is the old behavior before changes and new behavior after changes? Password could be printed in plaintext
N/A
=> Remove arg printing from command line apps with secret values

DocumentsFromSnapshotMigration/docker/entrypoint.sh, TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/CaptureProxy.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayer.java, coreUtilities/build.gradle, coreUtilities/src/main/java/org/opensearch/migrations/jcommander/NoSplitter.java, deployment/cdk/opensearch-service-migration/lib/common-utilities.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/capture-proxy-es-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/capture-proxy-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-console-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/reindex-from-snapshot-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/traffic-replayer-stack.ts, deployment/cdk/opensearch-service-migration/options.md, deployment/cdk/opensearch-service-migration/package-lock.json, deployment/cdk/opensearch-service-migration/package.json, deployment/cdk/opensearch-service-migration/test/common-utilities.test.ts, deployment/cdk/opensearch-service-migration/test/reindex-from-snapshot-stack.test.ts
Simplify CDK ExtraArg processing to remove yargs and make more robust.
Fixed places where parameter values which may have spaces weren't wrapped in quotes.
Removed cdk dependency on yargs
Fixed an issue where List arguments would split on `,` incorrectly e.g. `--setHeader name "value1,value2"`
Fixed an issue where ExtraArgs wouldn't correctly handle multi arity commands e.g. `--setHeader name value`
Fixed a bug in how user supplied plaintext password was being supplied to the replayer
* Why these changes are required? Currently --setHeader in extraArgs is broken along with special characters in the values.
* What is the old behavior before changes and new behavior after changes? CaptureProxy could crash on  startup with otherwise valid arguments. …
=> Update argument parsing to remove dependency on yargs and make more robust

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/middleware/clusters.py
There's a bug in our sigv4 dependency for `requests` that breaks when a url has a query param with no value. So `?v` fails but `?v=true` succeeds.
https://opensearch.atlassian.net/browse/MIGRATIONS-2023
Manual
=> ?v -> ?v=true to workaround the sigv4 bug

deployment/cdk/opensearch-service-migration/cdk.context.json, deployment/cdk/opensearch-service-migration/lib/common-utilities.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-console-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-service-core.ts, deployment/cdk/opensearch-service-migration/lib/stack-composer.ts, deployment/cdk/opensearch-service-migration/options.md
We discovered that our existing CDK is not sufficient for taking a snapshot of a managed service source cluster. A specific snapshot role must be created, and there needs to be a trust relationship between the console task role and this snapshot role that allows it to be passed.
With this PR, if `managedServiceSourceSnapshotEnabled` is added to the `cdk.context` as `true`, it sets up these roles and relationships.
In this PR, it **does not** handle adding the relevant role arn to the services.yaml and passing it through automatically.  That would be an excellent follow-up, but in this case I'm trying to focus on _unblocking_ the particularly time-confusing and messy parts instead of making this a fully supported experience.
One of the caveats is that, to pass in the snapshot role, the …
=> Add option to take a snapshot of a managed service source cluster

SECURITY.md
It came up in PE review that we don't support customer managed keys within the migration infrastructure. Adding a note about it to the SECURITY.md caveats section.
=> Add note about not supporting customer managed keys

RFS/src/main/java/org/opensearch/migrations/bulkload/common/InvalidResponse.java
Rather than using a backtracking pattern which could have performance impact, switch to using explict character ranges which work for json path seperated with periods.
Mitigates sonar lint rule java:S5852 [1]
- [1] https://rules.sonarsource.com/java/RSPEC-5852/?search=Using%20slow%20regular%20expressions%20is%20security-sensitive
=> Optimize the regex parser for InvalidResponse

CreateSnapshot/build.gradle, DocumentsFromSnapshotMigration/build.gradle, MetadataMigration/build.gradle, RFS/build.gradle, TrafficCapture/captureKafkaOffloader/build.gradle, TrafficCapture/captureOffloader/build.gradle, TrafficCapture/captureProtobufs/build.gradle, TrafficCapture/nettyWireLogging/build.gradle, TrafficCapture/trafficCaptureProxyServer/build.gradle, TrafficCapture/trafficCaptureProxyServerTest/build.gradle, TrafficCapture/trafficReplayer/build.gradle, TrafficCapture/transformationPlugins/jsonMessageTransformers/jsonJoltMessageTransformer/build.gradle, TrafficCapture/transformationPlugins/jsonMessageTransformers/jsonMessageTransformerInterface/build.gradle, awsUtilities/build.gradle, build.gradle, coreUtilities/build.gradle, dashboardsSanitizer/build.gradle, testHelperFixtures/build.gradle, transformation/build.gradle
Apply dependency overrides to all dependency types
* Category: Fixes dependency versions across all compile types
* Why these changes are required? Protobuf wasn't using a consistent version 
* What is the old behavior before changes and new behavior after changes? Annotation processing depended on protobuf 2.19 instead of current 2.25
GHA, verified dependency versions with `./gradlew <task>:dependencies` …
=> Apply dependency overrides to all dependency types

deployment/cdk/opensearch-service-migration/cdk.context.json, deployment/cdk/opensearch-service-migration/default-values.json, deployment/cdk/opensearch-service-migration/lib/network-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-service-core.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/reindex-from-snapshot-stack.ts, deployment/cdk/opensearch-service-migration/lib/stack-composer.ts, deployment/cdk/opensearch-service-migration/options.md, deployment/cdk/opensearch-service-migration/test/reindex-from-snapshot-stack.test.ts
* Updated the RFS Workers to use an EBS volume to store and unpack the snapshot.  Each worker gets a separate volume, which is provisioned on task launch.
* https://opensearch.atlassian.net/browse/MIGRATIONS-1750
* Tested by performing a small migration in AWS and confirming separate, correctly-size volumes were used for each task
```
(.venv) bash-5.2# console clusters cat-indices
SOURCE CLUSTER
health status index       uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   bwc_index_1 QYzCFpW9RTeZ9xW3ht5eTA   1   0          1            0      3.8kb          3.8kb
green  open   fwc_index_1 Axns2r74RCiDQYt6ewLAeQ   1   0          1            0      3.8kb          3.8kb
TARGET CLUSTER
health status index                     uuid …
```
=> RFS Workers now use EBS to store/unpack the snapshot

build.gradle, deployment/cdk/opensearch-service-migration/cdk.json, deployment/cdk/opensearch-service-migration/tsconfig.json
This ensures that our json files are valid and follow common formatting conventions.
- Related https://github.com/opensearch-project/opensearch-migrations/pull/1022
=> Add spotless formatting rules for json files

DocumentsFromSnapshotMigration/docker/entrypoint.sh, DocumentsFromSnapshotMigration/src/main/java/org/opensearch/migrations/RfsMigrateDocuments.java, DocumentsFromSnapshotMigration/src/test/java/org/opensearch/migrations/bulkload/ProcessLifecycleTest.java, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/integ_test/backfill_tests.py
Unsuccessful means anything but a 0 exit code.  The application has been cleaned up to return 3 for no work available.  It used to return whatever a top-level exception would create.  That part wasn't necessary, but it seemed like a good idea to test for that to make sure that after running repeatedly, processes would eventually do THAT instead of returning 0, causing infinite loops in the containers.
This eliminates container startup costs while still cleaning out the java process so that we don't have to worry about runaway processes.
* Category Enhancement
* Why these changes are required? For clusters with very small indices, migrations could take a very long time. since every tiny shard would need to create a new container.  That should be drastically reduced now (~100x ?). …
=> Run the RFS Container's DocumentMigration application repeatedly as long as it's successful

jenkins/migrationIntegPipelines/cleanupDeploymentCover.groovy, test/cleanupDeployment/Pipfile, test/cleanupDeployment/Pipfile.lock, test/cleanupDeployment/README.md, test/cleanupDeployment/cleanup_deployment.py, vars/cleanupDeployment.groovy
Adds logic for deleting our CFN stacks across two CDK packages we currently use (this projects CDK and sample EC2 source CDK). This logic can be used locally with python, but is also included as a Jenkins pipeline in this change to allow manually deleting an environment as well as scheduled deletion of environments.
https://opensearch.atlassian.net/browse/MIGRATIONS-2054
Local testing and Jenkins: https://migrations.ci.opensearch.org/job/delete-environment/11/console
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate- …
=> [Jenkins] Add delete environment pipeline

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/integ_test/backfill_tests_es68.py, jenkins/migrationIntegPipelines/rfsES68SourceE2ETestCover.groovy, vars/rfsES68SourceE2ETest.groovy
Added a simple integ test exercising the user workflow for RFS from an ES 6.8 source.
* https://opensearch.atlassian.net/browse/MIGRATIONS-1956
* Here's an Jenkins run demonstrating the new Pipeline
* https://migrations.ci.opensearch.org/job/rfs-es68source-e2e-test/14/console
=> Added a simple, single document RFS ES 6.8 Jenkins Integ Test

docs/migration-console.md
Remove AWS service reference.
None
N/A
- [ x] Commits are signed per the DCO using --signoff
=> Remove reference to DMS

commonDependencyVersionConstraints/build.gradle
[CVE] Update snappy-java from 1.1.10.4 -> 1.1.10.6
See full list of CVEs on advisories for the 2.0.1 release [1].
- https://advisories.opensearch.org/vulnerabilities/OpenSearch%20Migrations/2.0.1
=> [CVE] Update snappy-java from 1.1.10.4 -> 1.1.10.6

.github/workflows/CI.yml, DocumentsFromSnapshotMigration/build.gradle, TrafficCapture/dockerSolution/build.gradle, TrafficCapture/dockerSolution/src/main/docker/captureProxyBase/Dockerfile, TrafficCapture/dockerSolution/src/main/docker/composeExtensions/proxy-multi.yml, TrafficCapture/dockerSolution/src/main/docker/composeExtensions/proxy-single.yml, TrafficCapture/trafficCaptureProxyServerTest/build.gradle, TrafficCapture/trafficCaptureProxyServerTest/src/main/docker/docker-compose.yml, buildSrc/src/main/groovy/org/opensearch/migrations/common/CommonUtils.groovy, deployment/cdk/opensearch-service-migration/cdk.context.json, deployment/cdk/opensearch-service-migration/lib/common-utilities.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/capture-proxy-es-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/capture-proxy-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/elasticsearch-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/kafka-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-console-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-service-core.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/opensearch-container-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/reindex-from-snapshot-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/traffic-replayer-stack.ts, deployment/cdk/opensearch-service-migration/package.json, deployment/cdk/opensearch-service-migration/test/migration-console-stack.test.ts, deployment/cdk/opensearch-service-migration/test/migration-services-yaml.test.ts, deployment/cdk/opensearch-service-migration/test/network-stack.test.ts, deployment/cdk/opensearch-service-migration/test/opensearch-domain-stack.test.ts, deployment/cdk/opensearch-service-migration/test/reindex-from-snapshot-stack.test.ts, deployment/cdk/opensearch-service-migration/test/stack-composer-ordering.test.ts, deployment/cdk/opensearch-service-migration/test/stack-composer.test.ts
Currently, the capture proxy container image builds on the es base image. This is not needed for running the capture proxy independently. This change modifies this base image to use AL2023.
This change uses a multi-staged build to generate the certs with openssl without including it in the final image.
Other Changes:
* Cleaned up how cdk references docker images (uses local tag instead of rebuilding from final build directory)
* Cleaned up how migration console is being built, made more robust by using dedicated build directory instead of the source directory and fixed it erroneously being built
* Fixed TrafficCaptureProxyServerTest dockerImageBuild by explicitly declaring dependencies 
___
* Why these changes are required? Increased security 
* What is the old …
=> Remove elasticsearch from default capture proxy base image

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/console_api/Pipfile.lock, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/Pipfile, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/Pipfile.lock, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/cluster.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/utils.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/setup.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_cluster.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/Pipfile.lock
Replace requests-auth-aws-sigv4 with boto3 signing
* Why these changes are required? better security with sigv4 by using trusted library and bug fixes
* What is the old behavior before changes and new behavior after changes? Some calls would fail that included `?v` or `*` in url
[MIGRATIONS-2099](https://opensearch.atlassian.net/browse/MIGRATIONS-2099)
Added unit tests
Tested locally against an aws cluster with sigv4
```
(.venv) bash-5.2# console clusters clear-indices --cluster target --acknowledge-risk
Performing clear indices operation...
```
```
(.venv) bash-5.2# console clusters curl -XGET target_cluster /_cat/indices?v
health status index                     uuid                   pri rep …
```
=> Replace requests-auth-aws-sigv4 with boto3 signing

build.gradle
With the change that added the commonDependencyConstraints package, we need to add propagating to the maven pom files to better enable dependency resolution during importing.
Before
```
<dependencies>
<dependency>
<groupId>software.amazon.awssdk</groupId>
<artifactId>arns</artifactId>
<scope>runtime</scope>
</dependency>
<dependency>
<groupId>software.amazon.awssdk</groupId>
<artifactId>auth</artifactId>
<scope>runtime</scope>
</dependency>
<dependency>
<groupId>software.amazon.awssdk</groupId>
<artifactId>sdk-core</artifactId>
<scope>runtime</scope>
</dependency>
<dependency>
```
After
In the pom file:
```
<dependencyManagement>
<dependencies>
<dependency>
<groupId>org.apache.commons</groupId>
<artifactId>commons-text</artifactId>
<version>1.10.0</version>
</dependency>
</dependencies> …
```
=> Include versions in maven publish

deployment/cdk/opensearch-service-migration/default-values.json, deployment/cdk/opensearch-service-migration/lib/common-utilities.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/reindex-from-snapshot-stack.ts, deployment/cdk/opensearch-service-migration/lib/stack-composer.ts, deployment/cdk/opensearch-service-migration/options.md, deployment/cdk/opensearch-service-migration/test/default-values-test.json, deployment/cdk/opensearch-service-migration/test/reindex-from-snapshot-stack.test.ts
Added an RFS High Performance Mode that does the following:
* Increases EBS Throughput for faster s3 download and extract
* Increases worker size to 16vCPU 32GB
* Sets max concurrent requests to 100
* Enables Target Compression
With these settings, i was able to use 5 workers to migrate a 5 shard source where each source shard was 1.9TiB (9.2TiB total) in 7 hours with a target cluster composed of 10 r7gd.16xlarge data nodes (Increased target index shard count to 400).
Also improved the UX by adding a buffer on max shard size which can reduce friction when shards are slightly uneven and a customer calculated their max shard size by taking primary size / shards.
Also fixed a bug in imageHash for builds with "docker-compatible" clients like podman when image Id just returns the hash and not …
=> Add reindexFromSnapshotWorkerSize to cdk with default and maximum modes

DataGenerator/src/main/java/org/opensearch/migrations/data/FieldBuilders.java, DataGenerator/src/main/java/org/opensearch/migrations/data/IndexOptions.java, DataGenerator/src/main/java/org/opensearch/migrations/data/RandomDataBuilders.java, DataGenerator/src/main/java/org/opensearch/migrations/data/WorkloadOptions.java, DataGenerator/src/main/java/org/opensearch/migrations/data/workloads/Geonames.java, DataGenerator/src/main/java/org/opensearch/migrations/data/workloads/HttpLogs.java, DataGenerator/src/main/java/org/opensearch/migrations/data/workloads/Nested.java, DataGenerator/src/main/java/org/opensearch/migrations/data/workloads/NycTaxis.java
Address code smells in DataGenerator
- Defined constants for reused literals
- Mark unmodified fields final
- Add a private constructor to hide the implicit public constructor
=> Address code smells in DataGenerator

build.gradle
Remove unspecified dependencies in maven pom publishing
We were having one dependency that was unspecified opentelemetry-testing because it was only used in a testFixtures and wasn't in the resolution classpath. Fixed that and added a check before publishing that all versions are specified.
* Why these changes are required? Usable Maven Pom files
* What is the old behavior before changes and new behavior after changes? opentelemetry-testing didn't include a version
N/A
ran `./gradlew publishToMavenLocal`
For more information on following Developer Certificate of Origin and signing off …
=> Remove unspecified dependencies in maven pom publishing

DocumentsFromSnapshotMigration/src/main/java/org/opensearch/migrations/RfsMigrateDocuments.java, RFS/src/main/java/org/opensearch/migrations/bulkload/workcoordination/IWorkCoordinator.java, RFS/src/main/java/org/opensearch/migrations/bulkload/workcoordination/OpenSearchWorkCoordinator.java, RFS/src/test/java/org/opensearch/migrations/bulkload/workcoordination/WorkCoordinatorTest.java
The `numWorkItemsArePending` function had a parameter for maximum results, but if that field was set to `-1` (intended to be no maximum), it just wasn't set in the API call, which actually meant that it defaulted to a max of 10.
There was also a note in the function about switching it to use `_count`, and that was an easy way to fix the bug. The max results param was no longer relevant, so I removed it.
n/a
This being broken was breaking a different test, so fixing it has made that test pass.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING …
=> Fix numWorkItemsArePending bug

.github/workflows/CI.yml, deployment/README.md, deployment/migration-assistant-solution/.gitignore, deployment/migration-assistant-solution/.npmignore, deployment/migration-assistant-solution/README.md, deployment/migration-assistant-solution/bin/app.ts, deployment/migration-assistant-solution/cdk.json, deployment/migration-assistant-solution/eslint.config.mjs, deployment/migration-assistant-solution/index.ts, deployment/migration-assistant-solution/initBootstrap.sh, deployment/migration-assistant-solution/jest.config.js, deployment/migration-assistant-solution/lib/solutions-stack.ts, deployment/migration-assistant-solution/package-lock.json, deployment/migration-assistant-solution/package.json, deployment/migration-assistant-solution/test/solutions-stack.test.ts, deployment/migration-assistant-solution/tsconfig.json
The existing AWS Solutions template is in a GitHub repo [GitHub - aws-solutions/migration-assistant-for-amazon-opensearch: Upgrade, Migrate, and Compare OpenSearch Clusters](https://github.com/aws-solutions/migration-assistant-for-amazon-opensearch) but isn’t used for performing updates.
With ongoing efforts to improve deployment speed, having the solutions deployment inside of the OpenSearch-Migration GitHub repo makes coordinating cross stack references easier and creates a clear workflow for contribution.
- Open-source the AWS Solution CFN template source into the OpenSearch-Migration GitHub repository. https://opensearch.atlassian.net/browse/MIGRATIONS-2154
For more …
=> Include AWS Solution cloud formation template

deployment/cdk/opensearch-service-migration/eslint.config.mjs, deployment/cdk/opensearch-service-migration/lib/cdk-logger.ts, deployment/cdk/opensearch-service-migration/lib/common-utilities.ts, deployment/cdk/opensearch-service-migration/lib/lambda/acm-cert-importer-handler.ts, deployment/cdk/opensearch-service-migration/lib/migration-services-yaml.ts, deployment/cdk/opensearch-service-migration/lib/network-stack.ts, deployment/cdk/opensearch-service-migration/lib/opensearch-domain-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/capture-proxy-es-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/capture-proxy-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/elasticsearch-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/kafka-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-console-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-otel-collector-sidecar.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-service-core.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/opensearch-container-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/reindex-from-snapshot-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/traffic-replayer-stack.ts, deployment/cdk/opensearch-service-migration/lib/stack-composer.ts, deployment/cdk/opensearch-service-migration/package-lock.json, deployment/cdk/opensearch-service-migration/package.json, deployment/cdk/opensearch-service-migration/test/createApp.test.ts, deployment/cdk/opensearch-service-migration/test/lambda/acm-cert-importer-handler.test.ts, deployment/cdk/opensearch-service-migration/test/migration-console-stack.test.ts, deployment/cdk/opensearch-service-migration/test/migration-services-yaml.test.ts, deployment/cdk/opensearch-service-migration/test/reindex-from-snapshot-stack.test.ts, deployment/cdk/opensearch-service-migration/test/stack-composer.test.ts, deployment/cdk/opensearch-service-migration/test/test-utils.ts
As ESLint to the migrations cdk stack
- Resolves https://opensearch.atlassian.net/browse/MIGRATIONS-2190 Add linter to the migration cdk stack
Ran `npm run test:lint` from the console, 
=> Add linter to the migration cdk stack

test/cleanupDeployment/cleanup_deployment.py
Bug fix for cleanup deployment to properly handle CFN list stacks giving paginated response
None created
Local testing
=> [Bug] Cleanup deployment fix for paginated list stacks

deployment/migration-assistant-solution/bin/app.ts, deployment/migration-assistant-solution/lib/solutions-stack.ts, deployment/migration-assistant-solution/package.json, deployment/migration-assistant-solution/test/solutions-stack.test.ts
Changes functionality to generate two CFN templates for create VPC and import VPC for bootstrap. As well as introduces VPC Id and Subnet intake from CFN parameters that will later be used when deploying the Migration Assistant CDK
https://opensearch.atlassian.net/browse/MIGRATIONS-2166
Manual CFN deployment testing
CDK tests
=> Generate two CFN templates for create VPC and import VPC for bootstrap

RFS/src/main/java/org/opensearch/migrations/bulkload/version_universal/RemoteReaderClient.java, RFS/src/testFixtures/java/org/opensearch/migrations/bulkload/framework/SearchClusterContainer.java
I encountered startup issues running the ES 6.8 image on apple silicon due to x-pack-ml.
Fixed encountered metadata issue when only a single template exists in the cluster. 
* Why these changes are required? We shouldn't depend on 6.8 x-pack in unit tests
* What is the old behavior before changes and new behavior after changes? Encountered failure `org.elasticsearch.bootstrap.StartupException: org.elasticsearch.bootstrap.BootstrapException: java.io.IOException: Cannot run program "/usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/controller": error=0, Failed to exec spawn helper: pid: 111, exit value: 1 at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163)` exiting container in test …
=> Update test ES 6.8 to use es-oss image

deployment/cdk/opensearch-service-migration/package-lock.json
In regards to https://github.com/advisories/GHSA-952p-6rrq-rcjv 
N/A
N/A
=> Bump micromatch from 4.0.7 to 4.0.8 in /deployment/cdk/opensearch-service-migration

RFS/src/main/java/org/opensearch/migrations/bulkload/common/OpenSearchClient.java, RFS/src/main/java/org/opensearch/migrations/bulkload/common/RestClient.java, RFS/src/main/java/org/opensearch/migrations/bulkload/common/http/ConnectionContext.java, RFS/src/test/java/org/opensearch/migrations/bulkload/common/OpenSearchClientTest.java, transformation/src/main/java/org/opensearch/migrations/Flavor.java, transformation/src/main/java/org/opensearch/migrations/Version.java, transformation/src/main/java/org/opensearch/migrations/VersionMatchers.java, transformation/src/test/java/org/opensearch/migrations/FlavorTest.java, transformation/src/test/java/org/opensearch/migrations/VersionTest.java
Adding automatic version detection that supports both flavors of the Amazon Managed OpenSearch and Serverless offerings.  Also detecting if combability mode has been enabled that will extract the version number from the `_cat/plugins` api, specifically looking at the `repository-s3` plugin.
- Resolves https://opensearch.atlassian.net/browse/MIGRATIONS-2187
Tested with both a managed and serverless cluster locally.
```
> ./gradlew MetadataMigration:run --args='evaluate --source-host https://search-target-domain-p5keoxlvhl5slkqgildik64mce.us-west-2.es.amazonaws.com/ --source-aws-region us-west-2 --source-aws-service-signing-name es --target-host https://vwpt0d13nhrsiinwng90.us-west-2.aoss.amazonaws.com/ --target-aws-region us-west-2 --target-aws-service-signing-name aoss'
> Task …
```
=> Auto detect target cluster version

.github/workflows/release-drafter.yml, DocumentsFromSnapshotMigration/docker/Dockerfile, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/Dockerfile, build.gradle, deployment/cdk/opensearch-service-migration/buildDockerImages.sh
Use Syft action to generate and output sbom alongside published artifacts.
Added license identifier to created jars.
* Why these changes are required? Users expect software boms with artifacts
Tested with GHA, see https://github.com/opensearch-project/opensearch-migrations/actions/runs/11713035148?pr=1121
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificat …
=> Generate and output sbom in GHA

.github/workflows/CI.yml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/Dockerfile, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/.coveragerc, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/.gitignore, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/Pipfile, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/Pipfile.lock, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/README.md, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/setup.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/src/cluster_tools/main.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/src/cluster_tools/utils.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/src/tools/change_shards.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/src/tools/create_index.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/src/tools/disable_compatibility_mode.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/src/tools/enable_compatibility_mode.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/tests/change_shards_test.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/tests/conftest.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/tests/create_index_test.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/tests/disable_compatibility_mode_test.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/tests/enable_compatibility_mode_test.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/tests/main_test.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/tests/utils.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/README.md, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/cli.py
Creates library cluster_tools for an easy to extend library of tools around opensearch business logic for migrations.
Ships with tools: create_index, change_shards, enable/disable_compatibility_mode
Was getting some codecov failures, added retry akin to [security repo](https://github.com/opensearch-project/security/blob/main/.github/workflows/ci.yml)
* Category: New feature
* Why these changes are required? Provide an easy-to-extend library of adhoc cluster manipulations
* What is the old behavior before changes and new behavior after changes? Library didn't exist
https://opensearch.atlassian.net/browse/MIGRATIONS-2201
Unit testing and some manual testing 
By submitting this pull request, I confirm that my contribution …
=> Cluster tools

MetadataMigration/src/test/java/org/opensearch/migrations/EndToEndTest.java, RFS/src/main/java/org/opensearch/migrations/bulkload/models/GlobalMetadata.java, RFS/src/main/java/org/opensearch/migrations/bulkload/transformers/Transformer_ES_7_10_OS_2_11.java, RFS/src/main/java/org/opensearch/migrations/bulkload/version_es_6_8/GlobalMetadataData_ES_6_8.java, RFS/src/main/java/org/opensearch/migrations/bulkload/version_es_7_10/GlobalMetadataData_ES_7_10.java, RFS/src/main/java/org/opensearch/migrations/bulkload/version_universal/RemoteMetadata.java, RFS/src/test/java/org/opensearch/migrations/bulkload/transformers/Transformer_ES_7_10_OS_2_11Test.java, RFS/src/testFixtures/java/org/opensearch/migrations/bulkload/http/ClusterOperations.java
Currently, legacy templates (created with `_template`) were only supported on ES 6. Since the API is deprecated and not removed, customers still use this type of template for ES 7 and above and it should be supported and tested.
This change mirrors the existing transformation logic that is in Index processing and applying to Legacy templates for ES7. E.g.
```
* Starting state:
* {
*   "mappings": [
*     {
*       "foo": {
*         "properties": {
*           "field1": { "type": "text" },
*           "field2": { "type": "keyword" }
*         }
*       }
*     }
*   ]
* }
*
* Ending state:
* {
*   "mappings": {
*     "properties": {
*       "field1": { "type": "text" },
*       "field2": { "type": "keyword" },
*     }
*   }
* }
``` …
=> Metadata Support ES7+ Legacy Templates

.github/workflows/CI.yml
Update pull request trigger to be "pull_request_target" which allows actions to access secrets needed for CODECOV_TOKEN.
Removed codecov retry since this was due to throttling when ran without tokens, the retry didn't help. Also added `verbose: true` to aid in any future debugging on codecov action.
See documentation: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflows-in-forked-repositories
Note: This will make changes to GHA workflows slightly more complicated, the GHA on the PR will run with the upstream branch workflow definition when triggered on a PR from a forked repository (a security feature). Instead we can push updates to a branch to verify, or temporarily update pull_request_target -> pull_request in a …
=> GHA trigger CI with pull_request_target for secrets access

.github/workflows/CI.yml, .github/workflows/release-drafter.yml
Update gradle-setup action to v4 to fix cache cleanup https://github.com/gradle/actions/issues/431
* Why these changes are required? Facing error in v3 `Cannot get the value of write-only property 'removeUnusedEntriesOlderThan' for object of type org.gradle.api.internal.cache.DefaultCacheConfigurations$DefaultCacheResourceConfiguration.`
* What is the old behavior before changes and new behavior after changes? ^
N/A
This PR is on a branch so the updated workflow is run …
=> Update gradle-setup action to v4 to fix cache cleanup

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/README.md, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/snapshot.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_snapshot.py, deployment/cdk/opensearch-service-migration/lib/migration-services-yaml.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-console-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-service-core.ts
Specifying 'managedServiceSourceSnapshotEnabled' in the cdk.context.json will now not just create the role for making a snapshot to s3, but it will add it to the services yaml file and the console will thread that through to the command line for snapshot create so that users don't have to.
* Category Enhancement
https://opensearch.atlassian.net/browse/MIGRATIONS-2001
Manual deployments w/ and without the cdk.context.json value and w/ and w/out the value in migration_services.yaml …
=> Capture the created role arn for snapshotting into the AWS yaml parameter and pass it through the command line

.github/workflows/CI.yml, .github/workflows/codecov-publish.yml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/console_api/Pipfile
Split codecov upload to separate github actions workflow.
This enables making the CI workflow trigger on `pull_request` as it will not need secret access making modifications much easier.
* Why these changes are required? Changes to the CI workflow are common to unblock the pipeline and it can impede PRs to make it pull_request_target
Lots of testing on my fork with push, pr, and pr from a fork.
E.g.: https://github.com/AndreKurait/opensearch-migrations/pull/7
For more …
=> Split codecov upload to separate github actions workflow

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_snapshot.py
* Category Cosmetic
* Why these changes are required? fix CI check
=> Style Linting: Placate Flake8 w/ more lines

deployment/cdk/opensearch-service-migration/lib/components/reindex-from-snapshot-dashboard.json, deployment/cdk/opensearch-service-migration/lib/service-stacks/reindex-from-snapshot-stack.ts
* Added a CloudWatch Dashboard for RFS that gets created when the RFS feature is enabled
* The Target Cluster section relies on having metrics provided by an Amazon OpenSearch Service domain to populate.  Additionally, the user must supply the name of their domain in the Dashboard.
* One quirk is the mechanic we're using to represent how many "active" RFS Workers there are.  We don't have a good way to represent the number of \*desired\* workers in a steady-state sense, so what we do is effectively report how many RFS Workers were alive in a given period by counting the number of separate instances of a CPU metric for our ECS containers.  During steady-state operation, we'd expect the metric in that graph to resemble closely the user's desired worker count.  However, if the workers are …
=> Added initial CloudWatch Dashboard for RFS

deployment/migration-assistant-solution/README.md, deployment/migration-assistant-solution/create-ami-map.sh, deployment/migration-assistant-solution/lib/solutions-stack.ts, deployment/migration-assistant-solution/test/solutions-stack.test.ts
With the current latest AL2023 image `al2023-ami-2023.6.20241111.0-kernel-6.1-x86_64` npm install hangs indefinitely.  We are switching back to an older version that works and providing a way to incrementally update to AMIs that we have tested.
- initBootstrap.sh hangs on npm install tasks https://opensearch.atlassian.net/browse/MIGRATIONS-2227
- Related https://github.com/amazonlinux/amazon-linux-2023/issues/840
Deployed the updated cloudformation manually and verified the build succeeds.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md …
=> Hardcode AMIs for use in the bootstrap machine

.github/workflows/codeql.yml, .github/workflows/sonar-qube.yml, sonar-project.properties
This repo has an asynchronous process where SonarQube rules are run several hours after code has merged.  This creates a life-cycle where code is reviewed approved and merged and then needs to be updated in a second PR.
This change introduces two new workflows to minimize the after-work required for changes in this repo, by running CodeQL which is built into GitHub for security risk detection and SonarQube with its set of issues based on security issues, code smells, and bug detectors.
These new workflows are being added without any fixes or adjustments to the codebase to be handled in an ongoing basis.
- SonarQube integration https://opensearch.atlassian.net/browse/MIGRATIONS-1803
See failed workflow step and annotations on the pull request.
By submitting this pull request, I confirm …
=> Add analysis workflows for SonarQube and CodeQL

deployment/migration-assistant-solution/bin/app.ts, deployment/migration-assistant-solution/lib/solutions-stack.ts, jenkins/migrationIntegPipelines/solutionsCFNTestCover.groovy, test/awsRunInitBootstrap.sh, vars/solutionsCFNTest.groovy
This change introduces a new Jenkins pipeline that synthesizes the Solutions Create VPC CFN template from this repository and deploys it to the test account. It will then perform the `initBootstrap` and ensure it exits properly as well as verifies that CLI tools such as cdk, docker, java, and python are now available on the box.
https://opensearch.atlassian.net/browse/MIGRATIONS-2228
Jenkins AWS testing
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certific …
=> [Jenkins] Add Solutions CFN Create VPC Test

DocumentsFromSnapshotMigration/src/test/java/org/opensearch/migrations/bulkload/EndToEndTest.java, RFS/src/main/java/org/opensearch/migrations/bulkload/common/BulkDocSection.java, RFS/src/main/java/org/opensearch/migrations/bulkload/common/DocumentReindexer.java, RFS/src/main/java/org/opensearch/migrations/bulkload/common/LuceneDocumentsReader.java, RFS/src/main/java/org/opensearch/migrations/bulkload/common/RfsLuceneDocument.java, RFS/src/test/java/org/opensearch/migrations/bulkload/common/BulkDocSectionTest.java, RFS/src/testFixtures/java/org/opensearch/migrations/bulkload/http/ClusterOperations.java, RFS/src/testFixtures/java/org/opensearch/migrations/bulkload/http/SearchClusterRequests.java
* Category - Bug Fix
* Why these changes are required? Not using routing from source breaks routing based queries on target index.
* What is the old behavior before changes and new behavior after changes? Old behavior was creating target docs without routing. New behaviour creates target docs with routing.
https://github.com/opensearch-project/opensearch-migrations/issues/1162
Is this a backport?
No
1. Updated unit tests for BulkDocSection
2. Updated EndToEndTest to verify routing
3. Manually tested with ES 6.8
Note: I will raise followup PR with test-resource snapshot with routing along with updated tests for LuceneDocumentsReaderTest
For more information on following …
=> [RFS] Use shard routing from source while bulk indexing.

MetadataMigration/build.gradle, MetadataMigration/src/main/java/org/opensearch/migrations/MigrateOrEvaluateArgs.java, MetadataMigration/src/main/java/org/opensearch/migrations/commands/Evaluate.java, MetadataMigration/src/main/java/org/opensearch/migrations/commands/Migrate.java, MetadataMigration/src/main/java/org/opensearch/migrations/commands/MigratorEvaluatorBase.java, MetadataMigration/src/main/resources/log4j2.properties, MetadataMigration/src/test/java/org/opensearch/migrations/CustomTransformationTest.java, MetadataMigration/src/test/java/org/opensearch/migrations/EndToEndTest.java, RFS/src/main/java/org/opensearch/migrations/bulkload/models/ComponentTemplate.java, RFS/src/main/java/org/opensearch/migrations/bulkload/models/GlobalMetadata.java, RFS/src/main/java/org/opensearch/migrations/bulkload/models/Index.java, RFS/src/main/java/org/opensearch/migrations/bulkload/models/IndexMetadata.java, RFS/src/main/java/org/opensearch/migrations/bulkload/models/IndexTemplate.java, RFS/src/main/java/org/opensearch/migrations/bulkload/models/LegacyTemplate.java, RFS/src/main/java/org/opensearch/migrations/bulkload/models/MigrationItem.java, RFS/src/main/java/org/opensearch/migrations/bulkload/transformers/CompositeTransformer.java, RFS/src/main/java/org/opensearch/migrations/bulkload/transformers/TransformerToIJsonTransformerAdapter.java, RFS/src/main/java/org/opensearch/migrations/bulkload/version_es_6_8/GlobalMetadataData_ES_6_8.java, RFS/src/main/java/org/opensearch/migrations/bulkload/version_es_6_8/IndexMetadataData_ES_6_8.java, RFS/src/main/java/org/opensearch/migrations/bulkload/version_es_7_10/GlobalMetadataData_ES_7_10.java, RFS/src/main/java/org/opensearch/migrations/bulkload/version_es_7_10/IndexMetadataData_ES_7_10.java, RFS/src/main/java/org/opensearch/migrations/bulkload/version_os_2_11/GlobalMetadataData_OS_2_11.java, RFS/src/main/java/org/opensearch/migrations/bulkload/version_os_2_11/IndexMetadataData_OS_2_11.java, RFS/src/main/java/org/opensearch/migrations/bulkload/version_universal/RemoteIndexMetadata.java, RFS/src/main/java/org/opensearch/migrations/bulkload/version_universal/RemoteMetadata.java, RFS/src/main/java/org/opensearch/migrations/bulkload/worker/IndexRunner.java, RFS/src/main/java/org/opensearch/migrations/metadata/CreationResult.java, transformation/src/main/java/org/opensearch/migrations/transformation/JsonTransformerForDocumentTypeRemovalProvider.java
Add metadata transformations with metadata tuples.
Adds SKIPPED migration failure type
* Category: New feature
* Why these changes are required? Users may require metadata transformations across versions, particularly to support multi-type indices.
* What is the old behavior before changes and new behavior after changes? No Metadata tuples, no shown output for skipped indexes/templates, no transformation support in metadata
#1115 
https://opensearch.atlassian.net/browse/MIGRATIONS-2157
Unit tests added, aws testing for log format and location
For more information on following Developer Certificate of Origin …
=> Add metadata transformations with metadata tuples

.github/workflows/sonar-qube.yml
Add baseline sonarqube issue count of 89 so that commits that don't make it worse pass. As we resolve issues, we can reduce this number to avoid regressions. 
* Category: Test fix
* Why these changes are required? GHA should show as passing for commits that do not introduce issues
* What is the old behavior before changes and new behavior after changes? All commits and PRs showed failing sonarqube
N/A
GHA
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certif …
=> Add baseline sonarqube issue count

DocumentsFromSnapshotMigration/src/main/java/org/opensearch/migrations/RfsMigrateDocuments.java, RFS/src/main/java/org/opensearch/migrations/bulkload/common/OpenSearchClient.java, RFS/src/main/java/org/opensearch/migrations/metadata/CreationResult.java
Fix several minor issues in RFS codebase
- Fix keyword ordering of DOC_CONFIG_PARAMETER_ARG_PREFIX
- Created exception for Unexpected status code to remove duplicated error strings
- Make check for hasCompatibilityModeEnabled null safe
- Use isEmpty instead of size() == 0
- Remove redundant static modifier on CreationFailureType
=> Fix several minor issues in RFS codebase

RFS/src/main/java/org/opensearch/migrations/bulkload/transformers/Transformer_ES_6_8_to_OS_2_11.java, transformation/src/main/java/org/opensearch/migrations/transformation/rules/IndexMappingTypeRemoval.java, transformation/src/test/java/org/opensearch/migrations/transformation/rules/IndexMappingTypeRemovalTest.java
Fix bug handle empty mappings when removing mapping types
- Resolves #1177
=> Fix bug handle empty mappings when removing mapping types

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/backfill_rfs.py
The customer-facing issue [#1172](https://github.com/opensearch-project/opensearch-migrations/issues/1172) highlights confusion arising from the use of the term "shard" to describe both console backfill and console snapshot operations. The shard count in a snapshot does not necessarily match the shard count in a backfill. For instance, some indices (and their corresponding shards) may be excluded from the backill. To address this, we propose changing the terminology from "shards" to "worker items" for backfill operations. This change aligns with potential future updates where multiple worker items may be associated with a single shard.
* What is the old behavior before changes and new behavior after changes? `console backfill status --deep-check` displays items as …
=> MIGRATIONS-2243 - Replace 'Shards' verbiage with 'Fragment' in console backfill status

DocumentsFromSnapshotMigration/src/test/java/org/opensearch/migrations/bulkload/PerformanceVerificationTest.java, RFS/src/main/java/org/opensearch/migrations/bulkload/common/LuceneDocumentsReader.java
We were incorrectly reporting documents that were missing a reference id as an error message whereas this is on par with a missing source body at warning level.
Updated the error message to include slightly more context for troubleshooting.
- Lower logging level when there is no usable reference idenifiers
- Add the directory path in logging messages from troubleshooting
- Rename docId -> docSegId since it represents the position of the document as opposed to he other identifiers to improve readability
- Resolves _Fix log message when unable to find a reference id for a document_ https://opensearch.atlassian.net/browse/MIGRATIONS-2252
Locally examined the error messages
For …
=> Fix log message when unable to find a reference id for a document

TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/PayloadAccessFaultingMap.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NettyDecodedHttpRequestPreliminaryTransformHandler.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NettyJsonBodyAccumulateHandler.java
Flip the default should throw behavior for HttpJsonMessageWithFaultingPayload to opt-in rather than opt-out.
HttpJsonMessageWithFaultingPayload throws by default - so it could be run even if it wasn't within a transform - like from within a LoggingHandler, which is what I was observing when I added some more logging.  The worst part was that it created other errors which then caused the message to be processed in a very different way.
* Category Bug fix
* Why these changes are required? When logging levels go up, the system behaves as if logging weren't enabled!
https://opensearch.atlassian.net/browse/MIGRATIONS-2242
gradle/cicd
By submitting this pull request, I confirm that my contribution is made under the terms …
=> Flip the default should throw behavior for HttpJsonMessageWithFaultingPayload

MetadataMigration/src/test/java/org/opensearch/migrations/EndToEndTest.java
After recently reviewing metadata migration end to end test cases I
noticed there was 56 different tests, this was a large increase, taking
nearly 20 minutes of runtime.  Reviewing the parameters of the tests
I'm running evaluate and then immediately following migrate, this
should reduce the test cases by nearly half and increase of coverage
using http and snapshot sources.
I have tweaked how we use templates moving back to the logic of
legacy templates for ES 6.X and using both index and index component
templates for future ES versions, which should be another 30%
reduction.
- Resolves _Speed up Metadata end to end test cases_ https://opensearch.atlassian.net/browse/MIGRATIONS-2253
Package | Tests | Failures | Ignored | Duration | Success rate
-- | -- | -- | -- | -- | -- …
=> Reduce the number of cluster start/stops for Metadata end to end tests

transformation/transformationPlugins/jsonMessageTransformers/jsonTypeMappingsSanitizationTransformer/src/main/resources/jinjava/typeMappings/documentBackfillItems.j2
For backfill bulk items, don't transcribe the documents through jinjava but just have it pulled from the source doc.
* Category Performance enhancement
* Why these changes are required? To reduce wasted transcriptions and parses
* What is the old behavior before changes and new behavior after changes? Should be no semantic differences.
No Jira
CICD tests
=> For backfill bulk items, don't transcribe the documents through jinjava but just have it pulled from the source doc.

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/middleware/replay.py
`console replay status` was printing poorly -- it showed the actual tuple being returned from the model function, e.g.:
```
(<ReplayStatus.STOPPED: 4>, 'Running=0\nPending=0\nDesired=0')
```
This PR is a very small change to fix that, so that it prints the same way as `console backfill status`. The middleware function for replayer status was just missing an `on_success` handler to deal with this case.
```
(.venv) bash-5.2# console backfill status
BackfillStatus.STOPPED
Running=0
Pending=0
Desired=0
(.venv) bash-5.2# console replay status
ReplayStatus.STOPPED
Running=0
Pending=0
Desired=0
```
Bug discovered during demo prep
Manual, see above.
For more information on following …
=> Fix display of `console replay status`

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/tuple_reader.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/data/valid_tuple_missing_component.json, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_tuple_reader.py
While prepping for the demo today, we encountered a bug while checking the tuples. A tuple was throwing the following error (shown with a minimal-ish valid tuple):
```
(.venv) sh-5.2# echo '{"sourceRequest":{"Request-URI":"/_snapshot/migration_assistant_repo/rfs-snapshot","Method":"DELETE","HTTP-Version":"HTTP/1.1","payload":{"inlinedTextBody":""}},"targetRequest":{"Request-URI":"/_snapshot/migration_assistant_repo/rfs-snapshot","Method":"DELETE","payload":{"inlinedTextBody":""}},"targetResponses":[{"Date":["Tue, 10 Dec 2024 21:07:03 GMT"],"Content-Type":["application/json; charset=UTF-8"],"Status-Code":404,"Reason-Phrase":"Not Found","response_time_ms":49,"payload":{"inlinedJsonBody":{}}}],"connectionId":"024ad2fffe460aed-00000007-00000ac1-61aca27669436ce2-fdb9a98a.1563","numRequests":4," …
```
=> Add robustness for missing TupleComponents

.github/workflows/CI.yml, MetadataMigration/src/test/java/org/opensearch/migrations/BaseMigrationTest.java, MetadataMigration/src/test/java/org/opensearch/migrations/MultiTypeMappingTransformationTest.java, RFS/src/testFixtures/java/org/opensearch/migrations/bulkload/framework/SearchClusterContainer.java
Enable MultiTypeMappingTransformationTest
Fixes issue in GHA by not depending on local mounts and instead copying the required files into the container.
Reverts docker caching recently added in gradle gha actions, will be addressed with [MIGRATIONS-2265](https://opensearch.atlassian.net/browse/MIGRATIONS-2265)
* Category: Test fix
* Why these changes are required? Ensure full coverage of tests in GHA
* What is the old behavior before changes and new behavior after changes? Test Disabled, now enabled
No jira created
GHA, verified working locally too …
=> Enable MultiTypeMappingTransformationTest

.github/ISSUE_TEMPLATE/BUG_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Reduce and clarify instructions on issues and pr templates
- See updated Issue template, [link](https://github.com/peternied/opensearch-migrations/issues/new?assignees=&labels=bug%2C+untriaged&projects=&template=BUG_TEMPLATE.md&title=%5BBUG%5D).
- See updated PR template, [link](https://github.com/peternied/opensearch-migrations/compare/main...frontend-proto).
=> Update Issue and PR templates

TrafficCapture/dockerSolution/src/main/docker/elasticsearchTestConsole/runTestBenchmarks.sh, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/cluster.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_cluster.py
In https://github.com/opensearch-project/opensearch-benchmark-workloads/pull/514 OSB added waiting for green for cluster operations. This commit fixes the workload on the prior commit since our use case uses a single node cluster that is always in yellow state. 
Fixed workload on commit:
https://github.com/opensearch-project/opensearch-benchmark-workloads/commit/440ce4b1fc8832b6b7673bdcec948cce3ee87e7e
- https://opensearch.atlassian.net/browse/MIGRATIONS-2279
See GHA
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate- …
=> Fix OSB on specific working workload commit

.flake8, TrafficCapture/dockerSolution/src/main/docker/elasticsearchTestConsole/Dockerfile, TrafficCapture/dockerSolution/src/main/docker/elasticsearchTestConsole/testDocumentGenerator.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/Dockerfile, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-console-stack.ts
Miscellaneous improvements as noticed during demo testing:
* Unable to run watch command on migration-console: added proper package to dockerfile
* No indication of time when running commands: added time and adjusted bash prompt for migration console
`(21:48:43) migration-console (~) ->`
* Added basic multipart requests to testDocumentGenerator.py on migration console
* Increased migration console default resources as more operations are performed from this container
N/A
Local testing, verify on Jenkins
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/C …
=> Add Demo Testing Fixes/Improvements

RFS/src/main/java/org/opensearch/migrations/bulkload/common/S3Uri.java
When running metadata command part of the output shows the S3 uri and it was not human readable.
```
S3Uri(bucketName=bucket-name, key=, uri=s3://bucket-name)
S3Uri(bucketName=bucket-name, key=, uri=s3://bucket-name)
S3Uri(bucketName=bucket-name, key=with/suffix, uri=s3://bucket-name/with/suffix)
S3Uri(bucketName=bucket-name, key=with/suffix, uri=s3://bucket-name/with/suffix)
```
```
Starting Metadata Evaluation
Clusters:
Source:
Snapshot: ELASTICSEARCH 7.10.0 S3Repo(s3RepoUri=org.opensearch.migrations.bulkload.common.S3Uri@639cb788)
```
N/A
N/A Simple UX change …
=> Make sure that S3Uri are human readable when printed

deployment/migration-assistant-solution/bin/app.ts
Removes this confusing CDK `BootstrapVersion` parameter that isn't necessary for our CFN deployments through the AWS console: 
N/A
CDK unit tests
- [N/A] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.
=> [Solutions CDK] Remove bootstrap version CFN parameter

.github/workflows/full_pr_e2e_test.yml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/middleware/clusters.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_clusters_middleware.py
Update console_link logic on clearing snapshots with missing repo
Fixes [error](https://migrations.ci.opensearch.org/job/rfs-default-e2e-test/2992/console)
```
[31m[1mERROR   [0m console_link.middleware.clusters:clusters.py:101 Error clearing snapshots from repository 'migration_assistant_repo': 404 Client Error: Not Found for url: [https://vpc-os-cluster-rfs-integ1-gqpxocxdv5z7hnfmjpvtekpvsy.us-east-1.es.amazonaws.com:443/_snapshot/migration_assistant_repo/_all](https://vpc-os-cluster-rfs-integ1-gqpxocxdv5z7hnfmjpvtekpvsy.us-east-1.es.amazonaws.com/_snapshot/migration_assistant_repo/_all)
```
Updates GHA to run with both 7.10 and 6.8 tests (will apply after pr is merged)
N/A
Added unit test
- [N/A] Public documentation issue/PR …
=> Update console_link logic on clearing snapshots with missing repo

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_cluster.py
Fix flaky test by fixing time.
[MIGRATIONS-2294](https://opensearch.atlassian.net/browse/MIGRATIONS-2294)
Fixed unit test, validated by including a time.sleep(1) before the second signing before and after this change to induce it to fail consistently. This change fixed it.
=> Fix flaky sigv4 test

RFS/src/test/java/org/opensearch/migrations/bulkload/common/BulkDocSectionTest.java
Mark largeSourceDoc as slowTest for memory control
Fixes error encountered during GHA run
```
Caused by: java.lang.OutOfMemoryError: Java heap space
...
at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:4039)
at org.opensearch.migrations.bulkload.common.BulkDocSectionTest.testLargeSourceDoc(BulkDocSectionTest.java:193)
...
```
[Source](https://scans.gradle.com/s/qr5ozgp4hjs6e/tests/task/:RFS:test/details/(N%2FA)/Gradle%20Test%20Executor%2043?expanded-stacktrace=WyIwLTEiXQ&top-execution=1)
GHA …
=> Mark largeSourceDoc as slowTest for memory control

MetadataMigration/src/main/java/org/opensearch/migrations/commands/MigratorEvaluatorBase.java, MetadataMigration/src/test/java/org/opensearch/migrations/MultiTypeMappingTransformationTest.java, RFS/src/main/java/org/opensearch/migrations/bulkload/transformers/CompositeTransformer.java, RFS/src/main/java/org/opensearch/migrations/bulkload/transformers/FanOutCompositeTransformer.java, RFS/src/main/java/org/opensearch/migrations/bulkload/transformers/Transformer.java, RFS/src/main/java/org/opensearch/migrations/bulkload/transformers/TransformerToIJsonTransformerAdapter.java, RFS/src/main/java/org/opensearch/migrations/bulkload/transformers/Transformer_ES_6_8_to_OS_2_11.java, RFS/src/main/java/org/opensearch/migrations/bulkload/transformers/Transformer_ES_7_10_OS_2_11.java, RFS/src/main/java/org/opensearch/migrations/bulkload/worker/IndexRunner.java, RFS/src/test/java/org/opensearch/migrations/bulkload/common/http/FanOutCompositeTransformerTest.java, RFS/src/test/java/org/opensearch/migrations/bulkload/transformers/Transformer_ES_7_10_OS_2_11Test.java, transformation/src/main/java/org/opensearch/migrations/transformation/rules/IndexMappingTypeRemoval.java, transformation/src/test/java/org/opensearch/migrations/transformation/rules/IndexMappingTypeRemovalTest.java
1. Updates MetadataMigration to receive and handle List returned by IJsonTransformer, this adds support for 1:many custom transforms (e.g. multi type index split)
* Note: A future change will add support for built in transform to handle the split case.
2. Updates the TypeSanitization built in transformer to throw an error when encountering multi type index and behavior is not set to Union. (Previous behavior was to return Unsupported which would ignore the transformation which would result in an error during cluster put) 
[MIGRATIONS-2271](https://opensearch.atlassian.net/browse/MIGRATIONS-2271)
Existing code paths tested by existing tests.
1:Many transformations will be tested during a followup PR which adds multi type split as a provided javascript transform.
By submitting this pull …
=> Metadata add 1:many custom transformations

.github/workflows/sonar-qube.yml
We were using a deprecated versino of the upload-artifact, switched from v3 -> v4.
- Sonarqube github action is broken https://opensearch.atlassian.net/browse/MIGRATIONS-2313 
PR Check will confirm this is working correctly.
=> Fix broken sonarqube upload

.github/workflows/sonar-qube.yml, DocumentsFromSnapshotMigration/src/main/java/org/opensearch/migrations/RfsMigrateDocuments.java, DocumentsFromSnapshotMigration/src/test/java/org/opensearch/migrations/bulkload/EndToEndTest.java, DocumentsFromSnapshotMigration/src/test/java/org/opensearch/migrations/bulkload/ParallelDocumentMigrationsTest.java, DocumentsFromSnapshotMigration/src/test/java/org/opensearch/migrations/bulkload/SourceTestBase.java, RFS/src/main/java/org/opensearch/migrations/bulkload/version_os_2_11/OpenSearchWorkCoordinator_OS_2_11.java, RFS/src/main/java/org/opensearch/migrations/bulkload/workcoordination/OpenSearchWorkCoordinator.java, RFS/src/main/java/org/opensearch/migrations/bulkload/workcoordination/WorkCoordinatorFactory.java, RFS/src/test/java/org/opensearch/migrations/bulkload/workcoordination/OpenSearchWorkCoodinatorTest.java, RFS/src/test/java/org/opensearch/migrations/bulkload/workcoordination/WorkCoordinatorErrantAcquisitonsRetryTest.java, RFS/src/test/java/org/opensearch/migrations/bulkload/workcoordination/WorkCoordinatorTest.java, RFS/src/testFixtures/java/org/opensearch/migrations/bulkload/SupportedClusters.java
* Checkpoint.  This PR updates the RFS code to use a version-specific OpenSearchWorkCoordinator.  Currently, there's only one supported version (OS 2), which presents the existing behavior.  E.g. there's no functional changes in this PR, it just sets up the plumbing to add Coordinators for new versions (like ES 6.8).
* https://opensearch.atlassian.net/browse/MIGRATIONS-2285
Ran the unit tests
=> Added version-specific OpenSearchWorkCoordinators

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/Dockerfile, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/services.yaml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/loadServicesFromParameterStore.sh
Removes requirement that migrations `services.yaml` has to be loaded in from environment in order to get console library bash completion
https://opensearch.atlassian.net/browse/MIGRATIONS-2236
Local testing
=> [Console Library] Allow console library completion everywhere

RFS/src/main/java/org/opensearch/migrations/bulkload/common/OpenSearchClientFactory.java
[Sonarqube Fix](https://sonarqube.tools.solutions.aws.dev/project/issues?resolved=false&inNewCodePeriod=true&types=BUG&id=opensearch-migrations-aws-solutions%3Amainline&open=AZRnPZIntC8JI7w--v8d) for `Call "Optional#isPresent()" or "!Optional#isEmpty()" before accessing the value.` issue. The `isEmpty` check was already happening, but it wasn't explicitly linked with the `get`. I think this should solve the issue.
=> Sonarqube Fix - Ensure optional is present before `get`

.github/CODEOWNERS, MAINTAINERS.md
This PR adds Jugal to the list of Maintainers. It also allows Jugal to gain membership access to this opensearch project.
N/A
N/A
=> Update maintainer list to add Jugal

CreateSnapshot/src/test/java/org/opensearch/migrations/TestCreateSnapshot.java, RFS/src/main/java/org/opensearch/migrations/bulkload/common/OpenSearchClientFactory.java, RFS/src/test/java/org/opensearch/migrations/bulkload/common/OpenSearchClientFactoryTest.java
This change updates the `_cluster/settings` API call in the OpenSearchClient to include default settings. The modification ensures that the compatibility mode check accurately reflects the current cluster state, even when the setting is at its default value. This addresses an issue where the compatibility mode value could remain `true` even after being disabled via the Migration Console.
Specifically, this change:
- Updates the `getClusterVersion()` method in OpenSearchClient.java to use `_cluster/settings?include_defaults=true`.
- Modifies corresponding test cases in OpenSearchClientTest.java to reflect this change.
By including default settings in the API call, we can correctly interpret the compatibility mode status in both scenarios.
This PR addresses the issue described in …
=> Correctly read compatibility mode from cluster settings when it was unset

.github/workflows/full_pr_e2e_test.yml
Require maintainer trigger on Jenkins jobs
`pull_request_target` events are special: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository
With changes...
When a maintainer creates a PR, pushes a change, or retries the Jenkins action on their own PR, the action will execute as normal:
However, when a non-maintainer performs any action that would trigger the Jenkins action (same as list above), the action will fail early with error message:
N/A
Personal fork testing
For more information on following Developer Certificate of Origin and signing off your …
=> Update Jenkins job to require maintainer trigger

.github/workflows/release-drafter.yml
Upload SBOM to release
Currently SBOM are published to release run artifacts, but not release https://github.com/opensearch-project/opensearch-migrations/actions/runs/12717975529
Verified on my fork using a modified version of the [workflow](https://github.com/AndreKurait/opensearch-migrations/actions/runs/12837665875/workflow)
https://github.com/AndreKurait/opensearch-migrations/actions/runs/12837665875/job/35802627618
=> Fix upload SBOM to release artifacts

DocumentsFromSnapshotMigration/src/test/java/org/opensearch/migrations/bulkload/LeaseExpirationTest.java, DocumentsFromSnapshotMigration/src/test/java/org/opensearch/migrations/bulkload/SourceTestBase.java
Add a 6.8 source cluster to the automated Lease Expiration tests that validate sub-shard RFS behavior.
https://opensearch.atlassian.net/browse/MIGRATIONS-2297
This is an updated test.
=> Add 6.8 source to lease expiration test

deployment/cdk/opensearch-service-migration/lib/service-stacks/reindex-from-snapshot-stack.ts, deployment/cdk/opensearch-service-migration/test/reindex-from-snapshot-stack.test.ts
Fix RFS argument parsing error caused by floating point precision in maxShardSizeBytes.
Does not occur for default 80, but showed up when using `900` on release 2.1.3.
Confirmed behavior with unit test and added fix.
```
2025-01-21 23:56:22,983 INFO o.o.m.RfsMigrateDocuments [main] Starting RfsMigrateDocuments with workerId =ip-10-0-149-200.ec2.internal Exception in thread "main" com.beust.jcommander.ParameterException: "--max-shard-size-bytes": couldn't convert "1063004405760.0001" to a long at com.beust.jcommander.converters.LongConverter.convert(LongConverter.java:38) at com.beust.jcommander.converters.LongConverter.convert(LongConverter.java:28) at com.beust.jcommander.JCommander.convertValue(JCommander.java:1443) at com.beust.jcommander.ParameterDescription.addValue(ParameterDescripti …
```
=> Fix RFS argument parsing error caused by floating point precision in maxShardSizeBytes

build.gradle
When passed target/exclude spotless is doing its own file scan, instead of being able to build off of gradle's internal scan - gradle has a really fast implementation and in fully supports gradle's caching interface.
Anecdotally on my machine `./gradlew spotlessApply` went from 10s -> 4s and when up-to-date takes ~2s.
- Resolves https://opensearch.atlassian.net/browse/MIGRATIONS-2229
Local task checking
=> Improve spotless speed

vars/trafficReplayDefaultE2ETest.groovy
See title
```
[INFO ] 2025-01-31 12:28:28,702788 [main] TrafficReplayer - Starting Traffic Replayer with id=ip-12-0-2-118.ec2.internal
Only one main parameter allowed but found several: "https://<target-cluster>:443" and "--transformer-config-base64"
```
I removed target cluster endpoint here
N/A
Jenkins testing
=> [Bug] Jenkins Replayer test needs updated transformation arg name

DocumentsFromSnapshotMigration/src/test/java/org/opensearch/migrations/bulkload/LeaseExpirationTest.java, RFS/src/main/java/org/opensearch/migrations/bulkload/common/DocumentReindexer.java, RFS/src/main/java/org/opensearch/migrations/bulkload/common/LuceneDocumentsReader.java, RFS/src/test/java/org/opensearch/migrations/bulkload/common/LuceneDocumentsReaderTest.java
Refactor Segment Sorting into lucene version agnostic way.
Required for compatibility with lucene  < 9
Existing subshard tests verify segments are sorted correctly.
- [] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.
=> Refactor Segment Sorting into lucene version agnostic way

build.gradle, vars/defaultIntegPipeline.groovy
Fix spotless configuration cache issue with 8.12 since https://github.com/opensearch-project/opensearch-migrations/pull/1256:
```
> Error while evaluating property 'lineEndingsPolicy' of task ':TrafficCapture:trafficCaptureProxyServer:spotlessJava'.
> Spotless JVM-local cache is stale. Regenerate the cache with
rm -rf .gradle/configuration-cache
To make this workaround obsolete, please upvote https://github.com/diffplug/spotless/issues/987
```
By updating to Spotless 7.0.0+
Also fix
```
'indentWithSpaces' is deprecated, use 'leadingTabsToSpaces' in your gradle build script instead.
```
[MIGRATIONS-2386](https://opensearch.atlassian.net/browse/MIGRATIONS-2386)
Ran jenkins with it in GHA
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
=> Fix spotless configuration cache issue by updating to version 7.0.2

DocumentsFromSnapshotMigration/src/test/java/org/opensearch/migrations/bulkload/ParallelDocumentMigrationsTest.java, RFS/src/main/java/org/opensearch/migrations/bulkload/common/RestClient.java, RFS/src/main/java/org/opensearch/migrations/bulkload/workcoordination/OpenSearchWorkCoordinator.java
Worker Coordination does not retry on connection timeout. Observed with target self-managed cluster behind NLB (no ALB)
```
2025-02-05 09:08:26,485 INFO o.o.m.b.w.DocumentsRunner [reactor-http-epoll-4] Reindexing completed for Index REDACTED Shard 0 2025-02-05 09:08:26,485 INFO o.o.m.b.w.DocumentsRunner [main] Docs migrated 
2025-02-05 09:08:26,610 WARN r.n.h.c.HttpClientConnect [reactor-http-epoll-3] [2346c986-71, L:/10.0.154.183:34540 - R:REDACTED/REDACTED:443] The connection observed an error, the request cannot be retried as the headers/body were sent io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer
```
[MIGRATIONS-2387](https://opensearch.atlassian.net/browse/MIGRATIONS-2387)
Existing test suite, will later add more failure case testing …
=> Add retry for worker coordination

CreateSnapshot/build.gradle, DataGenerator/build.gradle, DocumentsFromSnapshotMigration/build.gradle, MetadataMigration/build.gradle, RFS/build.gradle, TrafficCapture/captureProtobufs/build.gradle, TrafficCapture/dockerSolution/build.gradle, TrafficCapture/trafficCaptureProxyServer/build.gradle, TrafficCapture/trafficCaptureProxyServerTest/build.gradle, build.gradle, buildSrc/build.gradle, dashboardsSanitizer/build.gradle, gradle/wrapper/gradle-wrapper.properties
This reverts commit dc5dced034f5008a9886072032aa08d220264b07.
Reverts the gradle upgrade to 8.12.1 (#1256) because it causes issues with the dependency pom.xml file during the release workflow (see: https://github.com/opensearch-project/opensearch-migrations/actions/runs/13168301259/job/36753514331).
=> Revert "Upgrade gradle to 8.12.1 (#1256)"

.github/workflows/sonar-qube.yml
[In version 25.2.0, Sonarqube removed support of the `password` option](https://sonarsource.atlassian.net/issues/?jql=fixVersion%20%3D%2016130%20AND%20issuetype%20%21%3D%20Task%20ORDER%20BY%20status%20DESC%2C%20created%20ASC%20), which we are using. We should move to using the `token` option, but in the meantime this freezes us to the docker image before that change so that we can continue to get sonarqube data while fix this. 
https://opensearch.atlassian.net/browse/MIGRATIONS-2389
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#develo …
=> Lock sonarqube version to pre-25.2

commonDependencyVersionConstraints/build.gradle
Updates netty to the latest stable release, 4.1.118.Final
All tests pass locally.
=> Update netty to 4.1.118.Final

jenkinsTests/build.gradle
Update groovy to version 3.23, which includes an update for its dependency, testng, to 7.5.1, which resolves a CVE.
Automated tests passing
=> Update groovy to version 3.23

commonDependencyVersionConstraints/build.gradle
We already had a pinned version of this dependency but are updating to handle a CVE that occurs in 2.5.0 and below.
Automated tests pass
=> Update json-smart to 2.5.1

TrafficCapture/trafficCaptureProxyServerTest/build.gradle, commonDependencyVersionConstraints/build.gradle
Updates xstream, which is a dependency of Apache JMeter to version 1.4.21, which handles a CVE.
Automated tests
=> Update xstream to 1.4.21

test/awsRunInitBootstrap.sh
This pipeline https://migrations.ci.opensearch.org/job/solutions-cfn-create-vpc-test/ has been timing out at the init bootstrap step. This PR gives it an extra 5 minutes to complete. We don't have much control over speeding up this process.
=> Increase the timeout for initBootstrap in the solution-cfn-create-vpc pipeline from 25 to 30 min

dashboardsSanitizer/src/test/java/org/opensearch/migrations/dashboards/SanitizerTest.java
Make sure sanitizer test ignores whitespace
On windows machines the line-ending behavior can cause output to include a trailing new-line that causes incorrect test failures.
- Related #1296 
Ran test on windows machine, previously it failed now it passes.
=> Make sure sanitizer test ignores whitespace

testHelperFixtures/src/testFixtures/java/org/opensearch/migrations/matchers/HasLineCount.java
Fixed the test assertion that was hard coded to look for `\n` character instead of system line ending.
Ran test on windows machine, previously it failed now it passes.  I'm refraining from adding additional CI checks for windows development, as this project _could_ run on windows hosts, I don't think that is a priority for this project and the associated overhead.
=> Make HasLineCount test work on non-linux environments

.github/workflows/CI.yml, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/NettyPacketToHttpConsumer.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/datahandlers/NettyPacketToHttpConsumerTest.java
Fix race condition where `readTimeoutMillis` may be accessed before it is set. This is because it was being used in an asynchronous callback setup in activateLiveChannel though initialized right afterwards.
Observed in [gha run](https://scans.gradle.com/s/jdpvxlyrg7sss/tests/task/:TrafficCapture:trafficReplayer:slowTest/details/org.opensearch.migrations.replay.datahandlers.NettyPacketToHttpConsumerTest/testThatPeerResetTriggersFinalizeFuture(boolean%2C%20boolean)%5B1%5D?top-execution=1)
```
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "java.time.Duration.toMillis()" because "this.readTimeoutDuration" is null |  
...
  | at org.opensearch.migrations.replay.datahandlers.NettyPacketToHttpConsumer.lambda$activateLiveChannel$3(NettyPacketToHttpConsumer …
```
=> Fix race condition causing failed request replay

transformation/transformationPlugins/jsonMessageTransformers/jsonTypeMappingsSanitizationTransformer/README.md, transformation/transformationPlugins/jsonMessageTransformers/jsonTypeMappingsSanitizationTransformer/src/main/java/org/opensearch/migrations/transform/TypeMappingsSanitizationTransformer.java, transformation/transformationPlugins/jsonMessageTransformers/jsonTypeMappingsSanitizationTransformer/src/main/resources/js/typeMappingsSanitizer.js, transformation/transformationPlugins/jsonMessageTransformers/jsonTypeMappingsSanitizationTransformer/src/test/java/org/opensearch/migrations/transform/TypeMappingsSanitizationCreateIndexTest.java, transformation/transformationPlugins/jsonMessageTransformers/jsonTypeMappingsSanitizationTransformer/src/test/java/org/opensearch/migrations/transform/TypeMappingsSanitizationDocBackfillTest.java, transformation/transformationPlugins/jsonMessageTransformers/jsonTypeMappingsSanitizationTransformer/src/test/java/org/opensearch/migrations/transform/TypeMappingsSanitizationMetadataTest.java, transformation/transformationPlugins/jsonMessageTransformers/jsonTypeMappingsSanitizationTransformer/src/test/java/org/opensearch/migrations/transform/TypeMappingsSanitizationTransformerBulkTest.java, transformation/transformationPlugins/jsonMessageTransformers/jsonTypeMappingsSanitizationTransformer/src/test/java/org/opensearch/migrations/transform/TypeMappingsSanitizationTransformerTest.java, transformation/transformationPlugins/jsonMessageTransformers/jsonTypeMappingsSanitizationTransformerProvider/README.md, transformation/transformationPlugins/jsonMessageTransformers/jsonTypeMappingsSanitizationTransformerProvider/src/main/java/org/opensearch/migrations/transform/TypeMappingSanitizationTransformerProvider.java, transformation/transformationPlugins/jsonMessageTransformers/jsonTypeMappingsSanitizationTransformerProvider/src/test/java/org/opensearch/migrations/replay/TypeMappingsSanitizationProviderTest.java, vars/fullES68SourceE2ETest.groovy
Update regexIndexMappings to regexMappings with map structure
From 
```
"regexIndexMappings": [
[
"(.*)",
".*",
"$1"
]
]
```
to
```
"regexMappings": [
{
"sourceIndexPattern": "(.*)",
"sourceTypePattern": ".*",
"targetIndexPattern": "$1"
}
]
```
[MIGRATIONS-2407](https://opensearch.atlassian.net/browse/MIGRATIONS-2407)
See GHA and 6.8 test
Updated in https://github.com/opensearch-project/documentation-website/pull/9164/files
=> Update regexIndexMappings to regexMappings with map structure

.github/workflows/CI.yml, TrafficCapture/build.gradle, build.gradle, jenkinsTests/src/test/groovy/JenkinsPipelineTestRunner.groovy
We currently have one GHA run for all the gradle tests, this can make runs take >40 minutes when a change impacts multiple parts of the project (e.g. transformations).
This change splits up this execution over parallel jobs while retaining existing functionality with codecov etc.
This achieves this by aggregating the jacoco and non-jacoco test tasks in order to enforce jacoco artifact upload on those tasks while executing all test tasks.
[MIGRATIONS-2411](https://opensearch.atlassian.net/browse/MIGRATIONS-2411)
See GHA and Codecov stats …
=> Parallel gradle gha

TrafficCapture/dockerSolution/src/main/docker/elasticsearchTestConsole/testDocumentGenerator.py
This change eliminates the need to manually provide endpoint and authentication details. The script now fetches these details from the `migration-services.yaml` file. It also leverages `boto3` to obtain AWS session credentials from within the migration console, improving security and ease of use.
flake8
./gradlew test 
./gradlew spotlessCheck
./gradlew spotlessApply
=> testDocumentGenerator fetches endpoint and auth from config file

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/utils.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_cluster.py, deployment/cdk/opensearch-service-migration/lib/network-stack.ts, docs/ClientTrafficSwinging.md
Opensearch Managed Service for Sigv4 auth requires the sigv4 signature to not have a port specified, this complicates adding the capture proxy between the service if the listener is on a non-443 port.
For the Migration Console, we will update our cluster sigv4 logic to exclude the port on the host prior to signing.
For the ALB, we will move the standard weighted listener to the 443 port instead of the current 9200 one.
https://opensearch.atlassian.net/browse/MIGRATIONS-2421
Verified with the migration console that sigv4 works with a vpc cluster on port 9201 (the capture proxy direct listener)
For more information on following Developer Certificate of Origin and signing off …
=> Update Sigv4 and ALB according to Opensearch logic

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/command_runner.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/metadata.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/snapshot.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_command_runner.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_snapshot.py
This modifies recent changes around printing output with the `command_runner` in the console library to allow printing output on commands that fail (which is very helpful for metadata commands) as well as always logging output regardless of success or failure
There is a decision here to not print failed command output to the console as a default, as I have found cases like snapshot create produce several stack traces on failure which we likely don't want to put in front of a user as a default, but give the option to explore this with the `-v` flag
N/A
Local testing …
=> [Bug] Fix metadata output with console library

CreateSnapshot/README.md
Add details of command usage required when creating snapshots on Managed OpenSearch 1.x source clusters. Had to pass in a few extra arguments after auth failed from ["anonymous not authorized" errors](https://repost.aws/knowledge-center/anonymous-not-authorized-opensearch).
This docs update might be too small to want to commit, but given that the compatibility guide mentions OpenSearch 1.3.x -> 2.14 [is supported](https://github.com/opensearch-project/opensearch-migrations/blob/0b868bd042bd1c67d2153624aae4068966003420/README.md?plain=1#L55) I thought it could be useful for future users.
**Context**: I'm evaluating whether my team can use OpenSearch Migrations to migrate our 1.x clusters. Adding my learnings from trying to step through the guide in a test environment.
n/a
Manual testing: …
=> Add usage warning for creating snapshot on Amazon Managed OpenSearch

TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/TypeMappingTransformationTest.java, transformation/transformationPlugins/jsonMessageTransformers/jsonTypeMappingsSanitizationTransformer/src/main/resources/js/typeMappingsSanitizer.js
Implement replayer support for `/<index>/_bulk` and `/<index>/<type>/_bulk` in type mapping sanitization transformer
Users can run bulk requests with either `/_bulk` or `/index/_bulk`, `/<index>/<type>/_bulk` but our Type Mappings Sanitization transformer only works for /_bulk.  This task should work for when the index is specified.  When multiple types/indices are used, it should change the URI to use the more general /_bulk format.
[MIGRATIONS-2268](https://opensearch.atlassian.net/browse/MIGRATIONS-2268)
Unit tests added
https://github.com/opensearch-project/documentation-website/pull/9363
For more information on following Developer Certificate of Origin and signing off …
=> Implement replayer support for /<index>/_bulk in type mapping sanitization transformer

DataGenerator/src/test/java/org/opensearch/migrations/DataGeneratorEndToEnd.java, DocumentsFromSnapshotMigration/src/test/java/org/opensearch/migrations/bulkload/CustomRfsTransformationTest.java, DocumentsFromSnapshotMigration/src/test/java/org/opensearch/migrations/bulkload/LeaseExpirationTest.java, DocumentsFromSnapshotMigration/src/test/java/org/opensearch/migrations/bulkload/ParallelDocumentMigrationsTest.java, DocumentsFromSnapshotMigration/src/test/java/org/opensearch/migrations/bulkload/ProcessLifecycleTest.java, MetadataMigration/src/test/java/org/opensearch/migrations/MultiTypeMappingTransformationTest.java, RFS/src/testFixtures/java/org/opensearch/migrations/bulkload/SupportedClusters.java, RFS/src/testFixtures/java/org/opensearch/migrations/bulkload/framework/SearchClusterContainer.java, transformation/src/main/java/org/opensearch/migrations/VersionMatchers.java
The documentation, as of #1336, refers to migrating to 2.19. This PR updates our tests to use the 2.19.1 image.
Because it's kind of silly to have to go change our code in N places every time we are testing against a new version, I also added an `OS_LATEST` alias so that as we add a new image, we only have to add its image info and update the alias in one file, and we'll automatically test against it in most places.
I did _not_ change our `SupportedCluster` matrix to use `OS_LATEST` because I think that's a helpful spot to be very explicit about exactly what we test against. Open to feedback if others disagree.
https://opensearch.atlassian.net/browse/MIGRATIONS-2430
Primarily a test-related change.
By submitting this pull request, I confirm that my contribution is made under the terms of …
=> Update most tests to use OS_LATEST image, currently 2.19.1

deployment/cdk/opensearch-service-migration/lib/network-stack.ts
Loosen capture proxy healthcheck error codes
Customers may get 403 due to sigv4 requirements on their cluster.
=> Loosen capture proxy healthcheck error codes

test/awsRunInitBootstrap.sh
More details in issue, this change should ensure an EC2 instance is ready to execute an SSM command before we send it one
https://opensearch.atlassian.net/browse/MIGRATIONS-2432
Manual and Jenkins testing
=> [Bug] Check that SSM is ready on EC2 instance in Jenkins pipeline

deployment/migration-assistant-solution/lib/solutions-stack.ts, deployment/migration-assistant-solution/test/solutions-stack.test.ts
This change accomplishes the following:
* Use a different CIDR range for VPC than default to avoid IP conflicts with VPC peering
* Include stage in VPC and subnet names
N/A
Cloud deployment testing: https://migrations.ci.opensearch.org/job/solutions-cfn-create-vpc-test/2701/console
=> Minor improvements to Solutions CFN naming and CIDR range

RFS/src/test/java/org/opensearch/migrations/bulkload/integration/SnapshotStateTest.java
The Solutions pipeline is blocked by mysterious failures in the SnapshotState tests. While we debug that, this is an emergency measure to unblock it. We believe this is a low risk test to disable because the logic is covered by other tests.
=> Add disabled annotation to SnapshotState tests

MetadataMigration/src/test/java/org/opensearch/migrations/EndToEndTest.java, RFS/src/main/java/org/opensearch/migrations/bulkload/common/ObjectNodeUtils.java, RFS/src/main/java/org/opensearch/migrations/bulkload/version_os_2_11/GlobalMetadataCreator_OS_2_11.java, RFS/src/main/java/org/opensearch/migrations/bulkload/version_os_2_11/IndexCreator_OS_2_11.java, RFS/src/main/java/org/opensearch/migrations/parsing/ObjectNodeUtils.java, RFS/src/test/java/org/opensearch/migrations/parsing/ObjectNodeUtilsTest.java
Bug fixes and E2E test update for handling ES 5.x default metadata
https://opensearch.atlassian.net/browse/MIGRATIONS-2433
Python E2E testing and Java E2E tests
=> Bug fixes and E2E test update for handling ES 5.x default metadata

.github/dependabot.yml
Every week will make a consolidated PR for our major dependency areas for npm, gradle, and github actions.
- Resolves [MIGRATIONS-2448 | Enable dependabot for dependencies](https://opensearch.atlassian.net/browse/MIGRATIONS-2448)
Its running on [my fork](https://github.com/peternied/opensearch-migrations/pulls/app%2Fdependabot), now the only changes needed to get outstanding PRs merged is fixes due to incoming library changes.
=> Add weekly dependabot configuration

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/tuple_reader.py
python:S3776 Refactor to reduce complexity in parse_tuple
=> [Sonarqube] python:S3776 Refactor to reduce complexity in parse_tuple

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/Pipfile, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/Pipfile.lock, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/Pipfile, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/Pipfile.lock, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/backfill_base.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/backfill_rfs.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/kubectl_runner.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/replayer_base.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/replayer_k8s.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/utils.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/setup.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_backfill_logic.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_backfill_rfs_k8s.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_kubectl_runner.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_replay.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/integ_test/common_utils.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/integ_test/full_tests.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/integ_test/ma_workflow_test.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/integ_test/replayer_tests.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/integ_test/test_cases/ma_test_base.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/integ_test/test_cases/multi_type_tests.py
To allow for more accurate status tracking of K8s pods, this introduces a `TERMINATING` status for K8s services so that users and our test cases can better tell when a service has completely scaled down. 
This change also refactors to use the K8s python client as there doesn't seem to be a good reason to use the `kubectl` command directly
N/A
Unit testing and local K8s testing
=> Provide terminating status for K8s console library

DocumentsFromSnapshotMigration/src/main/java/org/opensearch/migrations/RfsMigrateDocuments.java, DocumentsFromSnapshotMigration/src/test/java/org/opensearch/migrations/bulkload/SourceTestBase.java, TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/proxyserver/testcontainers/CaptureProxyContainer.java, TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/proxyserver/testcontainers/KafkaContainerTestBase.java, TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/proxyserver/testcontainers/annotations/TestContainerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/e2etests/KafkaRestartingTrafficReplayerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/kafka/KafkaCommitsWorkBetweenLongPollsTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/kafka/KafkaKeepAliveTests.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/kafka/KafkaTrafficCaptureSourceLongTermTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/kafka/KafkaTrafficCaptureSourceTest.java
Fix RFS Shutdown logic during exception cases
Set kafka tests as isolated
Remove deprecated usage of KafkaContainer in favor of ConfluentKafkaContainer
[MIGRATIONS-2461](https://opensearch.atlassian.net/browse/MIGRATIONS-2461)
[MIGRATIONS-2460](https://opensearch.atlassian.net/browse/MIGRATIONS-2460)
GHA
=> Fix RFS Shutdown logic during exception cases and set kafka tests as isolated

transformation/transformationPlugins/jsonMessageTransformers/jsonTypeMappingsSanitizationTransformer/src/main/resources/js/typeMappingsSanitizer.js
javascript:S5852 Improve perf on bulk request matcher
- Related https://opensearch.atlassian.net/browse/MIGRATIONS-2427
=> javascript:S5852 Improve perf on bulk request matcher

transformation/transformationPlugins/jsonMessageTransformers/jsonTypeMappingsSanitizationTransformer/src/main/resources/js/typeMappingsSanitizer.js
Use const in fieldName
SonarQube issue
N/A
=> Use const in fieldName

.github/workflows/CI.yml, TrafficCapture/dockerSolution/src/main/docker/elasticsearchTestConsole/Dockerfile, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/datahandlers/NettyPacketToHttpConsumerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/e2etests/SlowAndExpiredTrafficStreamBecomesTwoTargetChannelsTest.java
Improve test reliability, increasing timeout of kafka tests and preventing overloading gha by running with one less gradle worker than cpu cores.
~30 second improvement going from # CPU Cores workers to # CPU Cores - 1 workers.
~30 second improvement going from GCC to clang compiler with some build exclusions
See GHA
=> Improve test reliability

deployment/cdk/opensearch-service-migration/cdk.context.json
Disable trafficReplayerServiceEnabled by default with comments on enabling capture and replay
For most customers, including those using capture and replay, it benefits them to deploy Migration Assistant without C&R enabled and to enable deploying the services after basic connectivity and auth is ensured for a faster and successful deployment with easier troubleshooting.
N/A
=> Disable trafficReplayerServiceEnabled by default with comments on enabling services

DocumentsFromSnapshotMigration/src/test/java/org/opensearch/migrations/bulkload/EndToEndTest.java, RFS/src/main/java/org/opensearch/migrations/bulkload/lucene/SegmentNameSorter.java, RFS/src/main/java/org/opensearch/migrations/bulkload/lucene/version_6/LeafReader6.java, RFS/src/main/java/org/opensearch/migrations/bulkload/lucene/version_7/LeafReader7.java, RFS/src/main/java/org/opensearch/migrations/bulkload/lucene/version_9/LeafReader9.java, RFS/src/main/java/org/opensearch/migrations/bulkload/version_es_6_8/ElasticsearchConstants_ES_6_8.java, RFS/src/main/java/org/opensearch/migrations/bulkload/version_es_7_10/ElasticsearchConstants_ES_7_10.java, RFS/src/testFixtures/java/org/opensearch/migrations/bulkload/http/ClusterOperations.java, transformation/src/main/java/org/opensearch/migrations/VersionMatchers.java
This fixes the segmentName null issue mentioned here - https://github.com/opensearch-project/opensearch-migrations/issues/1405 by unwrapping the inner SegmentReader when there is a FilterCodecReader wrapper.
Refer to [SoftDeletesDirectoryReaderWrapper](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/index/SoftDeletesDirectoryReaderWrapper.java#L130-L153) for more details on wrapping behavior.
Previous logic, assumed soft deletes were added in ES 6 when they were actually added in ES 6.5 as an opt-in feature. This miss meant we were previously recreating soft-deleted docs on the target (target could contain more docs than valid docs on the source)
Previous testing on soft deletes either did not successfully create snapshots with soft deletes, or did not …
=> Fix soft delete behavior with ES 6 and above

DocumentsFromSnapshotMigration/src/test/java/org/opensearch/migrations/bulkload/EndToEndTest.java, DocumentsFromSnapshotMigration/src/test/java/org/opensearch/migrations/bulkload/SourceTestBase.java, RFS/src/main/java/org/opensearch/migrations/bulkload/common/BulkDocSection.java, RFS/src/testFixtures/java/org/opensearch/migrations/bulkload/http/ClusterOperations.java, build.gradle
Fixes #1417: RFS Handling of docs with fields over 20M characters in length
Existing behavior threw error
```
"ERROR o.o.m.b.w.DocumentsRunner [DocumentBatchReindexer-1] Error prevented some batches from being processed 
org.opensearch.migrations.bulkload.common.BulkDocSection$DeserializationException: Failed to parse source doc: String 
value length (20054016) exceeds the maximum allowed (20000000, from `StreamReadConstraints.getMaxStringLength()`) 
at org.opensearch.migrations.bulkload.common.BulkDocSection.parseSource(BulkDocSection.java:71)"
```
- Resolves #1417
- Resolves [MIGRATIONS-2469](https://opensearch.atlassian.net/browse/MIGRATIONS-2469)
Added unit test
For more …
=> Fixes #1417: RFS Handling of docs with fields over 20M characters in length

build.gradle
[CVE] Bump commons-io from 2.13.0 -> 2.18.0
- Resolves CVE-2024-47554
=> [CVE] Bump commons-io from 2.13.0 -> 2.18.0

deployment/cdk/opensearch-service-migration/lib/common-utilities.ts, deployment/cdk/opensearch-service-migration/lib/migration-assistance-stack.ts, deployment/cdk/opensearch-service-migration/lib/migration-services-yaml.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-console-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/reindex-from-snapshot-stack.ts, deployment/cdk/opensearch-service-migration/lib/stack-composer.ts, deployment/cdk/opensearch-service-migration/options.md, deployment/cdk/opensearch-service-migration/test/reindex-from-snapshot-stack.test.ts
This change introduces the ability to specify an existing snapshot with CDK and have that be utilized by downstream services such as RFS and the Migration Console
Sample CDK context option:
```
{
"snapshot": {
"snapshotName": "test-snapshot",
"s3Uri": "s3://snapshot-bucket-123456789012-us-east-2/snapshot-repo",
"s3Region": "us-east-2"
}
}
```
~Still verifying this works on a deployed environment and seeing if any issues exist to use this cross-region or cross-account as well as adding official documentation~
Documentation PR to review here: https://github.com/opensearch-project/documentation-website/pull/9573
https://opensearch.atlassian.net/browse/MIGRATIONS-2219
CDK tests …
=> BYOS - Bring Your Own Snapshot for CDK

TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/e2etests/KafkaRestartingTrafficReplayerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/kafka/KafkaTestUtils.java, transformation/transformationPlugins/jsonMessageTransformers/jsonMessageTransformerLoaders/src/main/java/org/opensearch/migrations/transform/TransformerConfigUtils.java
While running a RFS test case with a bad transformation config the container went down without clear signals to the problem, it took many attempts to discover. Adding new exception to allow for callers to manage failures.
Also removed a couple other suspect System.exit() use cases where exception throwing should be sufficient.
- Related https://github.com/opensearch-project/opensearch-migrations/pull/1438
=> Remove system.exit usage in components

RFS/src/main/java/org/opensearch/migrations/bulkload/common/DocumentReindexer.java, RFS/src/test/java/org/opensearch/migrations/bulkload/common/DocumentReindexerTest.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/PacketToTransformingHttpHandlerFactory.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/ResultsToLogsConsumer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayer.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/ResultsToLogsConsumerTest.java, transformation/transformationPlugins/jsonMessageTransformers/jsonMessageTransformerInterface/build.gradle, transformation/transformationPlugins/jsonMessageTransformers/jsonMessageTransformerInterface/src/main/java/org/opensearch/migrations/transform/ThreadSafeTransformerWrapper.java, transformation/transformationPlugins/jsonMessageTransformers/jsonMessageTransformerInterface/src/test/java/org/opensearch/migrations/transform/ThreadSafeTransformerWrapperTest.java
Fixes `java.lang.IllegalStateException: Multi threaded access requested by thread Thread[targetConnectionPool-4-2,5,main] but is not allowed for language(s) js.` caused in ResultsToLogsConsumer with non thread safe transformations.
=> Use LocalThread for ResultsToLogsConsumer transformations

build.gradle
Remove RFS from excluded maven publishing
GHA runs through publish prereqs for a package https://github.com/opensearch-project/opensearch-migrations/actions/runs/14499105148/job/40674222682?pr=1451
=> Remove RFS from excluded maven publishing

.github/workflows/CI.yml
Updates docker cache action to `AndreKurait/docker-cache@0.6.0` which provides an update for v4 of the underlying action cache
Fixes:
Failed to save: Unable to reserve cache with key docker-Linux-ae4aa90a40aa7d4bb6f161c37c0add12a35d0b4b, another job may be creating this cache. More details: This legacy service is shutting down, effective April 15, 2025. Migrate to the new service ASAP. For more information: https://gh.io/gha-cache-sunset
Test on GHA on my fork https://github.com/AndreKurait/opensearch-migrations/actions/runs/14503181939/job/40687342804 …
=> Update docker cache to AndreKurait/docker-cache@0.6.0

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/cluster.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_cli.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_cluster.py
@AndreKurait reported that `console clusters curl` throws `Error: Invalid value for '-X' / '--request': 'HEAD' is not one of 'GET', 'POST', 'PUT', 'DELETE'` for an attempted HEAD request.
This adds it as a valid HTTP method and verifies that.
n/a
Added two unit tests to verify behavior at the cluster model and the CLI level.
=> [Console Lib] Support http head requests

MetadataMigration/src/main/java/org/opensearch/migrations/cli/Items.java, MetadataMigration/src/test/java/org/opensearch/migrations/cli/ItemsTest.java
It was possible to have a null exception or a null message that would case error printing to thrown an exception - and not have context on what the source of the failure was.  Fixing an issue reported by a customer.
=> Metadata better handle null exception messages

CreateSnapshot/src/main/java/org/opensearch/migrations/CreateSnapshot.java, CreateSnapshot/src/test/java/org/opensearch/migrations/TestCreateSnapshot.java, DocumentsFromSnapshotMigration/src/test/java/org/opensearch/migrations/bulkload/EndToEndTest.java, RFS/src/main/java/org/opensearch/migrations/bulkload/common/FileSystemSnapshotCreator.java, RFS/src/main/java/org/opensearch/migrations/bulkload/common/S3SnapshotCreator.java, RFS/src/main/java/org/opensearch/migrations/bulkload/common/SnapshotCreator.java, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/README.md, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/cli.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/middleware/clusters.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/snapshot.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/utils.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/services.yaml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_cli.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_metadata.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_snapshot.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_snapshot_cleanup.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_source_cluster_multiversion.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/integ_test/backfill_tests.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/integ_test/full_tests.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/integ_test/ma_workflow_test.py, deployment/cdk/opensearch-service-migration/lib/common-utilities.ts, deployment/cdk/opensearch-service-migration/lib/migration-services-yaml.ts, deployment/cdk/opensearch-service-migration/lib/stack-composer.ts, deployment/cdk/opensearch-service-migration/options.md, deployment/cdk/opensearch-service-migration/test/reindex-from-snapshot-stack.test.ts
This change refactors out the hardcoded snapshot repository name found in several places in our code base and allows passing this name. This allows our migration console to be more customizable when it comes to creating a snapshot or performing operations such as checking the status of an external snapshot.
Also included is some refactoring of some disjoint snapshot logic in the console library to be contained within the snapshot class
- Documentation site update: https://github.com/opensearch-project/documentation-website/pull/9721
~~Test with BYOS in cloud~~
~~Fix gradle tests~~
~~Update to documentation website~~
https://opensearch.atlassian.net/browse/MIGRATIONS-2471
Unit tests, cloud testing
By submitting this pull request, I confirm that my contribution is made under the terms of …
=> Refactor hard-coded snapshot repo name to be provided

deployment/cdk/opensearch-service-migration/lib/components/capture-replay-dashboard.json, deployment/cdk/opensearch-service-migration/lib/constructs/migration-dashboard.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/reindex-from-snapshot-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/traffic-replayer-stack.ts
Dashboards cannot share the same name across all regions in an account. This change fixes deployment failures when the same stage name is used across regions along with adding simplification to the capture and replay dashboard, primarily fixing metric discovery with SEARCH, adding calculations for speedup observed and catchup time, and removing metrics that were unclear or added confusion.
[MIGRATIONS-1608](https://opensearch.atlassian.net/issues/MIGRATIONS-1608)
Jenkins run to verify successful deployment along with verifying json in AWS under a migration …
=> Update capture-replay-dashboard with rename

TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayerCore.java
TrafficStream Summary was noisy, especially for numerous packets for large requests. Reducing log level
=> Move TrafficSummary to debug logging

.github/dependabot.yml
Only update netty for patch version changes
- Related https://github.com/opensearch-project/opensearch-migrations/pull/1502 was cut attempting to move to netty 4.2
=> Only update netty for patch version changes

DocumentsFromSnapshotMigration/src/main/java/org/opensearch/migrations/RfsMigrateDocuments.java, DocumentsFromSnapshotMigration/src/test/java/org/opensearch/migrations/bulkload/EndToEndTest.java, DocumentsFromSnapshotMigration/src/test/java/org/opensearch/migrations/bulkload/SourceTestBase.java, MetadataMigration/src/main/java/org/opensearch/migrations/MigrateOrEvaluateArgs.java, MetadataMigration/src/main/java/org/opensearch/migrations/cli/ClusterReaderExtractor.java, MetadataMigration/src/main/java/org/opensearch/migrations/commands/Evaluate.java, MetadataMigration/src/main/java/org/opensearch/migrations/commands/MigratorEvaluatorBase.java, MetadataMigration/src/main/resources/log4j2.properties, RFS/src/main/java/org/opensearch/migrations/VersionStrictness.java, RFS/src/main/java/org/opensearch/migrations/bulkload/common/OpenSearchClientFactory.java, RFS/src/main/java/org/opensearch/migrations/bulkload/transformers/TransformFunctions.java, RFS/src/main/java/org/opensearch/migrations/bulkload/transformers/TransformerMapper.java, RFS/src/main/java/org/opensearch/migrations/bulkload/version_es_6_8/RemoteWriter_ES_6_8.java, RFS/src/main/java/org/opensearch/migrations/bulkload/version_es_6_8/SnapshotReader_ES_6_8.java, RFS/src/main/java/org/opensearch/migrations/bulkload/version_es_7_10/SnapshotReader_ES_7_10.java, RFS/src/main/java/org/opensearch/migrations/bulkload/version_os_2_11/RemoteWriter_OS_2_11.java, RFS/src/main/java/org/opensearch/migrations/bulkload/version_universal/RemoteReader.java, RFS/src/main/java/org/opensearch/migrations/cluster/ClusterProviderRegistry.java, RFS/src/main/java/org/opensearch/migrations/cluster/VersionSpecificCluster.java, RFS/src/test/java/org/opensearch/migrations/bulkload/common/LuceneDocumentsReaderTest.java, RFS/src/test/java/org/opensearch/migrations/bulkload/transformers/TransformerMapperTest.java, RFS/src/test/java/org/opensearch/migrations/bulkload/transformers/Transformer_ES_7_10_OS_2_11Test.java, RFS/src/test/java/org/opensearch/migrations/cluster/ClusterProviderRegistryTest.java, transformation/src/main/java/org/opensearch/migrations/UnboundVersionMatchers.java, transformation/src/main/java/org/opensearch/migrations/Version.java, transformation/src/main/java/org/opensearch/migrations/VersionMatchers.java, transformation/src/test/java/org/opensearch/migrations/UnboundVersionMatchersTest.java, transformation/src/test/java/org/opensearch/migrations/VersionMatchersTest.java
We've had issues where customers have tried to use our tooling on their cluster configuration and it was slightly outside the support ranges for both Metadata and RFS scenarios.  This allows customers to use a command line parameter to loosen the requirements.  
Added unit test cases for the new scenario, by default none of the existing tests use `loose version mode` since we don't officially support testing of these versions.
```
~/git/opensearch-migrations$ ./gradlew MetadataMigration:run --args='evaluate --snapshot-name reindex-from-snapshot --s3-local-dir /tmp/s3_files --s3-repo-uri s3://your-s3-uri --s3-region us-fake-1 --target-host http://hostname:9200 --target-username <user> --target-password <pass> --source-version ES_21_2_1'
...
Starting Metadata Evaluation
Results:
Issue(s) …
```
=> Add parameter to loosen strict version requirements for Metadata and RFS

MetadataMigration/src/main/java/org/opensearch/migrations/cli/Items.java, MetadataMigration/src/main/java/org/opensearch/migrations/commands/EvaluateResult.java, MetadataMigration/src/main/java/org/opensearch/migrations/commands/MigrateResult.java, MetadataMigration/src/main/java/org/opensearch/migrations/commands/MigrationItemResult.java, MetadataMigration/src/test/java/org/opensearch/migrations/commands/MigrationItemResultTest.java
When troubleshooting another issue saw a scenario where there were
errors in the metadata output, but nothing was reported at the bottom of
the report, fixed how this is calculated to include any fatal issues.
```
Indexes:
blog_index_2023, blog_indexandcomponent_2023, blog_legacy_2023, movies_2023
ERROR - myindexv4 failed on target cluster: Create object failed for myindexv4 [...]
WARN - already-exists already exists
Aliases:
alias_component, alias_index, alias_legacy, movies-alias
Results:
0 issue(s) detected
```
```
Indexes:
blog_index_2023, blog_indexandcomponent_2023, blog_legacy_2023, movies_2023
ERROR - myindexv4 failed on target cluster: Create object failed for myindexv4...
WARN - already-exists already exists
Aliases:
alias_component, alias_index, alias_legacy, movies-alias …
```
=> Metadata make sure all errors are counted and reported

build.gradle
Fix mergeJacocoReports after gradle refactor to correctly run all tests.
Fixes `listPublishedArtifacts` to correctly list the artifacts.
`mergeJacocoReports` not correctly resolving the test tasks
Local run
```
➜  opensearch-migrations git:(CodeCov) ✗ ./gradlew listPublishedArtifacts
Calculating task graph as configuration cache cannot be reused because file 'build.gradle' has changed.
adding task named 'test' = task ':transformation:standardJavascriptTransforms:test'
> Task :listPublishedArtifacts
org.opensearch.migrations.trafficcapture.awsUtilities
org.opensearch.migrations.trafficcapture.coreUtilities
org.opensearch.migrations.trafficcapture.CreateSnapshot
org.opensearch.migrations.trafficcapture.dashboardsSanitizer
org.opensearch.migrations.trafficcapture.DataGenerator …
```
=> Fix mergeJacocoReports after gradle refactor to correctly run all tests

build.gradle
Fix the jacocoMergeReports task so that it works with gradle caching.
No Jira
Tweaked the build.gradle file test definitions as below and ran ./gradlew jacocoMergeReports and confirmed that I had a full report in build/reports/jacoco/mergedReport/html/index.html that showed 66% coverage (I wasn't running all of the tests).
```
// Mutually exclusive tests to avoid duplication
tasks.named('test') {
systemProperty 'migrationLogLevel', 'TRACE'
useJUnitPlatform {
excludeTags('longTest', 'isolatedTest')
}
}
tasks.register('slowTest', Test) {
systemProperty 'migrationLogLevel', 'DEBUG'
useJUnitPlatform {
excludeTags 'longTest'
excludeTags 'isolatedTest'
}
}
tasks.register('isolatedTest', Test) {
maxParallelForks = 1
useJUnitPlatform {
excludeTags 'longTest'
excludeTags 'isolatedTest'
}
} …
```
=> Fix the jacocoMergeReports task so that it works with gradle caching.

deployment/migration-assistant-solution/bin/app.ts, deployment/migration-assistant-solution/lib/common-utils.ts, deployment/migration-assistant-solution/lib/eks-infra.ts, deployment/migration-assistant-solution/lib/solutions-stack-eks.ts, deployment/migration-assistant-solution/lib/solutions-stack.ts
This change adds an additional experimental template for our solutions CDK to generate a CFN stack that utilizes an EKS cluster. I expect this to change a good bit as we discover more about how we should configure EKS and what additional resources we actually need there, but should provide developers of this feature a good starting point.
The template can be generated with the following command:
```
cdk synth "Migration-Assistant-Infra-Create-VPC-v3"
```
https://opensearch.atlassian.net/browse/MIGRATIONS-2474
AWS deployment of template …
=> Add experimental path for EKS solutions deployments

DocumentsFromSnapshotMigration/build.gradle
We were building docker images for a container that used to be used, but has been phased out.
Verified the GHA results against a standard run, seeing ~2 mins less build time on the first 10 jobs I checked.
=> 10%+ speed improvement all gradle-tests legs

deployment/cdk/opensearch-service-migration/lib/service-stacks/capture-proxy-stack.ts
Increase capture proxy cpu and memory to 2vCPU/4GB which was shown to have lower more consistent latency addition versus the existing configuration even in low throughput scenarios.
Existing configuration had 15-30ms latency addition while new configuration had 5-10ms impact on client traffic after switchover.
N/A
Tested in AWS
=> Increase capture proxy cpu and memory to 2vCPU/4GB

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/metrics_source.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_metrics_source.py, deployment/cdk/opensearch-service-migration/lib/migration-services-yaml.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-console-stack.ts
Add qualifier as default dimension for cloudwatch metrics retrieval
https://opensearch.atlassian.net/browse/MIGRATIONS-2512
Adhoc test with jenkins job that was previously failing
=> Add qualifier as default dimension for cloudwatch metrics retrieval

transformation/standardJavascriptTransforms/src/metadataUpdater.js, transformation/standardJavascriptTransforms/test/metadataUpdater.test.js, transformation/transformationPlugins/jsonMessageTransformers/jsonJSTransformerProvider/build.gradle, transformation/transformationPlugins/jsonMessageTransformers/jsonJSTransformerProvider/src/main/java/org/opensearch/migrations/transform/JsonJSTransformerProvider.java, transformation/transformationPlugins/jsonMessageTransformers/jsonJSTransformerProvider/src/test/java/org/opensearch/migrations/transform/JsonJSTransformerProviderTest.java
Adding a JavaScript transformation example that can be iterated on by customer to handle mapping type conversions.  So long as this looks like a good foundation I'll adapt it to a simplified version that I'll post on the documentation website.
Can be used with string -> text, flattened -> flat_object, constant_keyword -> keyword fields as quick examples.
I'd expect the version that is posted into the documentation site to look something like the following:
```javascript
function main(context) {
/* Define rules here */
const rules = [{
when: { type: "string" }, /* Match all the key/value pairs here */
set: { type: "text" }, /* Replace them with these key/value pairs */
}, {
when: { type: "flattened" }, /* Match all the key/value pairs here */
set: { type: "flat_object" }, /* Replace them …
```
=> [Transformations] Add a 'template' for metadata updater function

TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/HttpByteBufFormatter.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/ResultsToLogsConsumerTest.java, TrafficCapture/trafficReplayer/src/test/resources/requests/raw/head_withAuthHeader.txt
TrafficReplayer's HttpByteBufFormatter, used for tuples, decodes the request and response in separate Embedded Channels. This limits the ability for the decoder to detect rfc9112 6.3.1-2 behavior where responses from HEAD and CONNECT requests are terminated after the headers ignoring content-length fields.
We now achieve correct behavior for these requests by writing a LastHttpContent.EMPTY_LAST_CONTENT in the channel if the output was empty after the entire request/response was sent. This triggers the end of the message and output is written.
This change converts from using HttpClientCodec to HttpResponseDecoder for initial response decoding and HttpServerCodec to HttpRequestDecoder for request decoding to simplify the decoding and make clearer the responsibilities. HttpClientCodec …
=> Fix TrafficReplayer behavior with HEAD and CONNECT method requests.

MetadataMigration/src/test/java/org/opensearch/migrations/EndToEndTest.java, RFS/src/main/java/org/opensearch/migrations/bulkload/common/FilterScheme.java, RFS/src/main/java/org/opensearch/migrations/bulkload/models/DataFilterArgs.java, RFS/src/test/java/org/opensearch/migrations/bulkload/common/FilterSchemeTest.java
Add exclusion list for known default/plugin ES index templates and indices.
Several system/plugin indicies do not follow the `.` prefix convention. This extends the default allowlist based on known defaults.
These indexes are either transient (cluster logs), or relate to plugins that are not compatible with Opensearch as they are.
https://opensearch.atlassian.net/browse/MIGRATIONS-2447
Unit Tests
=> Add exclusion list for known default/plugin ES index templates and indices

deployment/cdk/opensearch-service-migration/lib/common-utilities.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-console-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/reindex-from-snapshot-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/traffic-replayer-stack.ts
Customers are currently getting stuck with cross region/account migrations in part due to restrictive iam role permissions deployed by MA which restrict api calls only to clusters in the same region and account MA is deployed in. 
This change broadens resource policy in MA iam permissions to "*" for these resources customers bring in. Access will be controlled at the Resource level (e.g. opensearch access policy/FGAC) instead of customers having to self manage these and the role permissions.
[MIGRATIONS-2603](https://opensearch.atlassian.net/browse/MIGRATIONS-2603)
Unit/integ tests validate synthesis and existing permissions. Known behavior change for cross region/account access
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> Extend Migration Assistant iam permissions to allow access to cross account/region domain/collection/pipeline

jenkins/release.jenkinsFile
Maven central recently announced the end of life for publishing artifacts via nexus portal. As a part of the migration https://central.sonatype.org/pages/ossrh-eol/#process-to-migrate we made some changes to accommodate the new endpoints. See related [PR](https://github.com/opensearch-project/opensearch-build-libraries/pull/716/files#diff-4a19239627cfa172fa2404fa4a2feb02d26c4e26e1b2125e657d9f48ce4941ed)
This PR accommodates the change to successfully publish artifacts to maven central in future releases. 
- part of https://github.com/opensearch-project/opensearch-build/issues/5552
For more information on following Developer Certificate of Origin and signing off your commits, …
=> Update maven publishing workflow to accommodate nexus EOL

RFS/src/main/java/org/opensearch/migrations/bulkload/lucene/version_9/FallbackLuceneComponents.java, RFS/src/main/java/org/opensearch/migrations/bulkload/lucene/version_9/IgnoreVectorsFormat.java, RFS/src/main/resources/META-INF/services/shadow.lucene9.org.apache.lucene.codecs.KnnVectorsFormat
Add ignore support for ES8 KnnVectorsFormat.
Fixes previous error migrating documents with `dense_vector` fields
```
java.lang.IllegalArgumentException: An SPI class of type shadow.lucene9.org.apache.lucene.codecs.KnnVectorsFormat with name 'ES814HnswScalarQuantizedVectorsFormat' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene90HnswVectorsFormat, Lucene91HnswVectorsFormat, lucene92HnswVectorsFormat, Lucene94HnswVectorsFormat, Lucene95HnswVectorsFormat, Lucene99HnswVectorsFormat, Lucene99HnswScalarQuantizedVectorsFormat, Lucene99ScalarQuantizedVectorsFormat
```
https://opensearch.atlassian.net/browse/MIGRATIONS-2645
Manual testing through unit test performed to validate ES8 -> …
=> Add ignore support for ES8 KnnVectorsFormat

jenkins/release.jenkinsFile
Maven auto-publication is failing since the migration. We are following up with sonatype for the same. 
Since there are multiple steps after maven publication as well, setting this to false in order to proceed with next steps.
Please add a comment after the release and I'll take care of publishing the already staged artifacts manually to maven central. 
=> Set maven auto-publish to false

deployment/cdk/opensearch-service-migration/cdk.context.json
We had a customer with 1/3 of requests through the capture proxy was failing. Turns out they had 3 AZ on their NLB with cross zone load balancing turned off, and 2 AZ deployed on MA (by default) causing all requests through the 3rd AZ to fail.
https://opensearch.atlassian.net/browse/MIGRATIONS-2647
Existing feature
=> Update cdk.context.json with default vpcAZCount

RFS/src/main/java/org/opensearch/migrations/bulkload/common/FilterScheme.java
Fixes error during metadata on ES 8
```
ERROR - metrics-elastic_agent.apm_server failed on target cluster: Create object failed for _index_template/metrics-elastic_agent.apm_server
```
N/A
N/A
=> Add metrics-elastic_agent prefix to default list of excluded templates

DocumentsFromSnapshotMigration/src/test/java/org/opensearch/migrations/bulkload/EndToEndCompressionTest.java, RFS/build.gradle, RFS/src/main/java/org/opensearch/migrations/bulkload/lucene/version_9/ES8CompatibleZstdNoDictCompressionMode.java, RFS/src/main/java/org/opensearch/migrations/bulkload/lucene/version_9/Elasticsearch814ZstdFieldsFormat.java, RFS/src/main/java/org/opensearch/migrations/bulkload/lucene/version_9/Elasticsearch816CodecFallback.java, RFS/src/main/java/org/opensearch/migrations/bulkload/lucene/version_9/Elasticsearch8CompatibleFieldsFormat.java, gradle/libs.versions.toml, sonar-project.properties, transformation/src/main/java/org/opensearch/migrations/VersionMatchers.java
Add RFS support for ES 8 ZSTD Compression, along with tests against other versions "best_compression".
**Note, RFS still does not support ZSTD in OS 2.9+**
Note: We're not using https://github.com/opensearch-project/custom-codecs/blob/main/src/main/java/org/opensearch/index/codec/customcodecs/ZstdNoDictCompressionMode.java because based on snapshot data, it does not appear ES8 uses "subblocks" strategy as OS does, though its likely we can leverage the library for the OS2 extra compression schema support
[MIGRATIONS-2536](https://opensearch.atlassian.net/browse/MIGRATIONS-2536)
Unit testing
For more information on following Developer Certificate of Origin and signing off your …
=> Add support for ES 8 ZSTD Compression

DocumentsFromSnapshotMigration/build.gradle, DocumentsFromSnapshotMigration/docker/Dockerfile, TrafficCapture/dockerSolution/build.gradle, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/Dockerfile, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/api/system.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/cli.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/container_utils.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/api/test_system.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_cli.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_container_utils.py, buildImages/build.gradle, buildSrc/src/main/groovy/org/opensearch/migrations/common/CommonUtils.groovy, buildSrc/src/main/groovy/org/opensearch/migrations/image/RegistryImageBuildUtils.groovy, frontend/Dockerfile, frontend/build.gradle
This achieves two things:
1. Add VERSION file to all images to give traceability of version for built image
2. Allow the console link library to print the version of the Migration Assistant
```
(19:59:50) migration-console (~) -> console --version
Migration Assistant 2.4.7
```
https://opensearch.atlassian.net/browse/MIGRATIONS-2612
Python tests and gradle build testing
=> Print Migration Assistant version on Migration Console

MetadataMigration/src/main/java/org/opensearch/migrations/MetadataTransformationRegistry.java, MetadataMigration/src/main/java/org/opensearch/migrations/commands/MigratorEvaluatorBase.java, MetadataMigration/src/test/java/org/opensearch/migrations/ES7FlattenedMappingsTransformationTest.java, MetadataMigration/src/test/java/org/opensearch/migrations/ES8VectorFieldMappingsTransformationTest.java, transformation/src/main/java/org/opensearch/migrations/UnboundVersionMatchers.java, transformation/standardJavascriptTransforms/src/metadataUpdater.js, transformation/standardJavascriptTransforms/test/metadataUpdater.test.js
Add support to automatically resolve breaking change during ES 7.3+ to OS 2.7+ migrations by migrating `flattened` data type to flat_object https://docs.opensearch.org/latest/field-types/supported-field-types/flat-object/
Added test
=> Add automatic flattened to flat_object transformation

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_container_utils.py
Remove recently added `console --version` test which can cause issues when ran in environments with different permission models
N/A
N/A
=> Remove problematic `console --version` python test

TrafficCapture/dockerSolution/src/main/docker/elasticsearchTestConsole/testDocumentGenerator.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/src/cluster_tools/base/main.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/tests/conftest.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/tests/main_test.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/api/system.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/cli.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/environment.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/cluster.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/factories.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/metadata.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/snapshot.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/setup.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_backfill.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_cli.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_environment.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_search_containers.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_source_cluster_multiversion.py, sonar-project.properties
- Updated Environment class constructor to accept both config dict and config_file
- Added Environment serialization/deserialization in sessions API
- Fixed test cases to use keyword arguments for new Environment constructor
- Related [[MIGRATIONS-2593 | View session page]](https://opensearch.atlassian.net/browse/MIGRATIONS-2593)
=> Allow Environment to support non-file sources

RFS/src/testFixtures/java/org/opensearch/migrations/bulkload/SupportedClusters.java, RFS/src/testFixtures/java/org/opensearch/migrations/bulkload/framework/SearchClusterContainer.java
From recent discussions, the docker container associated with our `SearchClusterContainer.ES_V1_0` had a simple docker image URL `elasticsearch:1`. Upon looking further, this version appeared to be a duplicate image of `SearchClusterContainer.ES_V1_7_6` which corresponds to docker image URL `elasticsearch:1.7.6`.
The duplicated docker image url also does not follow the consistent format of `<major>.<minor>.<patch>`. The best action here is to drop it from all of our testing scenarios.
[MIGRATIONS-2673](https://opensearch.atlassian.net/browse/MIGRATIONS-2673)
- this task now also includes the addition of ES 1.0.0
This duplication was also confirmed when a simple `GET call` on `elasticsearch:1` resulted in 
```
...
"version" : {
"number" : "1.7.6",
...
```
By submitting this pull request, I …
=> Remove duplicated ES 1.7.6 version from test suites

RFS/src/main/java/org/opensearch/migrations/bulkload/common/RestClient.java
Reduce default RestClient connection and request timeout
We have seen some worker coordination client/server time out of sync. Upon investigation
this could occur during connection timeout issues since a reqeust could be delayed to be sent
until after a connection timesout (prior default 30s) which would cause a clock skew exception 
with the current value of 15 seconds. This change sets the value to 5 and further failure will delegate to 
the retry logic surrounding a call which would be able to reconstruct the request as needed.
Set request timeout and shorten connection timeout for rest client.
Prior default connection timeout is 30 seconds and prior to this PR there is no request timeout.
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> Set request timeout and shorten connection timeout for rest client

deployment/migration-assistant-solution/lib/solutions-stack.ts, deployment/migration-assistant-solution/test/solutions-stack.test.ts
IDMSv1 has been optional and sort of deprecated, while V2 is recommended.
This change adds IDMSv2 support via enforced tokens.
- Setting `requireImdsv2: true` in the `Instance` construct
- Yielding `AWS::EC2::LaunchTemplate` object to have `LaunchTemplateData/MetadataOptions/HttpTokens = required`
at the generated Cloudformation Template output.
> P.S: Also added a relevant test to check existence of this property in the synthesised output.
=> feat(migration-assistant-solution/idmsv2): add IDMSv2 to instance launch template

frontend/README.md
Add instructions for how to access the MA website on ECS deployment
Manually verified these instructions.
=> Add instructions for how to access the MA website on ECS deployment

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/argo_service.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/cluster.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/integ_test/conftest.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/integ_test/ma_workflow_test.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/integ_test/test_cases/backfill_tests.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/integ_test/test_cases/basic_tests.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/integ_test/test_cases/ma_argo_test_base.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/integ_test/test_cases/multi_type_tests.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/workflows/createClusterWorkflow.yaml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/workflows/createFullMigrationWithClustersWorkflow.yaml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/workflows/templates/clusterTemplates.yaml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/workflows/templates/fullMigration.yaml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/workflows/templates/fullMigrationWithClusters.yaml, deployment/k8s/charts/aggregates/migrationAssistantWithArgo/templates/resources/migrationConsole.yaml, deployment/k8s/charts/aggregates/migrationAssistantWithArgo/values.yaml, libraries/testAutomation/README.md, libraries/testAutomation/testAutomation/k8s_service.py, libraries/testAutomation/testAutomation/test_runner.py
Focus of this change was adding the ability to reuse clusters in the Argo integ test suite that is triggered by the testAutomation library. I went through a few iterations of adding this functionality with the least complexity. I am not pleased with some of the conditional logic the `MATestBase` currently has but preferred this for the time being after seeing some of the complexity/difficulty of trying to weave this conditional logic into the workflow file itself (I'm hopeful the Typescript DSL would make this much easier). A next iteration here could benefit from having a workflow step that calls some python logic to see if a cluster exists or otherwise creates the cluster, and always outputs the config to make things simpler.
As noted in the README, a command like the following, could …
=> Improve Developer UX with Argo Integration Tests

TrafficCapture/trafficCaptureProxyServer/build.gradle
Update Capture Proxy to OS 2.19.3 for security plugin usage for CVE GHSA-2rjv-cv85-xhgm (though this is unimpacting on Capture Proxy)
GHA
=> Update Capture Proxy to OS 2.19.3 for security plugin usage

test/awsRunInitBootstrap.sh
Fix some timeouts observed by increasing the overall timeout to 2 hours
https://migrations.ci.opensearch.org/job/solutions-cfn-create-vpc-test/6855/
=> Support longer boostraps in jenkins before failing

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/tests/conftest.py, test/README.md, test/defaultMigrationContext.json, vars/fullES68SourceE2ETest.groovy, vars/rfsDefaultE2ETest.groovy, vars/trafficReplayDefaultE2ETest.groovy
This fix replaces all usages of OS_2.11 with OS_2.19.
The developer pipeline is failing because it cannot find OS_2.11 image. A new update was recently merged in to register all images into our ECR, this update uses OS_2.19 since it is the latest os2x available.
No issue
=> Replace OpenSearch version 2.11 with latest 2.19 

TrafficCapture/captureKafkaOffloader/README.md, TrafficCapture/dockerSolution/src/main/docker/docker-compose.yml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/Dockerfile, deployment/cdk/opensearch-service-migration/lib/migration-assistance-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/kafka-stack.ts, deployment/cdk/opensearch-service-migration/package-lock.json, deployment/cdk/opensearch-service-migration/package.json, deployment/cdk/opensearch-service-migration/test/jest.setup.ts
This updates the Kafka version used across the project to `3.9.1`. The MSK instance in CDK is changed to `3_9_X` and the kafka clients are already on `4.0.0` and did not need update. By using a newer non-archived version of Kafka we can also utilize the CDN for the kafka distribution download in the Migration Console. Since this version could also later be added to the archived versions, there is a fallback URL to use the archive if the CDN endpoint is not available.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate- …
=> Update Kafka version to 3.9.1

deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-console-stack.ts, deployment/cdk/opensearch-service-migration/lib/stack-composer.ts, deployment/cdk/opensearch-service-migration/test/migration-services-yaml.test.ts
Ensures that when a source cluster is disabled in CDK, we still wire the version provided through the metadata block in the migration services yaml. Longer term we may want to look at aligning the differing models between handling a disabled source cluster in CDK versus the services yaml.
N/A
Jest testing
=> [Bug] Wire source version through metadata config when source is disabled

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/data/kubectl_describe_deployment_output.json, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/workflows/templates/fullMigrationWithClusters.yaml, deployment/k8s/charts/components/captureProxy/templates/deployment.yaml, deployment/k8s/charts/components/replayer/templates/deployment.yaml
This PR replaces all usages of `bitnami/kubectl:latest` with `bitnamisecure/kubectl:latest`
The `bitnami/kubectl` image has been deprecated and is no longer available, which caused pods to fail with ImagePullBackOff errors. 
No JIRA
Validated by using the Argo based tests under `libraries/testAutomation`
- executed test using `pipenv run app`
=> Update kubectl image due to deprication

vars/k8sLocalDeployment.groovy
A recent PR https://github.com/opensearch-project/opensearch-migrations/pull/1829
which got merged missed out on updating the Pipeline to accept these versions as available Source Cluster options. This PR fills that gap.
N/A
N/A
=> Enable ES 1x and 2x argo test on Jenkins

libraries/testAutomation/testAutomation/k8s_service.py, libraries/testAutomation/testAutomation/test_runner.py
Before we perform any kubectl commands we should first ensure the namespace exists
N/A
Local testing
=> Create namespace in test automation if it doesn't exist
