cluster_migration_core/cluster_migration_core/clients/rest_client_base.py, cluster_migration_core/cluster_migration_core/clients/rest_client_default.py, cluster_migration_core/cluster_migration_core/clients/rest_ops.py, upgrades/upgrade_testing_framework/robot_lib/OpenSearchRESTActions.py, upgrades/upgrade_testing_framework/robot_test_defs/common_upgrade_test.robot
-Remove references to opensearch python client and dependency
-Setup keywork mapping for unclear functions
-Add more functions to be available for use by the robot framework
* Category (Enhancement, New feature, Bug fix, Test fix, **Refactoring**, Maintenance, Documentation)
For more information on following Developer Certificate of Origin and signing off your commits, …
=> Refactoring robot tests to start using shared REST client + Removing dependency on OpenSearch Python client

TrafficReplayer/src/org/opensearch/migrations/replay/RequestResponseResponseTriple.java
We discovered (when trying to decompress gzipped message bodies in Python) that our mechanism for exporting message bodies to JSON was mangling the gzipped contents and making them invalid. This seems to have been happening when converting the byte arrays to strings to store in the json -- the deconverting process was lossy/included artifacts.
Instead, the new approach keeps the body as a byte array the entire time and base64 encodes it to embed it in the JSON triple. The body can be decoded in the traffic comparator, and from there either un-gzipped or parsed as json or a bulk request directly.
An example triple.json now:
```json
{
"request":
{
"host": "host.docker.internal",
"Request-URI": "/_cluster/health?wait_for_nodes=%3E%3D1",
"content-type": "application/json",
"Method": "GET", …
```
=> [Traffic Replayer] Preserve bytes of message body when exporting json triples

TrafficCapture/buildSrc/build.gradle, TrafficCapture/captureOffloader/build.gradle, TrafficCapture/captureProtobufs/build.gradle, TrafficCapture/nettyWireLogging/build.gradle, TrafficCapture/trafficCaptureProxyServer/build.gradle, TrafficCapture/trafficReplayer/build.gradle, plugins/opensearch/loggable-transport-netty4/build.gradle
This PR adds the ability to check for any security vulnerabilities in the dependencies.
To run the security check, run the following command:
`gradle dependencyCheckAnalyze`
[X]
=> Add plugin to check for CVE issues in dependencies to gradle files

TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NettySendByteBufsToPacketHandlerHandler.java
A single bad request or anything other kind of exception would propagate all the way to the top-level of the program and kill it.  Now, exceptions are accumulated for each request.  The number of exceptions and successful requests processed are logged to warn (or info if there were no exceptions) and the program exits cleanly w/out short circuiting any work.
No Jira
Manual testing and new unit tests
=> Request exception handling to prevent exits fix

TrafficCapture/build.gradle, TrafficCapture/captureOffloader/src/test/java/org/opensearch/migrations/trafficcapture/StreamChannelConnectionCaptureSerializerTest.java, TrafficCapture/dockerSolution/build.gradle, TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/NettyScanningHttpProxyTest.java
Fix failing unit tests.  I don't have the IDE codestyle template setup yet, so with the old reformatting diff in the history, this diff will be noisier.  Given the severity of the fixes though, I'd like to get these in ASAP while we wait to systematically address style concerns.
https://opensearch.atlassian.net/browse/MIGRATIONS-1144
`./gradle cleanTest test` repeatedly
=> More reliable unit tests

TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayer.java
* Category: 
* Bandaid
* To make tests more deterministic and to remove out-of-ordered requests that create failures.
* Previously, requests were asynchronously setup for processing and sending to the target server.  Now a message is processed entirely and the interaction with the target server is concluded _BEFORE_ returning control to the calling context, making the replayer now single-threaded with regard to processing and sending requests.
https://opensearch.atlassian.net/browse/MIGRATIONS-1180
manual testing only
For more …
=> Synchronous blocking requests

TrafficCapture/trafficCaptureProxyServerTest/build.gradle
This fixes one of the mend security issues, specifically being [CVE-2023-34623](https://www.mend.io/vulnerability-database/CVE-2023-34623)
#205 
=> Fix for CVE-2023-34623

TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/NettyPacketToHttpConsumer.java
Better reliability for the replayer to make send TLS traffic to target clusters!
* **_Category_** Bug fix
* **_Why these changes are required?_** Previously, some data was sent unencrypted and wasn't properly parsed or handled by the target cluster
* **_What is the old behavior before changes and new behavior after changes?_**
* Old results - about 87-98% accuracy on geonames and log OpenSearch benchmark datasets.
* New results - about 100% accuracy on geonames and log OpenSearch benchmark datasets.
https://opensearch.atlassian.net/browse/MIGRATIONS-1190 
dockerSolution
For more information on following Developer Certificate of Origin and signing off your commits, please …
=> Fix TLS handshake

TrafficCapture/README.md, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/runTestBenchmarks.sh
=> Backport #269 to Capture and Replay release branch 0.1.0

TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/BacksideConnectionPool.java
* Category Minor Refactoring
* Why these changes are required? readability
* What is the old behavior before changes and new behavior after changes? no changes, just a variable rename
none
build
=> Minor rename and cleanup that were leftovers from older revisions.

deployment/copilot/README.md
Minor update to Copilot readme for setting up an additional cluster
None
N/A
=> Minor update to Copilot readme for setting up an additional cluster

FetchMigration/python/requirements.txt
Update version of requests library to latest.
=> Update requests version to latest

TrafficCapture/coreUtilities/build.gradle
Update checkstyle version to fix mend issue
=> Update checkstyle version to fix mend issue

TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/AggregatedRawResponse.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/CapturedTrafficToHttpTransactionAccumulator.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/SourceTargetCaptureTuple.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TransformedTargetRequestAndResponse.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/AddCompressionEncodingTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/HeaderTransformerTest.java
=> Minor fixes to handle and propagate errors that had been getting lost through our system and into logs better.

deployment/cdk/opensearch-service-migration/package-lock.json, deployment/cdk/opensearch-service-migration/package.json
Updating `semver` version where possible.
CVEs on advisory vulnerabilities board
=> Updating Semver to latest where possible in an Attempt to fix CVEs

TrafficCapture/trafficReplayer/build.gradle, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/kafka/KafkaProtobufConsumer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/traffic/expiration/BehavioralPolicy.java, TrafficCapture/trafficReplayer/src/main/resources/log4j2.properties, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/kafka/KafkaProtobufConsumerLongTermTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/kafka/KafkaProtobufConsumerTest.java
=> SImple Manual Kafka Commit

TrafficCapture/trafficReplayer/build.gradle, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/kafka/KafkaProtobufConsumer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/traffic/expiration/BehavioralPolicy.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/kafka/KafkaProtobufConsumerLongTermTest.java
=> POC that uses testcontainers to test our KafkaProbufConsumer

.github/workflows/e2eTest.yml, test/requirements.txt, test/tests.py
This PR creates a github action that will deploy the docker solution within the action itself, and the runs an integ test against the deployed solution, therefore acting as an end-to-end testing pipeline.
[Migrations-1354](https://opensearch.atlassian.net/browse/MIGRATIONS-1354)
=> GitHub workflow to deploy and test the solution end-to-end

.github/workflows/linkCheck.yml, SECURITY.md, TrafficCapture/trafficReplayer/README.md, deployment/README.md, deployment/copilot/README.md, experimental/knowledge_base/README.md
This PR adds a github workflow to verify that all the links in the repo are valid, also fixes the invalid links that existed.
[Migrations-904](https://opensearch.atlassian.net/browse/MIGRATIONS-904)
=> Add Link Checking Workflow

deployment/cdk/opensearch-service-migration/lib/stack-composer.ts, deployment/cdk/opensearch-service-migration/test/migration-console-stack.test.ts, deployment/cdk/opensearch-service-migration/test/msk-utility-stack.test.ts, deployment/cdk/opensearch-service-migration/test/network-stack.test.ts, deployment/cdk/opensearch-service-migration/test/stack-composer-ordering.test.ts, deployment/cdk/opensearch-service-migration/test/stack-composer.test.ts
This PR adds targeted jest test cases for CDK and reduces some of the SonarQube complexity of the stack composer constructor by moving out two inner functions.
None currently
Jest testing
=> Add jest test cases for CDK and factor out some StackComposer functions

TrafficCapture/captureKafkaOffloader/src/main/java/org/opensearch/migrations/trafficcapture/kafkaoffloader/KafkaCaptureFactory.java, TrafficCapture/captureOffloader/src/main/java/org/opensearch/migrations/trafficcapture/FileConnectionCaptureFactory.java, TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/CaptureProxy.java, TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/BacksideConnectionPool.java, TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/ExpiringSubstitutableItemPool.java, TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/FrontsideHandler.java, TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/NettyScanningHttpProxy.java, TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/ProxyChannelInitializer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/CapturedTrafficToHttpTransactionAccumulator.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/SigV4Signer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayer.java
* Category Maintenance
https://opensearch.atlassian.net/browse/MIGRATIONS-1363
gradlew build
=> Easy de-linting fixes.

TrafficCapture/README.md, TrafficCapture/trafficCaptureProxyServer/README.md
This PR adds the documentation and all steps required for users to attach a Capture Proxy on a coordinator node.
=> Adding documentation for attaching a Capture Proxy to a node

TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/SourceTargetCaptureTuple.java
Remove an empty constructor that fell out of a recent change.
No Jira
gradle build
=> Minor aesthetic code cleanup to remove a code smell

TrafficCapture/trafficCaptureProxyServerTest/build.gradle, TrafficCapture/trafficReplayer/build.gradle
This PR fixes CVE-2023-42503
#331 
=> Fix for CVE-2023-42503

TrafficCapture/coreUtilities/src/main/java/org/opensearch/migrations/coreutils/MetricsAttributeKey.java, TrafficCapture/coreUtilities/src/main/java/org/opensearch/migrations/coreutils/MetricsLogger.java
=> Remove stacktrace from metrics.

TrafficCapture/dockerSolution/src/main/docker/otelcol/README.md
=> Update README.md - Remove reference to github email

TrafficCapture/nettyWireLogging/src/main/java/org/opensearch/migrations/trafficcapture/netty/LoggingHttpResponseHandler.java, TrafficCapture/replayerPlugins/jsonMessageTransformers/jsonJMESPathMessageTransformerProvider/src/main/java/org/opensearch/migrations/transform/JsonJMESPathTransformerProvider.java, TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/BacksideHandler.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/AdaptiveRateLimiter.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/ReplayEngine.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/TrafficReplayer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/HttpJsonTransformingConsumer.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/traffic/expiration/ExpiringTrafficStreamMap.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/util/DiagnosticTrackableCompletableFuture.java
=> Fix code smells.

TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/KafkaRestartingTrafficReplayerTest.java, TrafficCapture/trafficReplayer/src/test/java/org/opensearch/migrations/replay/kafka/KafkaProtobufConsumerLongTermTest.java
as a docker environment in a pipeline isn't configured properly to allow these to build.
* Category "Fix" flaky builds by disabling test code
=> Suppress the tests that use Kafka containers,

TrafficCapture/dockerSolution/src/main/docker/docker-compose.yml, deployment/cdk/opensearch-service-migration/lib/migration-assistance-stack.ts
Sync our kafka version across solution to 3.6. **Note**: This will likely require a new deployment of MSK for existing stacks.
N/A
Docker and deployment testing
=> Sync Kafka Versions across Solution

.github/CODEOWNERS
Update CODEOWNERS file to include new migrations team member and contirubtor.
=> Add Andre (andrekurait) to list of CODEOWNERS

TrafficCapture/build.gradle
Adds a new task `publishMavenJavaPublicationToMavenRepository` which publishes all subproject maven outputs to the root build/repository folder. This is needed to integrate with Maven Central publishing through jenkins
* Why these changes are required? Maven Central Publishing
* What is the old behavior before changes and new behavior after changes? New task `publishMavenJavaPublicationToMavenRepository` to save artifacts to build directory
[MIGRATIONS-1606](https://opensearch.atlassian.net/browse/MIGRATIONS-1606)
Ran task and verified correct output
```
➜  TrafficCapture git:(main) ✗ ./gradlew publishMavenJavaPublicationToMavenRepository
Configuration on demand is an incubating feature. …
```
=> Add task for outputting built jars

jenkins/release.jenkinsFile
Bug-fix in release jenkinsfile. 
=> Bug-fix in release jenkinsfile

jenkins/release.jenkinsFile
Remove unused 'arguments' parameter from jenkinsfile. Did a global search to confirm no more occurrences are present. 
=> Remove unused 'arguments' parameter

TrafficCapture/dockerSolution/build.gradle, TrafficCapture/trafficCaptureProxyServer/build.gradle, TrafficCapture/trafficCaptureProxyServerTest/build.gradle, TrafficCapture/trafficReplayer/build.gradle
Signed-off-by: Mikayla Thompson <thomika@amazon.com>### Description
* Category
Maintenance
Mend security issues
[MIGRATIONS-1674](https://opensearch.atlassian.net/browse/MIGRATIONS-1674)
=> Mend fixes for various transitive dependencies

TrafficCapture/trafficReplayer/build.gradle
This is an extension of #600 with one final fix.
=>   Fix final netty-codec-http 4.1.108 spot for Mend

FetchMigration/python/tests/test_endpoint_utils.py
Fix failing Fetch migration test case that is stopping Solutions pipeline
N/A
=> [Bug] Fix failing Fetch Migration test

TrafficCapture/dockerSolution/build.gradle
Minor bug fix of additional build dir cleanup
N/A
Local manual build testing
=> Remove Migration Console build directory on `gradle clean`

.codecov.yml, .flake8, .gitignore, SECURITY.md, TrafficCapture/dockerSolution/src/main/docker/elasticsearchWithSearchGuard/Dockerfile, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/README.md, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/osiMigrationLib/dev-requirements.txt, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/osiMigration.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/test/resources/basicAuthSourceAndSigv4Target.yaml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/test/resources/basicAuthSourceWithMultipleIndexInclusionRule.yaml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/test/resources/basicAuthSourceWithSingleIndexInclusionRule.yaml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/test/resources/sigv4SourceAndSigv4Target.yaml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/test/testOSIMigration.py, deployment/cdk/opensearch-service-migration/lib/lambda/msk-ordered-endpoints-handler.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-console-stack.ts, deployment/cdk/opensearch-service-migration/lib/stack-composer.ts, deployment/cdk/opensearch-service-migration/test/common-utilities.test.ts, deployment/cdk/opensearch-service-migration/test/network-stack.test.ts, deployment/cdk/opensearch-service-migration/test/resources/invalid-context-file.json, deployment/cdk/opensearch-service-migration/test/resources/sample-context-file.json, deployment/cdk/opensearch-service-migration/test/stack-composer.test.ts, deployment/cdk/opensearch-service-migration/test/test-utils.ts, test/README.md, test/awsE2ESolutionSetup.sh, test/awsRunIntegTests.sh, test/defaultCDKContext.json, test/operations.py, test/tests.py
Pull in latest main commits
N/A
=> E2E branch refresh with main

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/metrics_source.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_metrics_source.py
=> [Console Library] Fix self.__name__ calls (failing tests)

.github/workflows/console-library-tests.yml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/requirements.txt, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_metrics_source.py
=> [Console Library] Add region to botocore stubber client & make it a pytest fixture

buildSrc/build.gradle, commonDependencyVersionConstraints/build.gradle, coreUtilities/build.gradle, jenkinsdocker/Dockerfile, jenkinsdocker/buildFromLocal.xml
The local jenkins build hadn't been updated since the top level directories were rearranged, so builds were failing.
I also encountered java versioning issues--not sure why they suddenly popped up, but this fixes them for me (on an arm machine) and retains compatibility for an intel machine as well.
n/a
Manual
=> Fix Local Jenkins build

RFS/src/main/java/com/rfs/RunRfsWorker.java, RFS/src/main/java/com/rfs/worker/Runner.java, RFS/src/test/java/com/rfs/worker/DocumentsRunnerTest.java, RFS/src/test/java/com/rfs/worker/IndexRunnerTest.java, RFS/src/test/java/com/rfs/worker/MetadataRunnerTest.java, RFS/src/test/java/com/rfs/worker/SnapshotRunnerTest.java
Make sure exception cause is piped to PhaseFailed exception.  Found this issue while running locally and getting incomplete callstacks
Tested locally
=> Make sure exception cause is piped to PhaseFailed exception

RFS/src/test/java/com/rfs/integration/WorkerCompleteAfterErrorTest.java
Setups a couple of key types of faults and makes sure that the migration can still complete.
=> Basic worker fault integration tests stubs

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/Pipfile, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/Pipfile.lock
Add awscli to migration console
* Why these changes are required? Move to pipenv removed aws cli
* What is the old behavior before changes and new behavior after changes? cdk deploy failed with migration console, not anymore
Note: Automated testing will be included when the migration console is added to the E2E tests
N/A
Deployed container in aws and locally
=> Add awscli to migration console

TrafficCapture/dockerSolution/src/main/docker/docker-compose.yml, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/cli.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/environment.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/logic/kafka.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/kafka.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/services.yaml, deployment/cdk/opensearch-service-migration/lib/migration-services-yaml.ts, deployment/cdk/opensearch-service-migration/lib/msk-utility-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/kafka-stack.ts, deployment/cdk/opensearch-service-migration/lib/stack-composer.ts, deployment/cdk/opensearch-service-migration/test/migration-services-yaml.test.ts
Add basic Kafka command structure to console library
```
root@0abbc4d082d3:~# console kafka describe-topic-records
TOPIC                          PARTITION  RECORDS   
logging-traffic-topic          0          5         
```
N/A
Cloud and local testing
=> Add support for Kafka commands in console lib

TrafficCapture/dockerSolution/src/main/docker/docker-compose.yml, TrafficCapture/dockerSolution/src/main/docker/grafana/Dockerfile
=> Jaeger latest revision has issue exposing port 4317, uses 1 tag instead

RFS/src/main/java/com/rfs/common/ByteArrayIndexInput.java, RFS/src/main/java/com/rfs/common/ConnectionDetails.java, RFS/src/main/java/com/rfs/common/DocumentReindexer.java, RFS/src/main/java/com/rfs/common/EphemeralSourceRepoAccessor.java, RFS/src/main/java/com/rfs/common/FileSystemRepo.java, RFS/src/main/java/com/rfs/common/FilterScheme.java, RFS/src/main/java/com/rfs/common/GlobalMetadata.java, RFS/src/main/java/com/rfs/common/IndexMetadata.java, RFS/src/main/java/com/rfs/common/Logging.java, RFS/src/main/java/com/rfs/common/LuceneDocumentsReader.java, RFS/src/main/java/com/rfs/common/OpenSearchClient.java, RFS/src/main/java/com/rfs/common/PartSliceStream.java, RFS/src/main/java/com/rfs/common/S3Repo.java, RFS/src/main/java/com/rfs/common/ShardMetadata.java, RFS/src/main/java/com/rfs/common/SnapshotCreator.java, RFS/src/main/java/com/rfs/common/SnapshotRepo.java, RFS/src/main/java/com/rfs/common/SnapshotShardUnpacker.java, RFS/src/main/java/com/rfs/common/TryHandlePhaseFailure.java, RFS/src/main/java/com/rfs/common/Uid.java
A quick set of fixes to SonarQube violations
* https://opensearch.atlassian.net/browse/MIGRATIONS-1826
Ran `gradle RFS:test` and `gradle DocumentsFromSnapshotMigration:slowTest`
=> Small collection of SonarQube violation fixes

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/README.md
Catchup from missed documentation during the demo sprint.
This should pretty fully document all the `services.yaml` resources and options.
[MIGRATIONS-1817](https://opensearch.atlassian.net/browse/MIGRATIONS-1817)
n/a
=> [Console] Add services.yaml documentation

DocumentsFromSnapshotMigration/src/test/java/com/rfs/FullTest.java, RFS/src/testFixtures/java/com/rfs/framework/PreloadedDataContainerOrchestrator.java, RFS/src/testFixtures/java/com/rfs/framework/SearchClusterContainer.java
* Category Test Performance enhancement
* Why these changes are required? Tests weren't running or performing as expected
* What is the old behavior before changes and new behavior after changes? Not enough threads for larger tests and a lower likelihood of caching docker images of preloaded images (and an increased likelihood of layer bloat)
No jira.
Manual testing of the unit test
=> Performance fixes for FullTest.

.github/workflows/CI.yml
Separate spotless checks from GitHub Action test workflows
=> Separate spotless checks from GitHub Action test workflows

RFS/src/main/java/com/rfs/common/OpenSearchClient.java, RFS/src/main/java/com/rfs/worker/IndexRunner.java
* Fixing a couple bugs identified by SonarQube
* https://tiny.amazon.com/5q11fpwm/sonatoolsoluawsdevprojissu
* https://tiny.amazon.com/ocnotr1e/sonatoolsoluawsdevprojissu
* https://tiny.amazon.com/wohpkjtr/sonatoolsoluawsdevprojissu
Ran `./gradlew RFS:test`
=> A few SonarQube bugfixes

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/data/ecs_update_service_response.json, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_snapshot.py
Standardized sample account ids and changed large snapshot sizes to not match an account id regex.
https://opensearch.atlassian.net/browse/MIGRATIONS-1889
=> Fix test data files for viperlight findings

commonDependencyVersionConstraints/build.gradle
Fix for [CVE-2024-25638](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-25638)
Nothing beyond automated tests. The only component affected is `trafficCaptureProxyServerTest`, so I believe this should be pretty well covered by the automated tests. If there are specific areas of concern that should be manually exercised, please let me know.
=> Add constraint for dnsjava

.github/workflows/CI.yml
Remove volumes from image cache
~~* Why these changes are required? Seeing failures with cached images, we will have a more consistent state if we don't cache our volumes.~~
~~* What is the old behavior before changes and new behavior after changes? Volumes were included in the cache.~~
Not sure if this PR makes a difference in behavior, but seems good to remove the volumes 
n/a
Ran Actions
Before:
```
Run docker stop $(docker ps -q) && docker rm $(docker ps -aq)
9fbda3b0f65d
c9555676c79d
820314cb6436
c4a4a20d4675
c3ad8d5903d6
438c22e63541
db9b9a5b0b76
500[24](https://github.com/opensearch-project/opensearch-migrations/actions/runs/10222271505/job/28286520359#step:10:25)c9a2be6
abb3a335152c …
```
=> Remove volumes before caching

RFS/src/main/java/com/rfs/common/LuceneDocumentsReader.java
* Improved some comments on the RFS LuceneDocumentsReader class per discussion in https://github.com/opensearch-project/opensearch-migrations/pull/894
N/A
N/A
=> Improved comments on RFS LuceneDocumentsReader

docs/ClientTrafficSwinging.md
Adds documentation around ALB configuration and setup
* Category: Documentation
* Why these changes are required? Give customers who want to deep dive a place to understand the capabilities of the system.
* What is the old behavior before changes and new behavior after changes? Adds markdown in docs.
[MIGRATIONS-1962](https://opensearch.atlassian.net/browse/MIGRATIONS-1962)
View docs on github
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-ori …
=> Client Traffic Swinging Docs

deployment/cdk/opensearch-service-migration/lib/migration-assistance-stack.ts
Logs in EFS are infrequently accessed and cost savings are big for IA vs Standard tier. 
10TB in EFS Standard for a month cost $3000, whereas with this policy will cost $450 (Assuming no reads for files after 1 day, cost slightly higher based on reads for files in IA)
* Why these changes are required? Reduce cost for tuples as it is currently one of the most expensive aspects of capture and replay
* What is the old behavior before changes and new behavior after changes? EFS provisioned with tiering.
N/A
For more information on following Developer Certificate of Origin and signing off …
=> Add inteligentTiering for logs efs

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/Dockerfile
This will fix a todo that the user should know they get into the migration console on the documentation  https://github.com/opensearch-project/opensearch-migrations/wiki/Accessing-the-Migration-Console
=> Add a welcome message for the migration console

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/factories.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_backfill.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_cluster.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_kafka.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_replay.py
Lots of tests, a couple small bug fixes.
Went from:
```
TOTAL                                       1844    378    80%
```
to
```
TOTAL                                       1844    270    85%
```
locally, so 108 fewer uncovered lines.
=> Add more Migration Console test coverage

coreUtilities/src/main/java/org/opensearch/migrations/tracing/CommonScopedMetricInstruments.java, coreUtilities/src/main/java/org/opensearch/migrations/tracing/RootOtelContext.java, coreUtilities/src/main/java/org/opensearch/migrations/utils/ProcessHelpers.java
Fixed SonarQube bugs in coreUtilities
* Why these changes are required? Improve maintainability
[MIGRATIONS-2005](https://opensearch.atlassian.net/browse/MIGRATIONS-2005)
GHA
=> Fixed SonarQube bugs in coreUtilities

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/kafka.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/metadata.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/metrics_source.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_metrics_source.py
All minor stuff, mostly renaming variables to be snake case.
All 12 code smells within this tree: https://sonarqube.tools.solutions.aws.dev/code?id=opensearch-migrations-aws-solutions%3Amainline&selected=opensearch-migrations-aws-solutions%3Amainline%3Asource%2Fopensearch-migrations%2FTrafficCapture%2FdockerSolution%2Fsrc%2Fmain%2Fdocker%2FmigrationConsole%2Flib%2Fconsole_link%2Fconsole_link
=> Fix Sonarqube code smells in console lib

RFS/src/main/java/com/rfs/common/OpenSearchClient.java, transformation/src/main/java/org/opensearch/migrations/Flavor.java, transformation/src/main/java/org/opensearch/migrations/Version.java, transformation/src/main/java/org/opensearch/migrations/VersionMatchers.java, transformation/src/main/java/org/opensearch/migrations/transformation/CanApplyResult.java, transformation/src/main/java/org/opensearch/migrations/transformation/rules/IndexMappingTypeRemoval.java, transformation/src/test/java/org/opensearch/migrations/VersionTest.java
Address SonarQube findings in transformations
* Why these changes are required? Maintainability of codebase
* What is the old behavior before changes and new behavior after changes? No Behavior Change
[MIGRATIONS-2010](https://opensearch.atlassian.net/browse/MIGRATIONS-2010)
SonarQube Locally
=> Address SonarQube findings in transformations

TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/CaptureProxy.java, TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/ExpiringSubstitutableItemPool.java, TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/NettyScanningHttpProxy.java
SonarQube fixes for Capture Proxy
* Why these changes are required? Codebase Maintenance
Ran SonarQube locally, fixed most issues
=> SonarQube fixes for Capture Proxy

deployment/cdk/opensearch-service-migration/bin/app.ts, deployment/cdk/opensearch-service-migration/bin/createApp.ts, deployment/cdk/opensearch-service-migration/lib/common-utilities.ts, deployment/cdk/opensearch-service-migration/lib/lambda/acm-cert-importer-handler.ts, deployment/cdk/opensearch-service-migration/lib/migration-services-yaml.ts, deployment/cdk/opensearch-service-migration/lib/network-stack.ts, deployment/cdk/opensearch-service-migration/lib/opensearch-domain-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/capture-proxy-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-console-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-otel-collector-sidecar.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-service-core.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/reindex-from-snapshot-stack.ts, deployment/cdk/opensearch-service-migration/lib/stack-composer.ts, deployment/cdk/opensearch-service-migration/test/createApp.test.ts, deployment/cdk/opensearch-service-migration/test/lambda/acm-cert-importer-handler.test.ts, deployment/cdk/opensearch-service-migration/test/test-utils.ts
Applies some code quality fixes and adds tests to untested parts of the CDK.
Removed some dead code
* Why these changes are required? Maintenance
* What is the old behavior before changes and new behavior after changes? No behavior change
[MIGRATIONS-2003](https://opensearch.atlassian.net/browse/MIGRATIONS-2003)
Sonar qube locally. Issues went from 40 -> 7
=> Cdk maintenance and tests

.github/workflows/rfs_pr_e2e_test.yml
Removing security risk associated with using user supplied variables in context expressions with a run/script step. More details here: https://codeql.github.com/codeql-query-help/javascript/js-actions-command-injection/
N/A
Manual testing
=> Remove Jenkins Action User Supplied Context Expressions

DocumentsFromSnapshotMigration/src/main/java/org/opensearch/migrations/RfsMigrateDocuments.java
=> Reformat some more @Parameter definitions to be more readable

.github/workflows/CI.yml, .github/workflows/codecov-publish.yml
=> Disable tests for fast run

.github/workflows/CI.yml, .github/workflows/codecov-publish.yml
Fix codecov download by passing github token
Enable linting pr gate
* Why these changes are required? Fix codecov action, enable linting.
Codecov currently failing
Tested on fork
=> Codecov download token

docs/Frontend.md
=> Frontend design doc

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/README.md, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/tests/conftest.py
Set OpenSearch version for test containers
https://opensearch.atlassian.net/browse/MIGRATIONS-2223
Unit testing
=> [Cluster tools] Set OpenSearch version for test containers

TrafficCapture/dockerSolution/src/main/docker/elasticsearchTestConsole/Dockerfile, TrafficCapture/dockerSolution/src/main/docker/elasticsearchWithSearchGuard/Dockerfile, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/Dockerfile, sonar-project.properties
Fixed the following issues:
- Replace this shell form with exec form.
- Replace this invocation of wget with the ADD instruction.
Added exclusions for these issues:
- Surround this variable with double quotes; otherwise, it can lead to unexpected behavior.
- Merge this RUN instruction with the consecutive ones.
- Split this RUN instruction line into multiple lines.
- Use a specific version tag for the image.
- Fix Docker SonarQube issues https://opensearch.atlassian.net/browse/MIGRATIONS-2241
Ran sonarqube locally by using the CI workflow, verified it reports no more issues.
For more information on following Developer Certificate of Origin and signing off your commits, please …
=> Address all outstanding sonarqube docker issues

TrafficCapture/dockerSolution/src/main/docker/elasticsearchTestConsole/runTestBenchmarks.sh, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/cluster.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_cluster.py
Followup from https://github.com/opensearch-project/opensearch-migrations/pull/1202 to exclude cluster health
N/A
GHA
=> Use --exclude-tasks=check-cluster-health for OSB

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_cluster.py
Disable flaky test, task to resolve and re-enable: https://opensearch.atlassian.net/browse/MIGRATIONS-2294
N/A
N/A
=> [Console Library] Disable flaky sigv4 test

RFS/docs/DESIGN.md, RFS/docs/SNAPSHOT_READING.md
Add detailed docs about snapshot reading
[MIGRATIONS-2354](https://opensearch.atlassian.net/browse/MIGRATIONS-2354)
N/A
=> Add detailed docs about snapshot reading

CreateSnapshot/build.gradle, DataGenerator/build.gradle, DocumentsFromSnapshotMigration/build.gradle, MetadataMigration/build.gradle, RFS/build.gradle, TrafficCapture/captureProtobufs/build.gradle, TrafficCapture/dockerSolution/build.gradle, TrafficCapture/trafficCaptureProxyServer/build.gradle, TrafficCapture/trafficCaptureProxyServerTest/build.gradle, build.gradle, buildSrc/build.gradle, dashboardsSanitizer/build.gradle, gradle/wrapper/gradle-wrapper.properties
Upgrade gradle to 8.12.1 and move to supported com.gradleup.shadow
- Resolves https://opensearch.atlassian.net/browse/MIGRATIONS-2375 
CI runs, no new tests were added
=> Upgrade gradle to 8.12.1 and move to supported com.gradleup.shadow

docs/imageOverviews/opensearch-migrations-console.md, docs/imageOverviews/opensearch-migrations-reindex-from-snapshot.md, docs/imageOverviews/opensearch-migrations-traffic-capture-proxy.md, docs/imageOverviews/opensearch-migrations-traffic-replayer.md
Add initial docker documentation for ECR
* Category: Documentation
* Why these changes are required? Source for the readme on the ecr images
* What is the old behavior before changes and new behavior after changes? no behavior change
[MIGRATIONS-2097](https://opensearch.atlassian.net/browse/MIGRATIONS-2097)
N/A
=> Add initial docker documentation for ECR

commonDependencyVersionConstraints/build.gradle
Update json-smart for CVE mitigation
Update json-smart for CVE mitigation
GHA
=> Update json-smart for CVE mitigation

transformation/transformationPlugins/jsonMessageTransformers/jsonTypeMappingsSanitizationTransformer/src/main/resources/js/typeMappingsSanitizer.js, transformation/transformationPlugins/jsonMessageTransformers/jsonTypeMappingsSanitizationTransformer/src/test/java/org/opensearch/migrations/transform/TypeMappingsSanitizationMetadataTest.java
Add support for metadata transformations in TypeMappingsSanitizationTransformer #1275
[MIGRATIONS-2385](https://opensearch.atlassian.net/browse/MIGRATIONS-2385)
Added unit tests
https://github.com/opensearch-project/documentation-website/pull/9164
=> Add support for metadata transformations in TypeMappingsSanitizationTransformer

.github/workflows/sonar-qube.yml, RFS/src/main/java/org/opensearch/migrations/bulkload/models/IndexMetadata.java, RFS/src/main/java/org/opensearch/migrations/bulkload/version_os_2_11/IndexCreator_OS_2_11.java, RFS/src/main/java/org/opensearch/migrations/bulkload/workcoordination/OpenSearchWorkCoordinator.java, RFS/src/main/java/org/opensearch/migrations/bulkload/worker/IndexRunner.java, deployment/cdk/opensearch-service-migration/lib/common-utilities.ts, deployment/cdk/opensearch-service-migration/lib/components/shared-log-file-system.ts, deployment/cdk/opensearch-service-migration/lib/network-stack.ts, deployment/cdk/opensearch-service-migration/lib/service-stacks/migration-console-stack.ts, sonar-project.properties
Following sonarqube fixes alongside updating the sonarqube task to use a token for authentication
* typescript:S6582 simplify if expression condiition
* typescript:S2933 add readonly annotation on unmodified member
* typescript:S3863 consolidate ec2 imports
* typescript:S6594 Use RegExp.exec
* docker:S7026 Ignore docker ADD instead of curl
* java:S2095 Ignore try-with-resources for lucene9 index reader
* java:S1141 Refactor IndexRunner to remove nested try statements
* java:S5993 OpenSearchWorkCoordinator make constructors protected
* java:S1141 Refactor IndexCreator_OS_2_11 to remove nested try statements
* java:S3038 Remove redundant getter from IndexMetadata
- Resolves [MIGRATIONS-2389 | Sonarqube has deprecated the password property](https://opensearch.atlassian.net/browse/MIGRATIONS-2 …
=> Fix many outstanding sonarqube issues

README.md
Updates references to OpenSearch to be the latest version. Accompanying documentation website PR is here: https://github.com/opensearch-project/documentation-website/pull/9380.
https://opensearch.atlassian.net/browse/MIGRATIONS-2430
n/a
=> Update 2.14 references in readme.md to 2.19

DocumentsFromSnapshotMigration/README.md, RFS/README.md
Update RFS documentation to highlight that multiple workers are used to complete a migration
- Related #1344 
=> Update RFS documentation to highlight that multiple workers are used to complete a migration

RFS/src/test/java/org/opensearch/migrations/bulkload/workcoordination/WorkCoordinatorTest.java
Increase expiration in testAcquireLeaseForQuery to handle slower machines
Test Failing Intermittently in GHA
Re-ran GHA several times
=> Increase expiration in testAcquireLeaseForQuery to handle slower machines

docs/ScalingTrafficCaptureAndReplayer.md
Just adds a new design doc that had never gotten uploaded.
=> Replayer scaling doc

TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datahandlers/http/NettyJsonBodySerializeHandler.java
java:S3776 Refactor NettyJsonBodySerializeHandler to reduce complexity
=> [Sonarqube] java:S3776 Refactor NettyJsonBodySerializeHandler to reduce complexity

MetadataMigration/README.md, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/tests/conftest.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/search_containers.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_search_containers.py, TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/proxyserver/testcontainers/ToxiproxyContainerTestBase.java
Align container versions across tests
See GHA
=> Align container versions across tests

README.md
Adding references to Migration Assistant.
N/A
N/A
=> Add references to Migration Assistant to README.md

.github/workflows/CI.yml, .github/workflows/jenkins_tests.yml
Enable docker caching, better remove cancellation on main repo
Occasional e2e failures on docker throttled 
GHA
=> Enable docker caching, better remove cancellation on main repo

.github/workflows/sonar-qube.yml, RFS/src/main/java/org/opensearch/migrations/bulkload/common/OpenSearchClientFactory.java, sonar-project.properties
Fix a few reported sonarqube issues, these depend a bit on the exact version of sonarqube installed.
N/A
GHA
=> Fix a few reported sonarqube issues

TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/HeaderAdderHandler.java, TrafficCapture/trafficCaptureProxyServer/src/main/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/HeaderRemoverHandler.java, TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/HeaderAdderHandlerTest.java, TrafficCapture/trafficCaptureProxyServer/src/test/java/org/opensearch/migrations/trafficcapture/proxyserver/netty/HeaderRemoverHandlerTest.java
Currently, the HeaderAdderHandler and HeaderRemoverHandler only correctly performs their intended operation on the first request per connection. This change modifies them to reset between each request by triggering a reset when responses are received. A client should not send a second request until this occurs on HTTP/1.1.
Added unit test. Verified functionality end to end too.
=> Fix HeaderAdder/RemoverHandler over reused connections by resetting on response

.vscode/settings.json, DEVELOPER_GUIDE.md, TrafficCapture/dockerSolution/otelConfigs/.vscode/settings.json, TrafficCapture/dockerSolution/src/main/docker/elasticsearchTestConsole/.vscode/settings.json, TrafficCapture/dockerSolution/src/main/docker/k8sConfigMapUtilScripts/.vscode/settings.json, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/cluster_tools/.vscode/settings.json, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/console_api/.vscode/settings.json, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/.vscode/settings.json, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/.vscode/settings.json, libraries/testAutomation/.vscode/settings.json, test/cleanupDeployment/.vscode/settings.json
Configuration for VSCode python extension's intellisense and autocomplete
Ran on my machine to get python code working.
=> Configuration for VSCode python extension's intellisense and autocomplete

RFS/src/main/java/org/opensearch/migrations/bulkload/common/OpenSearchClientFactory.java, RFS/src/main/java/org/opensearch/migrations/bulkload/models/IndexMetadata.java, RFS/src/main/java/org/opensearch/migrations/bulkload/version_es_6_8/IndexMetadataData_ES_6_8.java, RFS/src/main/java/org/opensearch/migrations/bulkload/version_es_7_10/IndexMetadataData_ES_7_10.java, RFS/src/main/java/org/opensearch/migrations/bulkload/version_os_2_11/IndexMetadataData_OS_2_11.java, RFS/src/main/java/org/opensearch/migrations/bulkload/version_universal/RemoteIndexMetadata.java, RFS/src/main/java/org/opensearch/migrations/bulkload/workcoordination/OpenSearchWorkCoordinator.java, TrafficCapture/trafficReplayer/src/main/java/org/opensearch/migrations/replay/datatypes/HttpRequestTransformationStatus.java, sonar-project.properties, transformation/standardJavascriptTransforms/src/typeMappingsSanitizer.js, transformation/transformationPlugins/jsonMessageTransformers/jsonJSTransformer/src/main/java/org/opensearch/migrations/transform/JavascriptTransformer.java
Reduces sonarqube violations because we have a threshold that makes it difficult for me in my workflows if there are _any_ violations.
no jira
gradle build
=> Sonarlinting.

frontend/src/app/layout.tsx
Include a side bar with help links related to the OpenSearch Migration project.  In the code there are references for adding page references when there are additional pages to add into the project.
- Resolves https://opensearch.atlassian.net/browse/MIGRATIONS-2538
Ran locally
=> Website navigation sidebar

jenkins/release.jenkinsFile
Enable ECR publishing to public.ecr.aws/opensearchproject
https://opensearch.atlassian.net/browse/MIGRATIONS-2097
Will cut a release after this is merged
=> Enable ECR publishing to public.ecr.aws/opensearchproject

docs/Frontend.md
Update the frontend architecture with a simplified website hosting and access patterns
- Resolves https://opensearch.atlassian.net/browse/MIGRATIONS-2545
Proposed design has been vetted with existing ECS system
=> [Architecture] Simplify website hosting and access patterns

vars/k8sLocalDeployment.groovy
Attempt to fix minikube failed to start with a delete before start
E.g.
https://migrations.ci.opensearch.org/job/elasticsearch-5x-k8s-local-test/2768/execution/node/33/log/
N/A
N/A
=> Add minikube delete before start in jenkins

.github/ISSUE_TEMPLATE/MIGRATION_ONBOARDING.md
Created an onboarding template for the opensearch-migrations repo.
[MIGRATIONS-2595](https://opensearch.atlassian.net/browse/MIGRATIONS-2595)
Previewed locally. 
=> Created initial onboarding issue template for GitHub.

deployment/cdk/opensearch-service-migration/cdk.context.json
Align help text with updates in https://github.com/opensearch-project/documentation-website/pull/10082/files
N/A
N/A
=> Align help text with documentation

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/Dockerfile, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/.gitignore, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/Pipfile, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/Pipfile.lock, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/README.md, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/api/main.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/api/system.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/api/test_system.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/integ_test/common_utils.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/integ_test/test_cases/backfill_tests.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/integ_test/test_cases/basic_tests.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/integ_test/test_cases/ma_test_base.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/integ_test/integ_test/test_cases/multi_type_tests.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/start-console.sh, deployment/k8s/charts/components/migrationConsole/templates/deployment.yaml, deployment/k8s/charts/tests/testConsole/templates/deployment.yaml, frontend/nginx.conf
Add API Backend for Migration Console that is accessible via the Migration Console website.
- Closes [[MIGRATIONS-2546| [Spike] Create API service on migration console ]](https://opensearch.atlassian.net/browse/MIGRATIONS-2546)
- Added integration test case, in addition to a in k8 tests
- Manually tested locally and on k8
- Manually testing on AWS to ensure no regression
=> Add API Backend for Migration Console

MetadataMigration/src/test/java/org/opensearch/migrations/ES8VectorFieldMappingsTransformationTest.java, transformation/standardJavascriptTransforms/src/es8-vector-metadata.js
Add initial transformation for ES8 vector to knn metadata transformation.
This will evolve over time as more use cases are baked in.
N/A
Added test
=> Add transformation for ES8 vector to knn metadata transformation

gradle/libs.versions.toml
Bump commons-lang3 to 3.18.0 to resolve CVE, sorted transitive dep list
Security issue
GHA
=> Bump commons-lang3 to 3.18.0 to resolve CVE

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/.dockerignore
Minor guardrail to prevent putting undesired directories/files in migration console image
N/A
Local testing
=> Add docker ignore for migration console Dockerfile

vars/cleanupDeployment.groovy, vars/defaultIntegPipeline.groovy, vars/k8sLocalDeployment.groovy, vars/solutionsCFNTest.groovy
Add `git clean` for jenkins pipelines, for safer builds. Will produce output like below in logs:
```
+ sudo --preserve-env git clean -fd
Removing frontend/src/generated/
Removing test/migrationJenkinsContext.json
Removing test/sourceJenkinsContext.json
Removing test@tmp/
```
https://opensearch.atlassian.net/browse/MIGRATIONS-2656
Jenkins testing
=> [Bug] Add `git clean` for jenkins pipelines

vars/cleanupDeployment.groovy, vars/defaultIntegPipeline.groovy, vars/k8sLocalDeployment.groovy, vars/solutionsCFNTest.groovy
Change jenkins command permissions, to avoid creating files/directories with `root` ownership as well as properly cleanup if these files get created to not prevent subsequent run
N/A
Testing in progress
=> [Bug] Remove sudo commands that are not part of cleanup in Jenkins pipelines

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/Pipfile, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/README.md, frontend/__tests__/app/loading/loading-page.tsx, frontend/src/app/loading/page.tsx
Updates the loading page with more details and next steps.
- Related [[MIGRATIONS-2590 | Loading Page]](https://opensearch.atlassian.net/browse/MIGRATIONS-2590)
=> Update the loading page from latest round of ux reviews

MetadataMigration/src/main/java/org/opensearch/migrations/commands/MigrationItemResult.java
Prevents false positive report from sonarqube on deprecated method.
=> Fix sonarqube issues on recent merge

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/.dockerignore, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/Dockerfile.openapi, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/build.gradle, frontend/build.gradle
Generate openapi spec via docker container
- Closes [[MIGRATIONS-2663 | Enable automatic generation of sdk client]](https://opensearch.atlassian.net/browse/MIGRATIONS-2663)
=> Generate openapi spec via docker container

TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/console_link/models/snapshot.py, TrafficCapture/dockerSolution/src/main/docker/migrationConsole/lib/console_link/tests/test_snapshot_status.py, frontend/src/generated/api/types.gen.ts
Fixes strange build break that wasn't caught during CI runs
PR Checks
=> Re-add missing enum value
